service-deployment/bootstrap/webportal/webportal-ds.yaml.template
service-deployment/src/webportal/dockerfile

Fix bug in webportal deployment:
- Always pull docker image.
- Use `yarn install` instead of `npm install`.

Fix bugs in webportal deployment

---

rest-server/src/config/launcher.js
rest-server/src/models/job.js
rest-server/src/templates/yarnContainerScript.mustache

Refine rest server storage on hdfs:
- Use `path/username/jobname` structure.
- Store job config file on hdfs.

Refine rest server storage on hdfs

---

kubernetes-deployment/template/etcd.yaml.template

change mis-configuration according to https://github.com/coreos/etcd/blob/master/hack/kubernetes-deploy/etcd.yml。
Before
```
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused
```
After
```
/ # etcdctl cluster-health
member 2a686307d7e5f2d is healthy: got healthy result from http://10.240.0.18:4001
member 4f9baeb86f058c91 is healthy: got healthy result from http://10.240.0.19:4001
member 94c5ddba86d892e6 is healthy: got healthy result from http://10.240.0.20:4001
cluster is healthy
```

Change the url of listen-peer-urls and listen-client-urls. 

---

service-deployment/src/grafana/pai-clusterview-dashboard.json.template
service-deployment/src/grafana/pai-nodeview-dashboard.json.template

Have done the test and deployed at big gpu cluster. See:
Cluster view: http://10.151.40.179:3000/dashboard/db/pai_clusterview?refresh=30s&orgId=1 
Node view: http://10.151.40.179:3000/dashboard/db/pai_nodeview?refresh=30s&orgId=1 
- Add GPU usage gauge panel in cluster view
- Redesign layout of cluster view
- Set default time range and refresh time (see top right corner)
- Add drop-down box of node view (see top left corner of it)
- Remove graph titles' IP prefix
- Change GPU count to int
Other advice for revision welcomed.

update grafana node view

---

kubernetes-deployment/template/kubelet.sh.template

--image-gc-high-threshold=98. 
--image-gc-low-threshold=95
```
image-gc-high-threshold, the percent of disk usage which triggers image garbage collection. Default is 90%.
image-gc-low-threshold, the percent of disk usage to which image garbage collection attempts to free. Default is 80%.
```

Change the threshold of image gc.

---

service-deployment/cleanup-service.py

In the situation of private registry. When the cluster-configuration is cleaned up, then the last step to pull cleaning-image in the registry will fail. So I move the cluster-configuration cleaning up to the last.

Fix Bug in cleanup-service.py

---

pai-fs/fsimpl/BaseFs.py
pai-fs/pai-fs.py

delete the file if we find it has already exist in the path, and then continue the copy process.

Fix bug of copy the same file with pai-fs

---

.gitattributes
rest-server/.eslintrc.js
webportal/.eslintrc.js

Git will convert the linebreak in the file according to underlying OS (https://help.github.com/articles/dealing-with-line-endings/). In Windows, the line ending character will be automatically converted to 'CRLF' for the first time the repo is cloned to local. To fix the issue, just 3 steps:
1. Open a command line window and then go to `webportal` or `rest-server` folder.
2. Run: `node .\node_modules\eslint\bin\eslint.js src/**/*.js --fix`.
3. Run: `git add .`.
After these steps, Git will never convert the line ending characters back to 'CRLF' anymore.

[Web Portal + REST Server] Respect the linebreak style rule of ESLint.

---

rest-server/src/models/job.js
rest-server/src/templates/dockerContainerScript.mustache
rest-server/src/templates/yarnContainerScript.mustache

Add log message for EXIT trap in yarn container script and docker container script by using `set -x`. Update log files to hdfs before exit.
Can not get real line number in `trap EXIT`, pls refer to [GNU mailing list](https://lists.gnu.org/archive/html/bug-bash/2010-09/msg00021.html).

[Rest Server] Add log message for EXIT trap

---

webportal/src/app/job/job-view/job-detail-table.component.ejs
webportal/src/app/job/job-view/job-view.component.js

Features:
- No more prompting dialog for errors related to SSH info.
- The 'SSH Info' links will turn grey if:
* The job is not running, or
* The job does not contain ssh info (means it was either submitted using the old rest-server, or submitted directly using launcher, or using a non-standard docker image).
- When the 'SSH Info' links are grey, tooltips on them will explain the reason why the ssh info is not available.

[Web portal] SSH info: refine error messages.

---

service-deployment/bootstrap/prometheus/prometheus-configmap.yaml.template
service-deployment/bootstrap/prometheus/prometheus-deployment.yaml.template

From this PR prometheus will leverage kubernetes api server info to monitor node.
When nodes add and leave, prometheus can dynamic detect the live nodes and profile them.
To solve this issue #348

prometheus node discovery 

---

service-deployment/bootstrap/grafana/grafana-configuration/pai-jobview-dashboard.json.template
service-deployment/bootstrap/grafana/grafana-configuration/pai-taskroleview-dashboard.json.template
service-deployment/bootstrap/grafana/grafana-configuration/pai-taskview-dashboard.json.template

Job metrics page use new job exporter metrics & query
Page render doesn't change. Please ref https://github.com/Microsoft/pai/pull/387 pages image.
For example task view page

Job metrics page use new job exporter metrics 

---

service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template
service-deployment/bootstrap/prometheus/prometheus-configmap.yaml.template

- filter node exporter not used metrics
- remove path which node exporter have no permission
error log:
time="2018-04-16T07:53:55Z" level=error msg="Error on statfs() system call for \"/var/lib/docker/overlay2/9ce7c6d18109cad5da031f46fe78a176ae06a304df160f9b158df5b2c3ba035e/merged\": permission denied" source="filesystem_linux.go:57"
- remove deprecated prometheus configmap
For issue:
https://github.com/Microsoft/pai/issues/482
https://github.com/Microsoft/pai/issues/458

refine node exporter config & remove deprecated cadvisor config of configmap

---

pai-management/bootstrap/grafana/grafana-configuration/pai-clusterview-dashboard.json.template
pai-management/bootstrap/grafana/grafana-configuration/pai-nodeview-dashboard.json.template

memory usage at cluster view and node view.
just use 3 lines: 
Extend from PR#520, as dir change conflict
https://github.com/Microsoft/pai/pull/520

Fix:memory usage size line at node view and cluster view page

---

pai-management/README.md
pai-management/deploy.py

1. The command to cleanup deployments in `README.md` lose a parameter `-c`
2. There is a bug in `deploy.sh` when execute cleanup command. 
```
if os.path.exists(template):
```
It should be
```
if os.path.exists("bootstrap/{0}/{1}".format(serv,template)):
```

fix a bug in deploy.py when using cleanup-deployments command

---

prometheus/exporter/docker_stats.py

- lower version docker's docker stats command doesn't contain id column [longer id]
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
cf514c388f44        3.36%               8.855 MiB / 47.16 GiB   0.02%               936 B / 744 B       0 B / 0 B           15
- Change query id to container[sub id of id column] 
Then it could support both 1.12.6 and 17.09.0 docker status query docker perf metrics
Higher docker version
Client:
Version:      17.09.0-ce
API version:  1.32
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue Sep 26 22:42:18 2017
OS/Arch:      linux/amd64
Server:
Version:      17.09.0-ce
API version:  1.32 (minimum version 1.12)
Go version:   go1.8.3
Git commit:   afdb6d4
Built:        Tue …

[fix]change docker status query col id to Container

---

pai-management/kubernetesTool/servicestatus.py

When run `cleanup-service.py`, sometimes cleaning-one-shot created, but status.container_statuses still None, it will cause follow error, and cleaning-one-shot-ds will not be deleted.
```bash
daemonset.extensions "cleaning-one-shot" created
Traceback (most recent call last):
File "./cleanup-service.py", line 141, in <module>
main()
File "./cleanup-service.py", line 118, in main
while servicestatus.is_service_ready('cleaning-one-shot') != True:
File "/home/pai/pai-tools/pai-deploy/pai/pai-management/kubernetesTool/servicestatus.py", line 49, in is_service_ready
for container in pod.status.container_statuses:
TypeError: 'NoneType' object is not iterable
```

fix TypeError: 'NoneType' object is not iterable

---

pai-management/bootstrap/hadoop-service/hadoop-configuration/nodemanager-generate-script.sh
pai-management/config-patch/nodemanager-yarn-site.xml.patch

In current version, `yarn.nodemanager.resource.cpu-vcores` and `yarn.nodemanager.resource.memory-mb` are hard coded in each nodemanager's `yarn-site.xml` file where memory is `200G` and vcores is `24`. It is unsafe for yarn to allocate container on different nodes.
This pr add a feature that each nodemanager could set different `memory` and `cpu-vcores` according to nodes' hardware. 
The rule to set `cpu-vcores` and `memory-mb` is:
`cpu-vcores` = (`count` of cpu cores in current node)
`memory-mb` = (`available memory` * 0.8)

Add memory and cpu_vcores configuration for each nodemanager

---

pai-management/bootstrap/cluster-configuration/delete.sh
pai-management/bootstrap/cluster-configuration/start.sh
pai-management/bootstrap/drivers/delete.sh
pai-management/bootstrap/drivers/refrash.sh.template
pai-management/bootstrap/drivers/start.sh
pai-management/bootstrap/end-to-end-test/delete.sh
pai-management/bootstrap/frameworklauncher/refrash.sh.template
pai-management/bootstrap/frameworklauncher/start.sh
pai-management/bootstrap/grafana/delete.sh
pai-management/bootstrap/grafana/refrash.sh.template
pai-management/bootstrap/grafana/start.sh
pai-management/bootstrap/hadoop-service/delete.sh
pai-management/bootstrap/hadoop-service/refrash.sh.template
pai-management/bootstrap/hadoop-service/start.sh
pai-management/bootstrap/prometheus/delete.sh
pai-management/bootstrap/prometheus/refrash.sh.template
pai-management/bootstrap/prometheus/start.sh
pai-management/bootstrap/pylon/delete.sh
pai-management/bootstrap/pylon/refrash.sh.template
pai-management/bootstrap/pylon/start.sh
pai-management/bootstrap/rest-server/delete.sh
pai-management/bootstrap/rest-server/refrash.sh.template
pai-management/bootstrap/rest-server/start.sh
pai-management/bootstrap/webportal/delete.sh
pai-management/bootstrap/webportal/refrash.sh.template
pai-management/bootstrap/webportal/start.sh
pai-management/paiLibrary/paiService/service_delete.py
pai-management/paiLibrary/paiService/service_refrash.py
pai-management/paiLibrary/paiService/service_start.py
pai-management/paiLibrary/paiService/service_stop.py

In the [SO problem: What generates the “text file busy” message in Unix?
](https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), they says, ```The Text file busy error in specific is about trying to modify an executable while it is executing. The "Text" here refers to the fact that the file being modified is the text segment for a running program. This is a very special case, and not the generic one that your answer seems to suggest. Even so, your answer isn't entirely incorrect. – ArjunShank```
And we have a lot of shell and code will first set the permission of the script with the command ``` chmod u+x```, and with high potential, it will break the process of deployment. …

Solve Textfile busy issue when deploying service.

---

pai-management/container-setup.sh

To solve the issue: 
```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/pai/pai-management/k8sPaiLibrary/monitorTool/check_node_label_exist.py", line 24, in <module>
from ..monitorlib import nodestatus
File "/pai/pai-management/k8sPaiLibrary/monitorlib/nodestatus.py", line 21, in <module>
from kubernetes import client, config
File "/usr/local/lib/python2.7/dist-packages/kubernetes/__init__.py", line 20, in <module>
import …
```

Solve Environment Issue. 

---

cluster-configuration/services-configuration.yaml
pai-management/container-setup.sh
pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py
pai-management/paictl.py
pai-management/quick-start/services-configuration.yaml.template

Logic:
- Each VC will be assigned with (capacity / total_capacity * 100%) of the resources in the system.
- The system will automatically create the 'default' VC with 0 capacity, if 'default' VC has not been explicitly specified in the configuration file.
- The system will split resources to each VC evenly if the total capacity is 0.
- The capacity of each VC will be automatically set to 0 if it is a negative number in the configuration file.
Test cases (all passed):
- Define capacities in float numbers.
- Do not include virtualClusters section in service-configurations.yaml file.
- Do not include 'default' VC in virtualClusters section.
- Set the capacity of a VC as a negative number.
- Set the capacities of all VCs as 0.

Refine VC configuration; fix bugs

---

webportal/src/app/job/job-view/job-view.component.js

Introduced in #691
[`convertState`](/Microsoft/pai/pull/691/files#diff-297d09e3d94ba04115fb129259ce38e9L189) is used to render status column, which I copied as [`getHumanizedJobStateString`](/Microsoft/pai/pull/691/files#diff-297d09e3d94ba04115fb129259ce38e9R210) by mistake.

Web Portal: Fix status display in jobs table

---

pai-management/src/webportal/image.yaml

Introduced in #715 
This makes web portal depends on example directory in its build context.

Fix web portal build: no example files copied

---

webportal/src/app/job/job-view/job-view.component.js

Introduced in #691
[`A link`](https://github.com/Microsoft/pai/pull/691/files#diff-297d09e3d94ba04115fb129259ce38e9L183) is used to render vc column, which I copied as [`virtualCluster`](https://github.com/Microsoft/pai/pull/691/files#diff-297d09e3d94ba04115fb129259ce38e9R200) by mistake.

Web Portal: fix vc column rendering in job table

---

pai-management/src/end-to-end-test/dockerfile
pai-management/src/frameworklauncher/dockerfile
pai-management/src/hadoop-run/dockerfile.template

This fix if for #710 #711 .
Hi @abuccts,   @ydye ,
Please help reviewing this Dockerfile fix.
As discussed before, we'd better fix the base image.
Bad lucky, the Dockerfile of base image (which is src/hadoop-run/dockerfile) is out of control.
Also noticed that the 'src/hadoop-run/dockerfile' was generated on the fly, maybe someone know how we can update it?
Clean up the apt-get cache before run any apt-get command.

fix docker build apt-get related error

---

pai-management/src/base-image/dockerfile

Ref: https://serverfault.com/questions/853364/cron-and-crontab-are-missing-in-docker-image-of-ubuntu-16-04

Install Cron in base-image

---

pylon/src/nginx.conf.template

So that job detail page on web portal can correctly show the urls of app tracking page and container log page.

Rest-server via Pylon correctly converts urls of RM/NM.

---

pai-management/paiLibrary/paiBuild/build_center.py

Move 'tag()' into the 'build()', now the base_image could be tagged. Fixes #747 .
@ydye please take a look.

move "tag" operator to build(), so base_image could be tagged.

---

pylon/src/nginx.conf.template

Refine 1: Change the urls of yarn web pages from `/yarn/<ip>/<port>/...` to `/yarn/<ip>:<port>/...`, more consistent with the format of native yarn web page urls.
Refine 2: Support job history server (port 8188), thus the logs of finished jobs can now be viewed via pylon.
Fix bug: PAI REST API returns incorrect yarn url.

[Pylon] Refine and fix bugs

---

cluster-configuration/services-configuration.yaml
pai-management/doc/how-to-write-pai-configuration.md
pai-management/quick-start/services-configuration.yaml.template

The "custom-hadoop-binary-path" should include a 'filename', but not directory.
Fixes #780 .
@ydye please take a look.

[hotfix] Add description and fix default for "custom-hadoop-binary-path"

---

pai-management/doc/add-service.md
pai-management/doc/cluster-bootup.md
pai-management/doc/how-to-setup-dev-box.md
pai-management/doc/how-to-write-pai-configuration.md
pai-management/doc/machine-maintenance.md
pai-management/doc/paictl.md
pai-management/doc/service-maintain.md

Fix the spelling mistakes of pai-management/doc and add python instruction in front of paictl.py.

Fix the spelling mistakes of pai-management/doc and add python instruction in front of paictl.py

---

README.md

Doc the prerequisite in our readme.
Docker api version >= 1.26, or --cpus option could not found, job fails to start.

 update Prerequisite: docker api version >= 1.26

---

pai-management/paiLibrary/paiCluster/cluster_util.py

`/etc/resolv.conf` may have multiple lines contains `nameserver`, select first line as dns in generated configure file.

fix quick start bug

---

.gitignore
.travis.yml
utilities/doc_checker.py

fix #808 
Current working in progress. Already detected broken links:
```
link mailto:opencode@microsoft.com in file /home/dixu/dev/pai/README.md doesn't exist
link ../service-deployment/README.md in file /home/dixu/dev/pai/webportal/README.md doesn't exist
link ../service-deployment/clusterconfig-example.yaml in file /home/dixu/dev/pai/webportal/README.md doesn't exist
link ../service-deployment/README.md in file /home/dixu/dev/pai/pylon/README.md doesn't exist
link ../service-deployment/clusterconfig-example.yaml in file /home/dixu/dev/pai/pylon/README.md doesn't exist
link ../../job-tutorial/Dockerfiles/cuda8.0-cudnn6/Dockerfile.run.cntk in file /home/dixu/dev/pai/examples/keras/README.md doesn't exist
link ./bootstrap/hadoop-service/hadoop-configuration/ in file …
```

add tools for detective broken links in documents

---

pai-management/k8sPaiLibrary/maintainconf/add.yaml
pai-management/k8sPaiLibrary/maintainlib/add.py
pai-management/k8sPaiLibrary/maintainlib/common.py
pai-management/k8sPaiLibrary/maintainlib/etcdfix.py
pai-management/paictl.py

Add machine from node-list.
The nodelist.yaml format
```
#
#
#
machine-list:
- hostname: host1 # echo `hostname`
hostip: 192.168.1.11
machine-type: D8SV3
etcdid: etcdid1
sshport: PORT
username: username
password: password
k8s-role: master
dashboard: "true"
zkid: "1"
pai-master: "true"
- hostname: host2
hostip: 192.168.1.12
machine-type: NC24R
sshport: PORT
username: username
password: password
k8s-role: worker
pai-worker: "true"
```
The command:
```
./paictl.py machine add -p /conf/path -l nodelist.yaml
```
The supported node type：
```
master and worker
```

Add machine add option in paictl

---

pai-management/k8sPaiLibrary/maintainlib/common.py

In ubuntu environment which uses Chinese language, ```python paictl.py cluster k8s-bootup -p /path/to/cluster-configuration/dir``` will cause the encoding error as the picture shown below. 
So I remove the unnecessary output code.
Or maybe it could be resolved by using utf-8 encoding, but i think it's not a universal solution.

Add utf-8 encoding for stdout in pai-management/k8sPaiLibrary/maintainlib/common.py

---

hadoop-ai/hadoop-build/build.sh

Move Nodemanager GPU information and Port information to a single thread. 
Please check:  to get the source code.
https://github.com/qinchen123/hadoop/tree/new_branch-2.7.2

update hadoop version  [fix nvidia-smi and netstat hang issue]

---

pai-management/doc/cluster-bootup.md

Fix the doc of `cluster-bootup`, there is a little command typo for run `k8s-bootup`, which should have a `python` prefix.

Doc fixing, add missing `python`

---

prometheus/exporter/docker_stats.py
prometheus/test/test_docker_stats.py

`tb` and `tib` is different, means 10^12 and 2^40 respectively.

fix error in parsing docker stats

---

prometheus/exporter/gpu_exporter.py
prometheus/exporter/job_exporter.py
prometheus/test/test_job_exporter.py

We observe in some cases, nvidia-smi call will hang indefinitely, this will block job metrics generation.
So we use thread to call nvidia-smi and if there is already one thread doing that, ignore gpu metrics.

avoid hanging nvidia-smi block job metrics generation

---

pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template

Enable them if we find they are useful.

disable most metrics exposed by node exporter by default

---

cluster-configuration/services-configuration.yaml
pai-management/doc/how-to-write-pai-configuration.md
pai-management/quick-start/services-configuration.yaml.template

Lock the docker images tags used for release 0.6 to 'pai-0.6.y'.
@fanyangCS @hwuu please take a look.

Lock the image tag for release 0.6.

---

rest-server/src/controllers/job.js
rest-server/src/middlewares/job.js
rest-server/src/models/job.js
rest-server/src/models/user.js
rest-server/src/models/vc.js
rest-server/src/util/error.d.ts
rest-server/test/jobDeletion.js
rest-server/test/jobExecutionType.js
rest-server/test/jobSubmission.js

Refine job errors

---

pai-management/k8sPaiLibrary/maintainlib/common.py
pai-management/paiLibrary/common/file_handler.py
pai-management/paiLibrary/imageTool/host-configure.py

if template file contains Chinese, it will raise error as follow:
```bash
Traceback (most recent call last):
File "./paictl.py", line 449, in <module>
main()
File "./paictl.py", line 426, in main
pai_build()
File "./paictl.py", line 278, in pai_build
center.run()
File "/home/pai/paiflow/deploy-pai/pai/pai-management/paiLibrary/paiBuild/build_center.py", line 169, in run
self.build(image_name)
File "/home/pai/paiflow/deploy-pai/pai/pai-management/paiLibrary/paiBuild/build_center.py", line 121, in build
image_build_worker.run()
File "/home/pai/paiflow/deploy-pai/pai/pai-management/paiLibrary/paiBuild/image_build.py", line 149, in run
self.prepare_template()
File "/home/pai/paiflow/deploy-pai/pai/pai-management/paiLibrary/paiBuild/image_build.py", line 78, in prepare_template
generated_data …
```

fix jinja2 unicodedecodeerror

---

prometheus/exporter/gpu_exporter.py
prometheus/test/data/nvidia_smi_outdated_gpu.xml
prometheus/test/test_gpu_exporter.py

do not emit invalid gpu metrics if gpu not supported by nvidia-smi

---

pai-management/bootstrap/grafana/grafana-configuration/pai-clusterview-dashboard.json.template
pai-management/bootstrap/grafana/grafana-configuration/pai-nodeview-dashboard.json.template
pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template

node_exporter upgrade introduced many metrics name change, change grafana metrics to address no data point in font page.

change metrics name due to node_exporter upgrade

---

pai-management/bootstrap/prometheus/alert-deployment.yaml.template
pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template
pai-management/bootstrap/prometheus/service.yaml
pai-management/bootstrap/prometheus/start.sh.template
pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py

fix #1007
quick start script will not generate alerting in configuration. Modified code to accommodate  this: will not deploy alert manager if no alerting config present.
With this fix, both enabled/disabled alert manager can works.

fix can not start prometheus with quick start

---

webportal/src/app/cluster-view/hardware/hardware.component.js

previous I upgrade node_exporter to 0.16.0, this release introduced many metrics renaming. I already renamed metrics in grafana in #987 .

rename metrics in webportal

---

pai-management/bootstrap/grafana/grafana.yaml.template
pai-management/bootstrap/prometheus/service.yaml
pai-management/bootstrap/prometheus/start.sh.template
pai-management/bootstrap/prometheus/stop.sh.template
pai-management/bootstrap/prometheus/watchdog-configmap.yaml.template
pai-management/bootstrap/prometheus/watchdog-ds.yaml.template
pai-management/src/watchdog/dockerfile
pai-management/src/watchdog/image.yaml
prometheus/doc/watchdog-metrics.md
prometheus/exporter/utils.py
prometheus/exporter/watchdog.py
prometheus/prometheus-alert/k8s.rules
prometheus/prometheus-alert/node.rules
prometheus/prometheus-alert/pai-services.rules
prometheus/test/data/no_condtion_pod.json
prometheus/test/data/pods_list.json
prometheus/test/test_watchdog.py

fix #350 , also fix #972 
refactored previous service metric:
from `pod_current_probe_not_ready 1` to `pai_pod_count{ready="false", name="node_exporter"} 1`
for pai service pod, it will emit metric like:
```
pai_pod_count{host_ip="10.151.40.4",initialized="true",instance="10.151.40.4",job="node_exporter",name="zookeeper",phase="running",podscheduled="true",ready="true"}
```
pai_pod_count relays on all pai service labeled as `app: $service_name`, I found grafana not satisfy this, so I changed grafana's label.
for node, it will emit metric like:
```
pai_node_count{disk_pressure="false",instance="10.151.40.4",job="node_exporter",memory_pressure="false",name="10.151.40.4",out_of_disk="false",ready="true"}
```
this refactoring will make alert rule much simpler.
Also added some rule we …

Add service healthcheck

---

webportal/src/app/job/job-view/job-view.component.js

Order by:
- `UNKNOWN`
- `WAITING`
- `RUNNING`
- `STOPPING`
- `STOPPED`
- `SUCCEEDED`
- `FAILED`

Web portal: refine status sort order, closes #876

---

Jenkinsfile

Catch error, force to run the cleanup.
It won't skip the 'clean up' stages whatever user inputted.

[Jenkins] Catch error, force to run cleanup

---

pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template

For pods want to be scraped by prometheus should annotated with:
* prometheus.io/scrape
* prometheus.io/path
* prometheus.io/port
for example:
* prometheus.io/scrape: true
* prometheus.io/path: /metrics
* prometheus.io/port: 1234
with this annotation prometheus will scrape from `http://${pod_host_ip}:1234/metrics` to scrape metrics.

allow prometheus auto scrape from pod

---

docs/faq.md

faq for: To improve the cluster usage, customers would like to see a VC can use up all cluster resource if others don’t use it. While to ensure one user cannot occupy excessive resource our customers would like to set a quota constraint for individual users.

[faq] faq vc and user resource allocation quota

---

pai-management/k8sPaiLibrary/template/kubelet.sh.template

We start kubelet with hypekube image, if we want to use nfs PersistentVolume, kubelet will first mount nfs in dir `/var/lib/kubelet` and then instruct docker mount that dir into container.
If we start hypekube with `rw`, this will prevent [mount point propagation](https://lwn.net/Articles/690679/). In other words, mount happend in hypekube will not visible to out side world and hence this setting can not support PersistentVolume.
To allow mount point propagation, just change `rw` option to `shared`. Already tested in INT bed.

support PersistentVolume

---

pai-management/src/end-to-end-test/start.sh

If `$token_file` is empty, retry run `get_auth_token`.

retry get_auth_token if token_file empty

---

prometheus/exporter/gpu_exporter.py
prometheus/exporter/healthy_check.py

Bugfix for #1095 
Run command `which nvidia-smi` to check exists of `nvidia-smi`, preventing the health-check error.

bugfix: check nvidia-smi exists before run `nvidia-smi -q -x`

---

pai-management/bootstrap/grafana/minify.py

fixed #1147
with following observation:
* previous method of creating grafana configmap puts all files under grafana-configuration directory, including template files. This doubles configMap size.
* json files can be easily compressed using minify tools.
This PR reduced configMap size from 277920 byte to 61082.

minify grafana config and exclude template files to avoid too large configmap

---

cluster-configuration/cluster-configuration.yaml
pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py
pai-management/quick-start/cluster-configuration.yaml.template

fixed #1120 
Watchdog requires node with label watchdog:true to be deployed. Previously, we requires this label written in config and quick start will not generate this. After we upgrade into k8s 1.9.9 deployment select no node will marked as failed, so #1120 failed.
This PR move watchdog:true label into cluster object model like other service, instead of requires user label node manually.

label watchdog:true in cluster-object-model

---

pai-management/k8sPaiLibrary/template/kubelet.sh.template

Fix pod keeps retrying `pull image`

---

pai-management/k8sPaiLibrary/maintainlib/common.py
pai-management/k8sPaiLibrary/maintainlib/deploy.py

check api resources before install proxy

---

Jenkinsfile

Reviewing after CI passed is OK.

Jenkins CI: support multiple slashes in branch name

---

Jenkinsfile

Jenkins used to wait for webportal to be ready, but when it's ready, rest-server may fail.
Now we wait for rest-server to be ready.

waiting for rest-server to be ready

---

pai-management/bootstrap/alert-manager/alert-configmap.yaml.template
pai-management/bootstrap/alert-manager/alert-manager.yaml.template
pai-management/bootstrap/alert-manager/start.sh.template
pai-management/bootstrap/alert-manager/stop.sh
pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template
pai-management/bootstrap/prometheus/prometheus-deployment.yaml.template
pai-management/bootstrap/prometheus/start.sh
pai-management/bootstrap/prometheus/stop.sh
pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py
pai-management/paiLibrary/paiService/service_management_start.py
pai-management/paiLibrary/paiService/service_template_generate.py
prometheus/alert-templates/pai.tmpl
prometheus/doc/alert-manager.md
prometheus/prometheus-alert/k8s.rules
prometheus/prometheus-alert/node.rules
prometheus/prometheus-alert/pai-services.rules

Change alert email template.
The default email template contains many info not useful even obscure to end users, for example, `instance` label is generated by prometheus master which represent where this metrics scraped from, not problematic service's IP.
This PR changed email template for OpenPAI, only display alert's summary if applicable, and fallback to original version if summary not exist.
I copied default template, and only changed logic with [this](https://github.com/Microsoft/pai/pull/1282/files#diff-c0a60ee34697d1a458ef7fd020e41020R70) if branch.

change email template

---

pylon/src/nginx.conf.template

Fix #1314 
Closes #1319 
Since #1183 fix is not in the release branch, rename branch to make CI pass.

Pylon: Fix rewrite of WebHDFS redirection

---

rest-server/src/middlewares/job.js

Fix #1314 
Closes #1321 
Since #1183 is not in the release branch, rename branch to make CI pass.

Fix backward compatibility of killAllOnCompletedTaskNumber

---

src/rest-server/src/util/error.js

As [unirest](https://github.com/Kong/unirest-nodejs) document says:
> - raw_body (Mixed) - Unprocessed body data
but it still processed body data, from string to object, which is unacceptable in [http-errors](https://github.com/jshttp/http-errors)
This PR will convert transferred raw_body back to JSON if no message field in it.

REST Server: Refine error message transfering from upstream.

---

src/webportal/src/app/job/job-view/job-detail-table.component.ejs
src/webportal/src/app/job/job-view/job-view.component.js
src/yarn-frameworklauncher/deploy/stop.sh

if job retry count > 0 we can click retry number in job detail page then jump to Yarn portal which will show job history automatically.

[Rest-server] Add job retry history

---

src/webportal/config/webpack.common.js

Webportal: fix version display in PAIShare pages

---

deployment/k8sPaiLibrary/template/apiserver.yaml.template
src/drivers/deploy/drivers.yaml.template
src/end-to-end-test/deploy/end-to-end-test.yaml.template
src/grafana/deploy/grafana.yaml.template
src/hadoop-batch-job/deploy/one-time-job-hadoop.yaml.template
src/hadoop-data-node/deploy/delete.yaml.template
src/hadoop-data-node/deploy/hadoop-data-node.yaml.template
src/hadoop-jobhistory/deploy/delete.yaml.template
src/hadoop-jobhistory/deploy/hadoop-jobhistory.yaml.template
src/hadoop-name-node/deploy/delete.yaml.template
src/hadoop-name-node/deploy/hadoop-name-node.yaml.template
src/hadoop-node-manager/deploy/delete.yaml.template
src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template
src/hadoop-resource-manager/deploy/delete.yaml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
src/job-exporter/build/job-exporter.dockerfile
src/job-exporter/src/docker_inspect.py
src/job-exporter/src/job_exporter.py
src/job-exporter/src/network.py
src/job-exporter/src/utils.py
src/job-exporter/test/test_docker_inspect.py
src/node-exporter/deploy/node-exporter.yaml.template
src/prometheus/deploy/delete.yaml.template
src/rest-server/deploy/rest-server.yaml.template
src/rest-server/src/templates/yarnContainerScript.mustache
src/yarn-frameworklauncher/deploy/delete.yaml.template
src/yarn-frameworklauncher/deploy/yarn-frameworklauncher.yaml.template
src/zookeeper/deploy/delete.yaml.template
src/zookeeper/deploy/zookeeper.yaml.template

almost same with #764 
This functionality requires job-exporter container to be privileged and has host pid namespace. Since this will have security issue, I enabled admission control in api server with recommended policy and `DenyEscalatingExec`. @ydye please verify this.
It also requires other service to have non-host pid namespace to be accurate.

collect network metrics for containers

---

src/rest-server/src/templates/yarnContainerScript.mustache

hanging container, keep alive after `exit_handle`
only script process and 2 zombie processes. `/bin/bash` doesn't reap them correctly.
`--init` will overwrite `entrypoint` with `/dev/init`, thus the pid 1 process looks like `/dev/init -- /bin/bash dockerboostrap.sh`. `init` process have a right behavior in reaping zombie processes.

add init option in docker run, help reaping zombie processes

---

deployment/k8sPaiLibrary/template/apiserver.yaml.template
deployment/k8sPaiLibrary/template/controller-manager.yaml.template
deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template
deployment/k8sPaiLibrary/template/etcd.yaml.template
deployment/k8sPaiLibrary/template/kubelet.sh.template
deployment/k8sPaiLibrary/template/scheduler.yaml.template
src/drivers/deploy/drivers.yaml.template
src/grafana/deploy/grafana.yaml.template
src/hadoop-batch-job/deploy/hadoop-configuration/yarn-env.sh
src/hadoop-data-node/deploy/hadoop-data-node-configuration/yarn-env.sh
src/hadoop-data-node/deploy/hadoop-data-node.yaml.template
src/hadoop-jobhistory/deploy/hadoop-jobhistory.yaml.template
src/hadoop-name-node/deploy/hadoop-name-node.yaml.template
src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/nodemanager-generate-script.sh
src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-env.sh
src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-env.sh
src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
src/node-exporter/deploy/node-exporter.yaml.template
src/prometheus/deploy/prometheus-deployment.yaml.template
src/pylon/deploy/pylon.yaml.template
src/rest-server/deploy/rest-server.yaml.template
src/rest-server/src/templates/yarnContainerScript.mustache
src/watchdog/deploy/watchdog.yaml.template
src/webportal/deploy/webportal.yaml.template
src/yarn-frameworklauncher/deploy/yarn-frameworklauncher.yaml.template
src/zookeeper/build/run.sh
src/zookeeper/build/zookeeper.dockerfile
src/zookeeper/deploy/zookeeper.yaml.template
subprojects/frameworklauncher/yarn/bin/start.sh

Add memory limit for all PAI services. Fixes #506 .

Add memory limit for all PAI services, make it 'Burstable' Qos class

---

src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template

In case that if the RM hasn't ready the yarn-exporter container will exit, add liveness probe for yarn-exporter container will fix it.

Add liveness probe for yarn-exporter container

---

deployment/k8sPaiLibrary/template/kubelet.sh.template

```
--healthz-bind-address 0.0.0.0
The IP address for the healthz server to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 127.0.0.1)
--healthz-port int32
The port of the localhost healthz endpoint (set to 0 to disable) (default 10248)
```
REF Link: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

Enable kubelet healtz port and address.

---

src/rest-server/src/templates/dockerContainerScript.mustache
src/rest-server/src/templates/yarnContainerScript.mustache

Make our monitor process as docker main process, to avoid user command trick
A know issue:
For killing job sceanario, yarn script will exit before docker script, so the yarn log aggregation may collect incomplete `dockerContainerDebug.log`

Move user code background

---

deployment/paiLibrary/paiService/service_management_refresh.py
deployment/paiLibrary/paiService/service_refresh.py

In the past, execute kubectl label node regardless of whether the node has the label, it will output confused log, refine it by check the existence of the label first, if already has label, do nothing.
Now refresh each service all need to scan the whole machinelist once, if refresh all services and the cluster is big it will take longtime, should change the scan step to global way.

refine refresh

---

deployment/k8sPaiLibrary/maintaintool/docker-ce-install.sh
deployment/k8sPaiLibrary/template/docker-daemon.json.template
deployment/k8sPaiLibrary/template/kubelet.sh.template
deployment/paiLibrary/clusterObjectModel/paiObjectModel.py
deployment/quick-start/services-configuration.yaml.template
examples/cluster-configuration/services-configuration.yaml
paictl.py
src/drivers/build/clean.sh
src/drivers/build/docker-config-with-nvidia-runtime.json
src/drivers/build/drivers.dockerfile
src/drivers/build/install-all-drivers
src/drivers/build/install-nvidia-drivers
src/drivers/deploy/clean.yaml.template
src/drivers/deploy/delete.sh.template
src/drivers/deploy/drivers.yaml.template

Changed other bootup script to install nvidia-container-runtime and config kubelet with DevicePlugins=true.
With this PR, pai-lite user can use normal way to bootup a k8s cluster, and config `drivers.set-nvidia-runtime = true` and start `drivers` to be able to use gpu as resource.
An document still needed to describe how to setup correctly:
* bootup cluster as in pai
* config `drivers.set-nvidia-runtime = true`
* start drivers service
* start nvidia k8s-device-plugin manually

add nvidia gpu support for pai-lite

---

src/cleaner/deploy/service.yaml
src/cleaner/scripts/clean_docker_cache.py
src/cleaner/worker.py

during deployment, in rare case if cleaner is started and begin to clean docker cache. Some newly pulled image ready to deploy will be deleted, this can cause problems. So make cleaner the last service to start and add delay before its first cleaning.

Clean dependencies

---

src/job-exporter/src/job_exporter.py
src/job-exporter/test/test_job_exporter.py
src/prometheus/deploy/alerting/jobs.rules
src/rest-server/src/templates/dockerContainerScript.mustache

Monitor two types of zombie container:
1. container with log displaying `USER COMMAND END` but still exist for a long period.
2. those containers whose yarn container not exist but job container still exist.
We only send out alert email when the count above 0 for 1 hour, because we just want to find out the root cause of zombie container.

expose zombie count and add alert

---

src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template

`docker system prune` has some unexpected behavior, this is a workaround before cleaner find a better docker cache cleaner methods

mount docker credentials to NM

---

src/prometheus/deploy/prometheus-deployment.yaml.template

Increase prometheus memory limits to 10, keep data for one week.

[hotfix]increase prometheus memory limits (data keep 1 week)

---

src/webportal/src/app/job/job-view/job-view.component.js

Closes #1586
As `configInfo` is already a string, there is no need to stringify it again.

Web portal: Fix export job

---

src/rest-server/src/config/job.js
src/rest-server/src/models/job.js
src/rest-server/src/templates/yarnContainerScript.mustache
src/rest-server/test/setup.js
src/webportal/src/app/job/job-submit/job-submit.schema.js

add job Envs

---

src/pylon/src/nginx.conf.template

Fixes #1597
Ref: <http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size>

Pylon: Disable the checking of request body size.

---

deployment/k8sPaiLibrary/template/apiserver.yaml.template
deployment/k8sPaiLibrary/template/controller-manager.yaml.template
deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template
deployment/k8sPaiLibrary/template/etcd.yaml.template
deployment/k8sPaiLibrary/template/kubelet.sh.template
deployment/k8sPaiLibrary/template/scheduler.yaml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
src/zookeeper/deploy/zookeeper.yaml.template

Remove memory limits for k8s services.
Increase memory limits of rm to 36G, max heap size 32G.
Increase memory limits of zookeeper to 10G, max heap size 8G.

[hotfix] remove memory limits for k8s services and increase it for rm, zookeeper

---

src/job-exporter/src/job_exporter.py

relevant to #1603 , I suspect the issue is due to job-exporter spent too much time in one iteration thus failed to update file in 120 seconds.

add job_exporter_iteration_seconds to expose iteration time of job-exporter

---

src/watchdog/src/watchdog.py
src/watchdog/test/test_watchdog.py

fix watchdog None exception error

---

docs/drivers/drivers.md

Before the upgrading process, all service, which may occupy gpu resource, should be stopped.

[Drivers] How to upgrade the drivers version in OpenPAI cluster

---

src/cluster-configuration/deploy/gpu-configuration/gpu-configuration.json.template
src/job-exporter/build/job-exporter.dockerfile
src/job-exporter/src/gpu_exporter.py
src/job-exporter/src/job_exporter.py
src/job-exporter/src/utils.py
src/job-exporter/test/test_gpu_exporter.py
src/job-exporter/test/test_utils.py
src/node-exporter/deploy/node-exporter.yaml.template

The first step to remove using nvidia-smi to generate gpu count: use configuration as ground truth and expose in job-exporter. Will remove expose of `nvidiasmi_attached_gpus` in another PR.

calculate configured gpu in job-exporter

---

src/webportal/src/app/job/job-view/job-view.component.js

Cherry-picked from #1592 
Closes #1586
As `configInfo` is already a string, there is no need to stringify it again.

Web portal: Fix export job (#1592)

---

docs/pai-management/doc/machine-maintenance.md

Because the behavior of master branch is different from the pai-0.8.y. So I directly add this add-on into the release branch.

[Fix] Update document, add the content about add new node.

---

src/drivers/build/install-all-drivers
src/drivers/build/install-nvidia-drivers

because we set `$PRE_INSTALLED_NV_DRIVER_PATH` as volume, k8s will always have it as directory, so, previous will always think `$PRE_INSTALLED_NV_DRIVER_PATH` is installed, and modify `/var/drivers/nvidia/current` to it.

fix drivers bug

---

src/rest-server/deploy/rest-server.yaml.template
src/rest-server/src/templates/yarnContainerScript.mustache

it seems rest-server will not pass environment variable into yarn-script. just hardcode in yarn-script since it is hardcoded anyway.

fix driver bug

---

src/drivers/config/drivers.md
src/drivers/config/drivers.yaml
src/drivers/deploy/drivers.yaml.template

make preinstalled driver path configurable

---

deployment/clusterObjectModel/mainParser/machine.py
src/cluster-configuration/deploy/gpu-configuration/gpu-configuration.json.template

previous com has machinetype, but new com has machine-type, will cause job-exporter unable to find gpu count

fix cluster object model inconsistence

---

src/rest-server/src/templates/yarnContainerScript.mustache

1. Move all host folders under yarn monitor
2. Simplify yarn exit log, origin log is  too repetitive.

[Yarn script]Move host dir under yarn monitor, simplify yarn script exit log

---

deployment/paiLibrary/paiService/service_management_refresh.py
src/job-exporter/deploy/refresh.sh
src/node-exporter/deploy/refresh.sh
src/prometheus/deploy/refresh.sh
src/watchdog/deploy/refresh.sh

fix #1748 , I also fixed a bug when calling `paictl.py service refresh`. Not sure if this is correct. @ydye please have a check.

add refresh for {node,job}-exporter, prometheus and watchdog

---

src/node-exporter/deploy/node-exporter.yaml.template
src/prometheus/deploy/alerting/node.rules

fix #1766 , mount host-root as volume in node-exporter, so that node-exporter can report usage info about all disk mounted in host. Also changed alerting rule to remove duplicated entry in filesystem usage, this will also alert other disks previous ignored by node-exporter.

mount host path root into node-exporter

---

src/pylon/src/nginx.conf.template

(hotfix) Pylon: replace WehHDFS URLs in REST server responses

---

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml

Related configuraion
```
amGangAllocationTimeoutSec: 1100
yarn.resourcemanager.rm.container-allocation.expiry-interval-ms=1200000
```
AM might start container after `$amGangAllocationTimeoutSec` secs, but yarn ask the container should be launched whin `$yarn.resourcemanager.rm.container-allocation.expiry-interval-ms`. If clusters are out of sync, the token might be invalid

extend yarn container token expiry

---

deployment/k8sPaiLibrary/template/kubelet.sh.template

if not enable this feature gate, toleration for disk/memory pressure will not take effect. See [this](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions)

add TaintBasedEvictions

---

src/hadoop-run/build/hadoop-run.dockerfile

dockerfile doesn't allow assign and fetch an environment in a single ENV command

Fix YARN_CONF_DIR error

---

src/hadoop-node-manager/deploy/hadoop-node-manager-delete/delete.sh

Docker daemon might hang by some zombie container, so we abort deletion if timeout

Best-effort delete NM container

---

docs/webportal/README.md

add a paragraph to describe virtual cluster

update virtual cluster doc

---

src/job-exporter/deploy/job-exporter.yaml.template
src/job-exporter/src/collector.py

`k8s_job-exporter_job-exporter-l4ptn_default_d804d9e9-1d74-11e9-b630-000d3ab7e6d6_0 126.6MiB / 128MiB`.
increase memory limit for job-exporter and fix some code error.

increase job-exporter memory limit

---

src/prometheus/deploy/alerting/node.rules

Current alert:
```
FileSystem /dev/sda1 usage in 10.151.40.236:9100 is above 80% (current value is: 0.16608200616194327)
```
current value is confusing.

fix wording in alert email

---

src/webportal/src/app/plugin/plugin.component.js

Will hotfix to pai-0.9.y
jQuery version could not provide the document.currentScript property, which make the plugin cannot get the plugin configuration.

Webportal plugin: Use native loadScript instead of jQuery.getScript

---

paictl.py
src/base-image/build/base-image.dockerfile
src/dev-box/build/dev-box.dockerfile
src/hadoop-ai/build/hadoop-ai

```
xxx@xxxxxxxxxxxxxxx:~/pai$ sudo apt-cache madison openjdk-8-jre
openjdk-8-jre | 8u191-b12-0ubuntu0.16.04.1 | http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
openjdk-8-jre | 8u191-b12-0ubuntu0.16.04.1 | http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
openjdk-8-jre | 8u77-b03-3ubuntu3 | http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
openjdk-8 | 8u77-b03-3ubuntu3 | http://azure.archive.ubuntu.com/ubuntu xenial/main Sources
openjdk-8 | 8u191-b12-0ubuntu0.16.04.1 | http://azure.archive.ubuntu.com/ubuntu xenial-updates/main Sources
openjdk-8 | 8u191-b12-0ubuntu0.16.04.1 | http://security.ubuntu.com/ubuntu xenial-security/main Sources
xxx@xxxxxxxxxxxxxxx:~/pai$ sudo apt-cache madison openjdk-8-jdk
openjdk-8-jdk | …
```

[Issue Fix] Fix OpenJDK version to 8u191-b12-0ubuntu0.16.04.1

---

src/rest-server/src/templates/yarnContainerScript.mustache

User will have built the intel mpi into the job image by themselves.

[Azure RDMA] Remove "/opt/intel" from the rdma mount environment.

---

.travis.yml
src/job-exporter/deploy/job-exporter.yaml.template
src/job-exporter/src/main.py
src/watchdog/build/watchdog.dockerfile
src/watchdog/deploy/watchdog.yaml.template
src/watchdog/src/watchdog.py

fix #2104 by disable GCCollector. Use twisted as http server. Also add signal handler for dumping stack trace to facilitate future debug for hanging.

fix deadlock in job-exporter by disabling GCCollector

---

.travis.yml
src/job-exporter/build/job-exporter.dockerfile
src/job-exporter/deploy/job-exporter.yaml.template
src/job-exporter/src/main.py
src/watchdog/build/watchdog.dockerfile
src/watchdog/deploy/watchdog.yaml.template
src/watchdog/src/watchdog.py

fix #2104 by disable GCCollector. Use twisted as http server. Also add signal handler for dumping stack trace to facilitate future debug for hanging.

fix job-exporter deadlock by disabling GCCollector of prometheus client

---

build/core/build_center.py
deployment/k8sPaiLibrary/maintaintool/restart-etcd-server.sh
paictl.py
src/base-image/build/base-image.dockerfile
src/dev-box/build/dev-box.dockerfile
src/hadoop-ai/build/hadoop-ai

Find the old version in apt is overwrited. And build image failed with the error message following. 
```
Get:15 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8532 B]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [534 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [6119 B]
Fetched 15.6 MB in 1s (10.3 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '8u191-b12-0ubuntu0.16.04.1' for 'openjdk-8-jre' was not found
E: Version '8u191-b12-0ubuntu0.16.04.1' for 'openjdk-8-jdk' was not found
The command '/bin/sh -c apt-get -y …
```

[JDK] Remove JDK version hardcode and add print in pai_build for debuging

---

deployment/k8sPaiLibrary/template/kubelet.sh.template

1: Disable pod eviction behavior
2: Set the image gc threshold to 100%. And when image gc is triggered, kubelet will continue do image gc until the file system's space is below 95%.

[Pod Eviction] Disable kubernetes's hard enicvtion

---

build/core/build_center.py
build/core/build_utility.py

Add error message when image build failed to help debug.
[Here](http://40.76.53.138:33080/blue/organizations/jenkins/pai/detail/PR-2086/7/pipeline/#step-47-log-1466) is an example. This fixes #2125.

[CI/CD] Add error message when image build failed

---

subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/AggregatedFrameworkStatus.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/webserver/StatusManager.java

**Solve Issues:**
#2022 
#2051 
#2099 
**New Definition:**
Framework is running <-> Exists running Task
This makes the Launcher APIs reflect the real Framework running state, instead of just the raw AM running state. (Since We always want to best effort hide AM concept to end user).
The definition works for both Incremental and Gang Scheduling, because even for Gang Scheduling, “Exists running Task” means the Framework has already satisfied Gang Allocation, and all its Tasks has already been launched before.
**Why not implement in RestServer?**
To revise state, RestServer List operation need to also read all TaskStatuses, which is too heavy.
**Why implement in LauncherWebServer instead of LauncherService?**
It is hard to make sure the FrameworkStatus is consistent with the TaskStatuses …

[Launcher]: Revise the definition of Framework running state

---

src/pylon/src/nginx.conf.template

Fixed #1674
- [Python HDFS client](https://github.com/jingw/pyhdfs/blob/fab8bcf4966f894a7114665875b258536534749d/pyhdfs.py#L51)  and [HdfsCLI](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L62) hard-coded the webhdfs prefix (/webhdfs/v1) and do not provide documented way to change them, we make (/webhdfs **/webhdfs/v1** ) alias of (/webhdfs **/api/v1** ) for easier use.
- Python HDFS client have an [assertion](https://github.com/jingw/pyhdfs/blob/fab8bcf4966f894a7114665875b258536534749d/pyhdfs.py#L424) of empty response body in 307 response, but nginx automatically adds a simple html in 307 response, we cleared it to be compatible to the library.

[Pylon] WebHDFS library compatibility

---

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml.template

This is the tolerable NM downtime.
origin 15 mins might not afford an upgrade.

extend nm expiry period

---

src/prometheus/deploy/alerting/pai-services.rules

this was fixed in pai-0.9 along with job-exporter fix. But since job-exporter fix is a temporary fix, so I only add this fix to master, and fix job-exporter in master when we find out the root cause.

make it more clear in service not up

---

src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template

make the front page consistently use yarn's gpu view.
Will add a page about all sort of gpu count in future.

use yarn's metrics in cluster view

---

src/webportal/package.json
src/webportal/src/app/job/job-submit/job-submit.component.ejs
src/webportal/src/app/job/job-submit/job-submit.component.js
src/webportal/yarn.lock

Allowing user to import json with comment (JSONC) on job submission page.
Addressing #1986.

webportal: allow jsonc in job submission

---

docs/rest-server/API.md
src/rest-server/src/config/vc.js
src/rest-server/src/controllers/vc.js
src/rest-server/src/models/vc.js
src/rest-server/test/vc.js

For backward compatibility, if no `maxCapacity` provided, bonus token will be disabled
TODO:
webportal:
1. expose `vcMaxCapacity` box when add or edit VC.
2. show `maxCapacity` info in VC page.

Support configure vc bonus 

---

src/rest-server/src/controllers/vc.js
src/rest-server/test/vc.js

#2169 
YARN actually supports more kinds of characters such as space, but PAI doesn't.
This pr is to keep consistent with other PAI API.

Restrict vcname character in VC related API

---

docs/job_tutorial.md
src/rest-server/src/templates/yarnContainerScript.mustache

Unify PAI runtime environment variable names in docs and envfile.
Here's the exposed environment variable list:
- PAI_JOB_NAME
- PAI_JOB_VC_NAME
- PAI_USER_NAME
- PAI_DEFAULT_FS_URI
- PAI_TASK_ROLE_COUNT
- PAI_TASK_ROLE_LIST
- PAI_TASK_ROLE_TASK_COUNT\_`$taskrole`
- PAI_HOST_IP\_`$taskRole`\_`$taskIndex`
- PAI_PORT_LIST\_`$taskRole`\_`$taskIndex`\_`$portType`
- PAI_RESOURCE\_`$taskRole` 
- PAI_MIN_FAILED_TASK_COUNT\_`$taskRole`
- PAI_MIN_SUCCEEDED_TASK_COUNT\_`$taskRole`
- PAI_CURRENT_TASK_ROLE_NAME
- PAI_CURRENT_TASK_ROLE_CURRENT_TASK_INDEX

Unify PAI runtime environment variable names

---

src/job-exporter/src/collector.py
src/job-exporter/src/main.py

Current prometheus will failed to get task gpu metrics as shown below, this is due to GpuCollector(producer) and ContainerCollector(consumer) is in different thread, and consumer running in shorter interval, so consumer may failed to get data needed.
This PR make GpuCollector interval shorter to fix this problem. This should be a temporary fix, should change structure for long term fix.

fix missing gpu metrics

---

src/rest-server/src/models/job.js
src/rest-server/src/templates/dockerContainerScript.mustache

#2213 
#2214 
When user submit the job, set the following property in the  jobEnv of jobConfig. If the job's user command fails, the container will be kept for 1 weeks. And user could debug the container after ssh to it. After debugging, user should manually stop it to recycle the system resources.
```
"jobEnvs": {
"isDebug": true
}
```
```
[INFO] USER COMMAND START
job has finished with exit code 2
=============================================================================
======   The job container failed, so it will be reserved for 1 week   ======
======          After debugging, please stop the job manually.         ======
=============================================================================
```

[Job Debugging] If user command's exitcode is none zero, container will be reserved.

---

src/rest-server/src/templates/yarnContainerScript.mustache

Fixes Jenkins CI failed.
`docker_pid` was used for detect cgroup failed, which has been removed to make all OOM as user failed, 55.
Since Jenkins CI just runs `bash --version` as command, which usually be finished quickly, there is a bad case that the container exited before `docker attach` and will cause yarn failed.
This PR reverts this part.

Fix yarn container failed when docker container exited quickly.

---

docs/webportal/PLUGINS.md
src/webportal/config/webportal.md
src/webportal/config/webportal.py

Dependency of #2238
In `service-configuration.yaml`
Before:
```yaml
webportal:
plugins:
- title: Plugin Title
uri: //example.com/plugin.js?foo=bar
```
After:
```yaml
webportal:
plugins:
- title: Plugin Title
uri: //example.com/plugin.js
config:
foo: bar
```

Deploy: add explicit config field in webportal  plugin

---

src/pylon/docker-compose.yaml
src/pylon/src/nginx.conf.template

Pylon: fix double start query in yarn redirect

---

src/rest-server/test/jobExecutionType.js

[HotFix] REST server: remove expires in JWT payload of unit test

---

src/webportal/src/app/job/job-submit/job-submit.component.js

Dependency of #2238
Since the maximum length in address bar of browser will be (usually) 2000 chars, transfer the job JSON through url might be risky, so we choose sessionStorage
1. Save the initial job JSON string by `window.sessionStorage.setItem('job-init', job)`
2. Navigate to `/submit.html?op=init`
3. The saved job JSON string will be automatically loaded from sessionStorage, than cleared.

Web portal submit job: support init json from sessionStorage.

---

src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
src/yarn-exporter/build/yarn-exporter.dockerfile
src/yarn-exporter/src/requirements.txt
src/yarn-exporter/src/yarn_exporter.py

similar to #2093 , use twisted in yarn-exporter for better performance and disable gc collector to avoid deadlock

use twisted in yarn-exporter

---

src/job-exporter/src/collector.py
src/job-exporter/src/docker_stats.py
src/job-exporter/src/main.py
src/job-exporter/test/test_collector.py

Fix external process error.
If pid using gpu can not found container id, we deem it as external process, if it has container id, it is not. If its container id in zombie list, it is zombie using gpu

fix external process error

---

docs/pai-management/doc/how-to-setup-dev-box.md
src/dev-box/dev-box-k8s-deploy.yaml

Related issue: #2021 #2293 
docker daemon volume is a host path. We should map it to devbox, then our code could retrive it.

Fix hadoop-run build error

---

.travis.yml
src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template
src/yarn-exporter/src/yarn_exporter.py
src/yarn-exporter/test/base.py
src/yarn-exporter/test/data/empty_nodes
src/yarn-exporter/test/data/nodes
src/yarn-exporter/test/data/scheduler
src/yarn-exporter/test/test_collector.py

export following metrics:
* yarn_queue_cpu_available
* yarn_queue_cpu_total
* yarn_queue_mem_available
* yarn_queue_mem_total
* yarn_queue_gpu_available
* yarn_queue_gpu_total
* yarn_queue_running_job
* yarn_queue_pending_job
* yarn_queue_running_container
* yarn_queue_pending_container
* yarn_node_cpu_total
* yarn_node_cpu_available
* yarn_node_mem_total
* yarn_node_mem_available
* yarn_node_gpu_total
* yarn_node_gpu_available

export vc/node related metrics from yarn

---

src/prometheus/deploy/alerting/node.rules

increase threshold for CPU alert to 98%, as yarn currently do not reserve any CPU, so in heavy used cluster, yarn may allocate all CPU to tasks, and if tasks use CPU fully, it is easy for this alert to be triggered.
In a long term, we should reserve some CPU for system/service usage.

increase threshold for CPU alert

---

src/hadoop-jobhistory/deploy/hadoop-jobhistory-configuration/yarn-site.xml.template
src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/core-site.xml
src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml.template

Before this PR, other service could only get a html page with embeded log.
With this PR, other service could get plain-text job log and customize their own UI.
log api at
```
[running job] http://{worker_ip}:8042/ws/v1/node/containers/{container_id}/logs/stdout
[completed job] http://{master_ip}:8188/ws/v1/applicationhistory/containers/{container_id}/logs/stdout?redirected_from_node=true

enable hadoop web cross-origin and log web service

---

Jenkinsfile
deployment/quick-start/services-configuration.yaml.template

Here's the case:
1. When user install, the `latest` was v0.9.
2. Somehow one service, for example rest-server, restart. Kubernetes would try to using the `latest` image, which is v0.10.
So we should fix the quick-start template tag to the currently release.
In this case, it should be v0.10.1.

[HOT-FIX] Set the qucik-start template image tag to v0.10.1

---

src/rest-server/src/templates/yarnContainerScript.mustache

Support samba shares in container, add `DAC_READ_SEARCH` cap in `docker run`.
Closes #2227.

[Rest Server] Support samba shares in container

---

docs/tools/node_maintain.md
src/tools/node_maintain.py

A part of #2192
After #2209, unhealthy gpu info will be collected by prometheus. This PR provides following operation guide after alerting.
In our design, admin need to do:
1. Query prometheus, collect unhealthy nodes.
2. Add unhealthy nodes to blacklist.
3. Enforce service to reload the blacklist.
More details in https://github.com/Microsoft/pai/blob/8b186958f9ed55c4c0fac157977f58f9b56adc8c/docs/tools/node_maintain.md

Query unhealthy GPU from prometheus

---

src/pylon/src/nginx.conf.template
src/pylon/src/render.py

Fixes #468 
Closes #1567
To prevent issue of conf changes but upstream etag matches. Currently, only rest-server & web portal service expose etags. So only apply to routes of these services.
Moreover, proxy etag is set to md5 hash of conf file, and will be set to PAI version when @DongZhaoYu 's version proposal landed.

[Pylon]Append conf etag to upstream etag.

---

src/grafana/deploy/grafana-configuration/pai-jobview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskroleview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-tasks-in-node-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskview-dashboard.json.template
src/job-exporter/src/collector.py
src/job-exporter/src/docker_inspect.py
src/job-exporter/src/nvidia.py
src/job-exporter/test/test_collector.py
src/job-exporter/test/test_docker_inspect.py
src/job-exporter/test/test_nvidia.py

Tasks run by nvidia-container-runtime will have ENV of `NVIDIA_VISIBLE_DEVICES` and value is GPU uuids, these uuid can mapped into minor number by info get from nvidia-smi.
This PR will make job-exporter able to get resource usage of tasks run by either yarn-launcher and kube-launcher, including GPU usage.

map gpu in kube tasks

---

src/hadoop-ai/build/build-pre.sh
src/hadoop-ai/build/build.sh
src/hadoop-ai/build/hadoop-ai
src/hadoop-ai/build/hadoop-ai-fix.patch

Origin code only consider ecc code 0/1, but it's actually an int.
Readable patch is here:
https://github.com/mzmssg/hadoop/pull/3

Fix hadoop-ai ecc eccor detection

---

src/job-exporter/src/collector.py

We have detection of external gpu users, previous this is implemented as check /proc/$pid/cgroup content, if it not starts with /docker/, it will be treat as external process.
But tasks started by kube launcher will have content started with `/kubepods/`.
This PR will treat these tasks also as normal users.

prevent tasks scheduled by kube launcher be deemed as external user

---

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml.template
src/rest-server/src/models/job.js
src/rest-server/src/templates/yarnContainerScript.mustache

This PR includes:
1. Revert #1108, remove unnecessary logs.
2. Improve log readability. Killed job and finished job will have different logs. 
Killed job:
Finished job:
3. #2336 
We assume only docker errors raise 125 errorcode. This pr covert it to 205, which is launcher USER_APP_TRANSIENT_ERROR. Then launcher will retry it without burning retry count.

yarn container script exit handler fix and refactor

---

src/webportal/src/app/cluster-view/hardware/hardware-detail.component.js
src/webportal/src/app/job/job-submit/job-submit.component.js
src/webportal/src/app/marketplace/job-submit/job-submit.component.js
src/webportal/src/app/user/user-login/user-login.component.js

This optimization replaces all code in the webprotal that uses the url module with the querystring module and ensures consistent functionality. The result of this optimization is to reduce the total webprotal size from 478.4MB to 477.4MB.
The url module is built using the punycode and querystring modules, which are larger than the query string module. Webprotal uses the "url.parse().query" function of the url module to get the query type parameter of the address bar. However, this feature can be replaced by the "querystring.parse()" function in the smaller querystring module.
The reason is in lines 143 to 151 of url.js `this.query = querystring.parse(this.search.substr(1));`
used the parse method in querystring.  Both “url.parse().query” and "querystring.parse()" return an object, but …

optimization: Replace the url module with the querystring module

---

src/rest-server/src/templates/yarnContainerScript.mustache

Fixes messages in task `stderr` log when using a numeric-only task role:
```
...
jq: error: Invalid numeric literal at EOF at line 1, column 6 (while parsing '.0009.') at <top-level>, line 1:
.0009.taskStatuses.taskStatusArray[] | .containerIp, .containerPorts, .taskIndex
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.0009.taskStatuses.taskStatusArray[] | .containerIp, .containerPorts, .taskIndex      
jq: 2 compile errors
...
```
- Added quotes for task role names in `jq` queries

Fix jq invocation errors with numeric task roles

---

src/webportal/config/webpack.common.js
src/webportal/server/config/express.js

- webpack
- change dev server's port
- copy favicon to output directory root
- server
- fix some lint errors in express.js

[Web Portal] chore: keep using port 9286 in dev server; fix favicon.ico display

---

Jenkinsfile

release branch will change template to release tag, as jenkins relied on `latest` tag.

Fix jenkins failure on release branch

---

subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/applicationmaster/ApplicationMaster.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/applicationmaster/RequestManager.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/applicationmaster/SelectionManager.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/AggregatedFrameworkRequest.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/FrameworkDescriptor.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/FrameworkRequest.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/SummarizedFrameworkInfo.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/service/Service.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/webserver/RequestManager.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/webserver/WebServer.java
subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/zookeeperstore/ZookeeperStore.java

1. Add more info into SummarizedFrameworkInfo
https://github.com/Microsoft/pai/issues/2228
2. Skip to stop ZKStore in case it is still using
https://github.com/Microsoft/pai/pull/2408

[Launcher]: Add more info into SummarizedFrameworkInfo

---

docs/rest-server/API.md
src/rest-server/src/controllers/job.js
src/rest-server/src/models/job.js

- add task state field
- add job's retry details field
- refine job config api
- use request's Accept header to determine whether json or yaml will be sent.
- BREAK CHANGE: fix the bug that old job config api may return an escaped json string instead of a json object

[Rest API] Add task state; Add job's retry details; Refine job config

---

src/job-exporter/src/docker_inspect.py
src/job-exporter/test/data/inspect_result_bug_fix.json
src/job-exporter/test/test_docker_inspect.py

The assumption of job-exporter was broken by #2352 , which will cause the job-exporter stop reporting the GPU usage by tasks

fix void env supply by yarnScript

---

src/webportal/config/webpack.common.js
src/webportal/src/app/job/job-submit/job-submit.component.js
src/webportal/src/app/marketplace/job-submit/job-submit.component.js

#2361 
- add checksum to cloned job's name suffix
- prepare for job config api change (fix)

[Web Portal] Replace the suffix if a cloned job is resubmited

---

src/job-exporter/src/collector.py
src/job-exporter/src/ps.py
src/job-exporter/test/data/ps_sample.txt
src/job-exporter/test/test_ps.py
src/prometheus/deploy/alerting/node.rules

Get process memory consumption by ps rss, report those who use more than 500M to save space in prometheus. Also defined an alert rule for process `omiagent` and `omsagent`, these two processes are frequently causing OOM in azure VM, which DRI should take care of.

monitor process memory consumption and alert for om[is]agent

---

src/rest-server/src/templates/dockerContainerScript.mustache

We found that some command might consume 10+ secs, then job will be considered timeout and killed
Still investigating.

Extend job expiry to reduce false timeout

---

deployment/clusterObjectModel/mainParser/layout.py
deployment/clusterObjectModel/test/data/configuration-duplicate-hostname/kubernetes-configuration.yaml
deployment/clusterObjectModel/test/data/configuration-duplicate-hostname/layout.yaml
deployment/clusterObjectModel/test/data/configuration-duplicate-hostname/services-configuration.yaml
deployment/clusterObjectModel/test/data/configuration-none-overwrite/layout.yaml
deployment/clusterObjectModel/test/data/configuration-overwrite/layout.yaml
deployment/clusterObjectModel/test/test_cluster_object_model.py

Check duplicate `hostname` in kubernetes configuration.
Closes #2377.

[Deployment] Check duplicate hostname

---

src/drivers/build/install-all-drivers
src/drivers/config/drivers.py
src/drivers/config/drivers.yaml
src/drivers/deploy/drivers.yaml.template

Approach to skip InfiniBand installation, after the PR.
1): Configuration
Please set the following configuration into your service configuration.
```
drivers:
skip-ib-installation: true
```

[Drivers] Add an optional configuration to skip ib drivers installation.

---

src/prometheus/deploy/alerting/node.rules

fix alert label error in pai_node_count alert.
This metric is scrapped by watchdog, so the instance label will be where watchdog was deployed. We can not use this label, there are `name` label in watchdog to represent the node's IP, so we should use `name` here instead of `instance`.

fix alert label error

---

src/rest-server/src/models/job.js

This is full yarn entrypoint: 
`exec /bin/bash -c "source YarnContainerScripts/2.sh 1>$LAUNCHER_LOG_DIR/stdout 2>$LAUNCHER_LOG_DIR/stderr"`
`source` will extract the exit_handler to parent process  and bypass the redirect.
There are 2 fix options:
1. replace `source` with `bash`
2. move redirect out of quotation
Source:
Bash:

Fix script entrypoint to correctly redirect stdout/stderr

---

src/hadoop-ai/build/build-pre.sh
src/hadoop-ai/build/build.sh
src/hadoop-ai/build/hadoop-2.9.0-fix.patch
src/hadoop-ai/build/hadoop-ai

More readable patch: https://github.com/mzmssg/hadoop/pull/4/files
There will no duplicate stderr in diagnostics:
Original
Fixed

[hadoop] remove duplicate diagnostics

---

src/rest-server/src/templates/yarnContainerScript.mustache

Test case:
```json
{
"jobName": "test_failure",
"image": "openpai/pai.example.tensorflow:stable",
"authFile": "",
"dataDir": "",
"outputDir": "",
"codeDir": "",
"virtualCluster": "default",
"gpuType": "",
"retryCount": 0,
"taskRoles": [
{
"name": "111",
"taskNumber": 1,
"cpuNumber": 1,
"memoryMB": 1024,
"shmMB": 64,
"gpuNumber": 0,
"minFailedTaskCount": 1,
"minSucceededTaskCount": null,
"command": "sleep 5; exit 1",
"portList": []
}
],
"jobEnvs": {},
"extras": {}
}
```
Submit above job, 
before this PR, there are some false diagnostic in stderr or application summary:
```
YarnContainerScripts/0.sh: line 58: [: -gt: unary operator expected
```
After this PR, such diagnostic will disappear

[Bug]Add empty pid checker when kill user's container

---

src/prometheus/deploy/prometheus-deployment.yaml.template

Fixed #2449 
Before this PR, every time the prometheus get restart, all time series data will be lost. This PR change the location of data to host, and also prolong the retention date of data from default 15d to 31d to facilitate report generation.
Our biggest bed will consume 6.5G of space during 15d, so we can assume the space need will no more than 20G for a short term.

put prometheus data dir in host to avoid lost data during restart

---

deployment/tools/configMigration.py

Now the config migrate tool would read the image tag from the paictl version.
No need to edit the script for each release.

[HOT-FIX] config migrate tools read the docker image tag from the paictl version

---

deployment/tools/configMigration.py

Now the config migrate tool would read the image tag from the paictl version.
No need to update the script for each release.

config migrate tools read the docker image tag from the paictl version

---

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/util.js

Disable clone for old yaml jobs.
Do not support protocol job at present.

[Hotfix] Disable clone for old yaml jobs

---

src/rest-server/src/config/job.js
src/rest-server/src/controllers/job.js
src/rest-server/src/controllers/rewrite.js
src/rest-server/src/models/job.js
src/rest-server/src/routes/rewrite.js
src/rest-server/src/routes/user.js
src/rest-server/test/job.js
src/rest-server/test/jobDeletion.js
src/rest-server/test/jobDetail.js
src/rest-server/test/jobExecutionType.js
src/rest-server/test/jobSubmission.js

Closes #2439 
Rewrite them to `/jobs/:user~:jobname`-family.
<a name="tip">*</a>: If a namespace is already provided in job name, the `:user` param will be ignored, this is for e2e compatibility: a job created by `POST /user/:user/jobs` with un-namespaced job name would be able to retrieved by the following ways:
1. `GET /user/:user/jobs/:jobname`: client may hard coded the job name.
2. `GET /user/:user/jobs/:user~:jobname`: client may retrieve the job name from creating response.
3. `GET /jobs/:user~:jobname`: the new recommended way.
Including `GET` and `POST` requests.
The `POST` one is newly added for distinguish with legacy (pre-0.7.0) `POST /jobs` API
- If `POST /jobs` with **un-namespaced** job name is called, the legacy (pre-0.7.0) job without namespace will be created. This is …

[REST server]Use framework name as job name

---

src/drivers/build/install-all-drivers
src/drivers/config/drivers.py
src/drivers/config/drivers.yaml
src/drivers/deploy/drivers.yaml.template

Disable IB driver installation by default.
Azure VM builtin IB kernel modules into vmlinux image,
IB driver installation will fail in this case.
If IB installation is needed during deployment,
set `enable-ib-installation` field to `true` in config.

[Deployment] Disable IB driver installation by default

---

.travis.yml

Because of the release of [node 12](https://nodejs.org/en/blog/release/v12.0.0/), current travis CI broke due to [nan](https://github.com/nodejs/nan) issues in node 12.
Following packages will be affected in node 12 nan issue:
* node-sass
* deasync
Fix travis CI node version to 10 until the problem has been solved in upstream.

[Hotfix] Fix travis CI node version (#2650)

---

.travis.yml

Because of the release of [node 12](https://nodejs.org/en/blog/release/v12.0.0/) on April 23rd, current travis CI broke due to [nan](https://github.com/nodejs/nan) issues in node 12.
Following packages will be affected in node 12 nan issue:
* [node-sass](https://github.com/sass/node-sass/issues?q=is%3Aissue+is%3Aopen+label%3A%22Node+12%22)
* deasync
Fix travis CI node version to 11 until the problem has been solved in upstream.

[CI/CD] Fix travis CI node version

---

src/hadoop-data-node/deploy/delete.yaml.template
src/hadoop-data-node/deploy/hadoop-data-node-delete/delete-data.sh

fix #2637 
Test case: 
**Don't test it on production** 
1. Stop data node
`./paictl.py service stop -n hadoop-data-node`
2. Edit `service-configuration.yaml`, add following lines
```yaml
hadoop-data-node:
storage_path: /mnt/hdfs-test/data1,/mnt/hdfs-test/data2
```
3. Start data node
`./paictl.py service start -n hadoop-data-node`
4. Delete name node & data node
`./paictl.py service delete -n hadoop-data-node && ./paictl.py service delete -n hadoop-name-node`
5. Start name node & data node
`./paictl.py service start -n hadoop-data-node && ./paictl.py service start -n hadoop-name-node`
Before this PR, data node should fail

fix hdfs delete failure

---

src/rest-server/build/rest-server.dockerfile

Installed versions (on 2019/4/24)
- `dos2unix`
- In `openpai/rest-server:v0.12.0`: dos2unix 7.3.4 (2016-05-24)
- Manual remove jessie-backports source: dos2unix 7.3.4 (2016-05-24)
- `openssh-server`
- In `openpai/rest-server:v0.12.0`: OpenSSH_7.4p1 Debian-10+deb9u5, OpenSSL 1.0.2q  20 Nov 2018
- Manual remove jessie-backports source: OpenSSH_7.4p1 Debian-10+deb9u6, OpenSSL 1.0.2r  26 Feb 2019

[REST Server] Remove jessie-backports source

---

src/webportal/config/webpack.common.js
src/webportal/src/app/marketplace/job-submit/sub-components/user-template.js

job-detail gzipped size:  760.51KB -> 561.4KB
- monaco-editor: remove unused features and languages
- js-yaml: remove optional esprima dependency
- chart.js: remove optional moment dependency

[Web Portal] reduce bundle size

---

src/hadoop-ai/build/build-pre.sh
src/hadoop-ai/build/hadoop-ai-fix.patch

TODO:
Accquire structural gpu info by `nvidia-smi -x`

Rewrite hadoop-ai regex to match gpu info

---

src/rest-server/src/templates/yarnContainerScript.mustache

Add IPC_LOCK capability `--cap-add IPC_LOCK` and /dev/infiniband devices `--device=/dev/infiniband` for jobs to use InfiniBand in non privileged Docker. Will check the IB device automatically.
Before this PR, host can install IB OFED drivers but jobs cannot use infiniband network inside container. With this PR, infiniband network will be enabled automatically for jobs if IB device is available.
Reference: https://community.mellanox.com/s/article/how-to-create-a-docker-container-with-rdma-accelerated-applications-over-100gb-infiniband-network#jive_content_id_Option_2

Add capability/device for jobs to use InfiniBand

---

README.md
README_zh_CN.md

Fix link of travis ci status in README.
__Background__: Microsoft org has changed to lower case on GitHub
GitHub link is case insensitive, but travis status link is case sensitive and got broken.
__Before__: https://travis-ci.org/Microsoft/pai
__After__: https://travis-ci.org/microsoft/pai

[Docs] Fix link of travis ci status in README

---

src/watchdog/src/watchdog.py
src/watchdog/test/test_watchdog.py

Previous watchdog use `/api/v1/namespaces/{}/pods` iterate all namespace to get all pods, simplify it to get via `/api/v1/pods`.
This can reduce number of http get watchdog issues.

use api/v1/pods to get all pods

---

src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/core-site.xml

There are some exception when we enable both cross origin and queue api, as below, since we havn't used RM cross origin, disable it here:
```
19/05/14 09:54:54 DEBUG mortbay.log: REQUEST /ws/v1/cluster/scheduler on org.mortbay.jetty.HttpConnection@12829025
19/05/14 09:54:54 DEBUG mortbay.log: sessionManager=org.mortbay.jetty.servlet.HashSessionManager@3be4fcc0
19/05/14 09:54:54 DEBUG mortbay.log: session=null
19/05/14 09:54:54 DEBUG mortbay.log: servlet=org.mortbay.jetty.servlet.DefaultServlet-1005331061
19/05/14 09:54:54 DEBUG mortbay.log: chain=NoCacheFilter->NoCacheFilter->safety->Cross Origin Filter->org.apache.hadoop.security.http.XFrameOptionsFilter->guice->org.mortbay.jetty.servlet.DefaultServlet-1005331061
19/05/14 09:54:54 DEBUG mortbay.log: servlet …
```

Mitigate vc update failure

---

docs/alerting/exporter-metrics.md
src/job-exporter/src/collector.py
src/job-exporter/src/nvidia.py
src/job-exporter/test/test_collector.py
src/job-exporter/test/test_nvidia.py

required by DLWS, may also be useful to pai.

add gpu temperature detection

---

src/rest-server/src/middlewares/v2/converter.js
src/rest-server/src/util/converter.js
src/rest-server/test/converter.js

Add job config v1 to v2 converter.

[Rest Server] Add job config v1 to v2 converter

---

src/rest-server/src/models/job.js
src/rest-server/src/models/v2/job.js
src/rest-server/src/templates/yarnContainerScript.mustache

Check default runtime before starting Docker, fix #2739.
If nvidia-docker is installed and nvidia runtime is enabled by default, start nvidia-docker and isolate GPU through `NVIDIA_VISIBLE_DEVICES` provided by nvidia runtime.

[Rest Server] Check default runtime before starting Docker

---

src/rest-server/src/config/v2/protocol.js
src/rest-server/src/middlewares/v2/protocol.js
src/rest-server/src/models/v2/job.js
src/rest-server/src/templates/yarnContainerScript.mustache
src/rest-server/src/util/protocolSecret.js
src/rest-server/test/protocolSecret.js
src/rest-server/test/v2/protocol.js

Add secrets field in protocol, implement #2729:
* Update protocol schema
* Parse and render secrets field in commands/auth
* Support Docker login using secrets, remove credentials from `set -x` debug log
* Mask secrets field when storing yaml

[Rest Server] Add secrets field in protocol

---

src/prometheus/deploy/alerting/pai-services.rules

Previous rule triggered too frequently, since many are due to IO slow instead of IO hangs, and can mitigate automatically. This alert was intend to catch IO hangs and when triggered the node may need to be restarted, so change triggering rule to make it less frequent.

change triggering rule for exporter hangs

---

docs/pai-job-protocol.yaml
src/rest-server/src/config/v2/protocol.js
src/rest-server/src/middlewares/v2/protocol.js
src/rest-server/src/models/v2/job.js
src/rest-server/src/templates/yarnContainerScript.mustache
src/rest-server/src/util/protocolSecret.js
src/rest-server/test/protocolSecret.js
src/rest-server/test/v2/protocol.js

Support secrets in protocol
------------------------------
Users may need sensitive information including password or API key in their jobs, `secrets` section is used to help user hide those sensitive information in plain text and avoid sharing.
Work items
------------

[Protocol] Support secrets in protocol

---

deployment/clusterCmd.py
deployment/confStorage/download.py
deployment/confStorage/external_version_control/external_config.py
deployment/confStorage/upload.py
deployment/k8sPaiLibrary/maintainlib/kubectl_install.py
deployment/machineCmd.py
deployment/serviceCmd.py
deployment/utility/sftp_copy.py
deployment/utility/ssh.py

Allow user to use <kbd>Backspace</kbd> when inputing in paictl.
Currently, <kbd>Backspace</kbd> will results `^H` in stdin.

[Deployment] Allow user to use Backspace in paictl input

---

src/job-exporter/src/collector.py

Add DLTS services names to job-exporter white list so job-exporter could also monitor dlts service's resource usage.

add DLTS services names to job-exporter white list

---

src/webportal/src/app/job/job-view/fabric/job-detail/conn.js

[Webportal] Fix job clone bug

---

src/authentication/config/authentication.yaml
src/rest-server/deploy/group-configmap/group.yaml.template
src/rest-server/src/config/authn.js
src/rest-server/src/config/v2/user.js
src/rest-server/src/controllers/v2/group.js
src/rest-server/src/controllers/v2/user.js
src/rest-server/src/models/v2/group.js
src/rest-server/src/routes/v2/user.js

Api modify

---

src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job.js

[Rest Server] Add get job api v2

---

contrib/marketplace/yarn.lock
contrib/pai_vscode/yarn.lock
contrib/submit-job-v2/yarn.lock
src/webportal/yarn.lock

Versions of `fstream` prior to `1.0.12` are vulnerable to Arbitrary File Overwrite.
Upgrade` fstream` to `1.0.12` to fix vulnerability.

[Plugin] Upgrade fstream version to fix vulnerability

---

src/webportal/src/app/components/auto-complete.jsx
src/webportal/src/app/home/home.jsx

> The AutoComplete is an extension of a regular text-field that will auto-complete the input dynamically.
The difference between AutoComplete and ComboBox is that it is mainly focused on text input.
- `items`
- string[], required
- Array of suggestions. Only suggestions prefixed by current text field `value` are displayed by default.
- `value`
- string, required
- TextField's value
- `onChange`
- callback function, required
- (newValue: string) => {}
- TextField's onChange function
- `showAllSuggestions`
- boolean, required
- Whether to disable suggestions' default prefix filter.
```
const app = () => {
const [val, setVal] = useState('');
return (
<AutoComplete
value={val}
onChange={setVal}
items={['pen', 'apple', 'applepen']}
/>
);
}
```

[Web Portal] AutoComplete component

---

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/hdfs-site.xml

This is an attempt to suppress the warning in tf gfile:
```
19/06/04 04:18:48 WARN hdfs.DFSClient: Error Recovery for block BP-1214599446-127.0.0.1-1542938874046:blk_1075798010_2071296 in pipeline DatanodeInfoWithStorage[10.0.0.11:5010,DS-cbdc31a9-41a2-4fe6-8bb0-feb70edf5edd,DISK], DatanodeInfoWithStorage[10.0.0.17:5010,DS-20f235bc-947e-4f79-b676-4d7fc13cafb5,DISK], DatanodeInfoWithStorage[10.0.0.20:5010,DS-e6f17471-5ee3-406b-a092-4ec6bb9cc38c,DISK]: bad datanode DatanodeInfoWithStorage[10.0.0.20:5010,DS-e6f17471-5ee3-406b-a092-4ec6bb9cc38c,DISK]
19/06/04 04:18:48 WARN hdfs.DFSClient: DataStreamer Exception
java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: …
```

[HDFS] client tolerate datanode replacement failure

---

src/rest-server/src/util/protocolSecret.js
src/rest-server/test/protocolSecret.js

Add quotes for masked secrets field in protocol to avoid "unidentified alias" exception in getting v1 config.

[Rest Server] Add quotes for masked secrets field in protocol

---

src/drivers/build/install-all-drivers

Use `[[` to replace `[` in drivers config detection.

[Drivers] Use `[[` to replace `[` in drivers config detection

---

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml.template
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml.template

Update yarn-site.xml to fit DGX-2 maximum resources.
Closes #2740.

Update maximum resources in yarn-site.xml

---

docs/tools/dedicated_vc.md
src/dev-box/build/dev-box.dockerfile
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/hdfs-site.xml
src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/resourcemanager-generate-script.sh
src/tools/.gitignore
src/tools/config/logging.yaml
src/tools/node_maintain.py
src/tools/operator_wrapper/__init__.py
src/tools/operator_wrapper/alert_operator.py
src/tools/operator_wrapper/base_operator.py
src/tools/operator_wrapper/kubernetes_operator.py
src/tools/operator_wrapper/yarn_operator.py
src/tools/tests/__init__.py
src/tools/tests/capacity_scheduler_case1.json
src/tools/tests/cluster_nodes_case1.json
src/tools/tests/test_alert_operator.py
src/tools/tests/test_kubernetes_operator.py
src/tools/tests/test_node_maintain.py
src/tools/tests/test_yarn_operator.py
src/tools/utility/__init__.py
src/tools/utility/common.py
src/tools/utility/log.py

[dedicated vc] management tool

---

src/rest-server/src/models/job.js

Trap SIGTERM in entrypoint to avoid yarn container early stop

---

src/job-exporter/src/collector.py
src/job-exporter/src/docker_inspect.py
src/job-exporter/test/test_collector.py
src/job-exporter/test/test_docker_inspect.py

Distributed job's resource usage requires pod_name to exist.

add pod_name to task related resource usage metrics

---

src/watchdog/src/watchdog.py
src/watchdog/test/data/dlts_non_preemptable_pod.json
src/watchdog/test/data/dlts_preemptable_pod.json
src/watchdog/test/data/vc_quota.json
src/watchdog/test/test_watchdog.py

Add `vc_url` argument for watchdog to get per vc gpu quota.
Will emit three metrics:
* `k8s_vc_gpu_total`: quota of each gpu type from each VC
* `k8s_vc_gpu_available`: k8s_vc_gpu_total – (sum of gpu used by all jobs in this VC)
* `k8s_vc_gpu_preemptive_availabe`: k8s_vc_gpu_total – (sum of gpu used by all jobs with preemptionAllowed=False in this VC)
All these metrics have 2 labels: `vc_name` and `gpu_type`.

support per vc gpu available count

---

src/rest-server/src/config/launcher.js
src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job/index.js
src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/routes/v2/job.js

Part of #2933, moved from #2979.
Support framework controller in rest server, migrate api v2:
* POST /api/v2/jobs
* GET /api/v2/jobs

[Rest Server] Support framework controller

---

src/hadoop-ai/build/build-pre.sh
src/hadoop-ai/build/build.sh
src/hadoop-ai/build/hadoop-ai
src/hadoop-ai/build/hadoop-ai-port-conflict.patch

Fix #1983 
patch at https://github.com/mzmssg/hadoop/pull/5/files
Cause:
RM doesn't exclude localused port in nodeReport

[hadoop-ai] port conflict

---

docs/tools/how-to-setup-report-script.md
src/tools/reports.py
src/tools/reports_requirements.txt

generate csv reports for OpenPai cluster.
Document is in the header of the script.

add script to generate reports for OpenPai cluster

---

src/node-exporter/deploy/node-exporter.yaml.template

related to #2117 , ignore those network based filesystems in node-exporter. So the source down will not affect node-exporter.
We append `cifs|nfs4?|lxcfs` to the [`defIgnoredFSTypes`](https://github.com/prometheus/node_exporter/blob/v0.18.0/collector/filesystem_linux.go#L33).

ignore network based file systems in node-exporter

---

src/webportal/src/app/job-submission/components/data/custom-storage.jsx
src/webportal/src/app/job-submission/components/data/data-component.jsx
src/webportal/src/app/job-submission/components/data/mount-tree-view.jsx
src/webportal/src/app/job-submission/components/data/team-storage.jsx
src/webportal/src/app/job-submission/components/sidebar/parameters.jsx
src/webportal/src/app/job-submission/components/submission-section.jsx
src/webportal/src/app/job-submission/job-submission.jsx

1. add data instruction
2. add parameter instruction
3. adjust stack position to support responsive

refine submit job UI page

---

src/rest-server/src/templates/dockerContainerScript.mustache
src/rest-server/src/templates/yarnContainerScript.mustache

1. try to kill docker process session instead of only the root process, to avoid exit delay.
2. docker sigterm handler should exit 143

[runtime] fix and improvement

---

Jenkinsfile
deployment/confStorage/conf_storage_util.py
deployment/confStorage/upload.py

After this change
1. New cluster's id will be got from service-configuration.yaml->cluster->common
2. The default cluster-id will be 'pai'
3. If admin update the cluster-id in service-configuration.yaml, and then push the latest configuration into k8s. Paictl will detect it, and update the id in cluster.

[paictl] Unify cluster ID

---

src/webportal/src/app/user/fabric/userView/Table.jsx
src/webportal/src/app/user/fabric/userView/TopBar.jsx

As discussed, this PR have below changes:
* disable edit button in the row when select multi users
* allow batch edit admin's password
* add tips for the disabled buttons

[Web Portal] Redesign batch edit behavior

---

src/rest-server/src/templates/dockerContainerScript.mustache
src/rest-server/src/templates/yarnContainerScript.mustache

New log file named /pai/log/user.pai.all is added
log can be retrieved by:
http://host_ip/yarn/host_ip:8042/node/containerlogs/container_e68_1563150728066_0003_01_000002/admin/user.pai.stdout

Add log file which merge user stdout & stderr

---

src/webportal/src/app/job-submission/models/job-protocol.js

When clone a job with deployment field. In new submission page, the origin deployment info will be cleaned. Fix this issue.

fix deployment field missing bug

---

src/rest-server/src/templates/dockerContainerScript.mustache

In ubuntu18.04, the configuration of the default port of sshd service is commented out like "#Port 22".   Thus, sed -i 's/Port.*/Port '$PAI_CONTAINER_SSH_PORT'/' missed  ’#‘ and it cannot start sshd service on $PAI_CONTAINER_SSH_PORT.

match commented out sshd port

---

src/kube-runtime/src/init.d/parse.py
src/kube-runtime/src/runtime
src/kube-runtime/src/runtime.d/port.py
src/webportal/src/app/job/job-view/fabric/JobList/utils.js

Add port conflict check in runtime.

[Kube Runtime] Add port conflict check

---

docs/rest-server/API.md
src/rest-server/package.json
src/rest-server/src/controllers/job.js
src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job/yarn.js
src/rest-server/src/utils/converter.js
src/rest-server/test/jobConfig.js

BREAKING CHANGE !!!
- The rest server should treat job config file as plain text, so accept header feature should not be implemented

[Rest Server] ignore get job config's accept header

---

src/webportal/src/app/job/job-view/fabric/job-detail/conn.js

fix the incorrect full log link due to yarn log page's [base](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element.

[Web Portal] fix "view full log" link in job submission page

---

src/prometheus/deploy/alerting/gpu.rules
src/prometheus/deploy/prometheus-configmap.yaml.template
src/prometheus/deploy/prometheus-deployment.yaml.template
src/prometheus/deploy/recording/gpu.rules

Add alert when node GPU count is changed. This may caused by driver issue.
Add a record rule to generate a new metric: `node:nvidiasmi_utilization_gpu:count`, which is calculated by: `count(nvidiasmi_utilization_gpu) by (instance)`
Add a new alert when `changes(node:nvidiasmi_utilization_gpu:count) > 0`

add alert for gpu count changes

---

src/hadoop-ai/build/build-pre.sh
src/hadoop-ai/build/docker-executor.patch

Fix #3202 
Use the latest hadoop regex, reference https://github.com/apache/hadoop/blob/29465bf169a7e348a4f32265083450faf66d5631/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/src/main/java/org/apache/hadoop/yarn/server/nodemanager/containermanager/linux/runtime/DockerLinuxContainerRuntime.java#L205
Test:
```
Old pattern: ^(([\w\.-]+)(:\d+)*\/)?([\w\.-]+\/)?[\w\.:-]+$
[OK] Old pattern pass test string: registry.somecompany.com:9999/containername:0.1
[OK] Old pattern pass test string: containername:0.1
[OK] Old pattern pass test string: containername
[Fail] Old pattern fail test string: harbor.bglab.com/library/openpai/hadoop-run:v0.12.0
New pattern: ^(([a-zA-Z0-9.-]+)(:\d+)?/)?([a-z0-9_./-]+)(:[\w.-]+)?$
[OK] New pattern pass test string: …
```

Fix hadoop image name check

---

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx

If a job does not contain ssh info, the page will give the reason and offer some solutions.

Update SSH info for better user experience

---

src/webportal/build/build-pre.sh
src/webportal/build/webportal.dockerfile
src/webportal/config/webpack.common.js
src/webportal/src/app/layout/layout.component.ejs

If build with the following environmental variable, a commit ID will be attached to webportal.
```bash
ATTACH_COMMIT_ID=true ./build/pai_build.py build -c ~/pai-config/ -s webportal
```
It looks like:

Attach a commit ID for webportal

---

deployment/k8sPaiLibrary/template/kubelet.sh.template

Remove deprecated `--require-kubeconfig` flag for kubelet.

[Deployment] Remove deprecated flag for kubelet

---

src/webportal/config/webpack.common.js

Resolve webpack chunks runtime conflicts between webportal and plugins,
use another `jsonpFunction` name for webportal.
Issue left in #3244.
Reference: https://webpack.js.org/configuration/output/#outputjsonpfunction

[Webportal] Fix webpack conflict

---

deployment/serviceCmd.py
docs/pai-management/doc/how-to-start-pai-serv.md
docs/pai-management/doc/validate-deployment.md
docs/paictl/paictl-manual.md
docs/zh_CN/pai-management/doc/how-to-start-pai-serv.md
docs/zh_CN/pai-management/doc/validate-deployment.md
docs/zh_CN/paictl/paictl-manual.md

Support to manage a list of services in `paictl`.
Fixes #2734.

[Deployment] Support to manage a list of services in paictl

---

src/webportal/src/app/job-submission/components/tools/tensorboard.jsx

Fix bug:
If there is no team storage, the entire page will be blank when TensorBoard is enabled.

[TensorBoard]Fix TensorBoard bug

---

src/tools/reports.py

PaiJobsZombie alert do not have minor_number label, use default instance label.
`ALERTS{alertname="PaiJobsZombie",alertstate="firing",instance="172.23.233.62:9102",job="pai_serivce_exporter",pai_service_name="job-exporter",scraped_from="job-exporter-bmhml",type="residual_job"}`

PaiJobsZombie do not have minor_number

---

src/hivedscheduler/deploy/service.yaml
src/hivedscheduler/deploy/start.sh.template
src/hivedscheduler/deploy/stop.sh.template
src/rest-server/deploy/rest-server.yaml.template
src/rest-server/src/config/launcher.js
src/rest-server/src/config/vc.js
src/rest-server/src/controllers/v2/virtual-cluster.js
src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/models/v2/virtual-cluster/k8s.js
src/rest-server/src/routes/v2/virtual-cluster.js
src/webportal/src/app/home/home/conn.js

Change to default k8s scheduler.

[Rest Server] Change to default k8s scheduler

---

src/drivers/deploy/service.yaml

Remove drivers serivce in k8s cluster deployment, users should install nvidia drivers on the host by themselves.
With nvidia device plugin, [job-exporter](https://github.com/Microsoft/pai/blob/master/src/job-exporter/deploy/job-exporter.yaml.template#L71-L72) and user jobs will work w/o drivers service in k8s cluster.

Remove drivers service in k8s cluster deployment

---

src/rest-server/src/models/v2/job/k8s.js

Add pod GPU number for default scheduler.

[Rest Server] Add pod GPU number for default scheduler

---

src/grafana/deploy/grafana-configuration/prom-datasource.json.template
src/pylon/deploy/pylon-config/location.conf.template

Before this change, grafana access Prometheus from the front-end. And it doesn't work in the env with the gateway. Change it to though back-end proxy.
The request flow is changed from "Grafana->Gateway->Pylon->Prometheus" to  "Grafana->->Prometheus"

fix grafana can not be accessed behind the gateway

---

src/frameworkcontroller/deploy/delete.sh

Froeground stop all frameworks before delete controller crd.

Foreground stop all frameworks

---

src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/models/v2/job/yarn.js

Make gang scheduling optional, allow user to disable gang scheduling by setting:
```yaml
extras:
gangAllocation: false
```
Close #3519.

[Rest Server] Make gang scheduling optional

---

src/rest-server/src/models/v2/job/k8s.js

Enable fancy retry policy for elastic tasks,
task will retry for transient failure, e.g. node deallocation.

[Rest Server] Enable fancy retry policy for elastic tasks

---

deployment/k8sPaiLibrary/template/docker-daemon.json.template

Because K8S does not recognize multiple rotated files yet

Increase container log max size and keep single log file

---

src/rest-server/src/models/v2/job/k8s.js

Add node selector for user jobs in k8s,
only run user pods on pai-worker nodes.

[Rest Server] Add node selector for user jobs in k8s

---

deployment/k8sPaiLibrary/template/apiserver.yaml.template
deployment/k8sPaiLibrary/template/scheduler.yaml.template
src/hivedscheduler/deploy/hivedscheduler-config.yaml.template
src/hivedscheduler/deploy/hivedscheduler.yaml.template
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/example/run/deploy.yaml

Support https://github.com/microsoft/pai/issues/3704

Tune default scheduler to support Job FIFO

---

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
src/kube-runtime/build/kube-runtime.dockerfile
src/kube-runtime/src/init

In prod env, we saw when node down and up. The pod running on this node
may be restarted by kubelet. Even though the `restartPolicy` set to
`Never`. If that happens, the init container script will failed when
executing `mv` command. To prevent this, we clean the `${PAI_WORK_DIR}`
before mv content to this folder.

clean ${PAI_WORK_DIR} before mv content to this folder

---

src/webportal/src/app/job/job-view/fabric/job-detail.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role.jsx

[Web Portal] Seperate 'waiting' and 'running' states on task role's statistics

---

src/watchdog/src/watchdog.py
src/watchdog/test/data/dlws_nodes_list.json
src/watchdog/test/data/dlws_nodes_list_with_unschedulable.json
src/watchdog/test/test_watchdog.py

GPU Accounting Formula
Capacity = Allocatable + Unallocatable
Allocatable = Used in Allocatable + Available
Capacity: Total number of GPUs in the cluster, regardless of its usability.
Allocatable: Number of GPUs that are good for immediate allocation in the cluster.
Unallocatable: Number of GPUs that are bad, pending repair (e.g. GPUs having DBE).
Used in Allocatable: Number of GPUs in use by user jobs in the cluster.
Available: Number of GPUs available for usage in the cluster. This is the number users care about.
With above definition:
* `k8s_node_gpu_total` is collected from k8s node capacity, represents Capacity mentioned above. It will **not** be 0 when the node become unschedulable or not ready.
* `k8s_node_gpu_allocatable` is collected from k8s node allocatable, represents …

add k8s_node_gpu_allocatable remove k8s_node_gpu_reserved

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/cell.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/config.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/constants.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/intra_vc_scheduler.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/common/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/common/utils.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/utils.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go

- In-VC scheduling no longer relies on cells (and buddy alloc).
- Wrote a topology-aware scheduling algorithm, which is used for in-VC scheduling and opportunistic pod scheduling.
- Cell priority mechanism simplified: only keeps a free cell list for the physical cluster for regular pod scheduling, and a full cell list for opportunistic pod scheduling. They are decoupled now.

HiveD algorithm refactor

---

contrib/storage_plugin/README.MD
contrib/storage_plugin/storagectl.md
contrib/storage_plugin/storagectl.py
docs/rest-server/API.md
src/rest-server/deploy/delete.sh
src/rest-server/deploy/secret-create.sh
src/rest-server/src/controllers/v2/storage.js
src/rest-server/src/controllers/v2/user.js
src/rest-server/src/models/v2/group.js
src/rest-server/src/models/v2/storage.js
src/rest-server/src/models/v2/user.js
src/rest-server/src/routes/v2/storage.js
src/rest-server/src/utils/manager/storage/crudK8sSecret.js
src/rest-server/src/utils/manager/storage/crudUtil.js
src/rest-server/src/utils/manager/storage/storage.js
src/webportal/src/app/job-submission/components/data/data-component.jsx
src/webportal/src/app/job-submission/components/data/team-detail.jsx
src/webportal/src/app/job-submission/utils/conn.js

Add CRUD for Storage 
Set storage configs for group 
Get user storage config in user info
Call Storage Rest Api in webportal
Refine Storage CLI

Storage Rest API, Refine Storage Data and CLI

---

src/rest-server/src/models/v2/job/k8s.js

Decompress possible fields for large framework.
Reference: https://github.com/microsoft/frameworkcontroller/pull/44

[Rest Server] Decompress large framework

---

src/kube-runtime/src/init

Runtime goes wrong when repeat execuate in same env. Fix such bug

[kube-runtime] fix runtime bug

---

docs/rest-server/API.md
src/rest-server/deploy/delete.sh
src/rest-server/src/config/kubernetes.js
src/rest-server/src/controllers/v2/token.js
src/rest-server/src/controllers/v2/user.js
src/rest-server/src/middlewares/token.js
src/rest-server/src/models/k8s-secret.js
src/rest-server/src/models/token.js
src/rest-server/src/routes/authn.js
src/rest-server/src/routes/token.js
src/rest-server/src/routes/v2/group.js
src/rest-server/src/routes/v2/user.js
src/rest-server/src/routes/v2/virtual-cluster.js
src/rest-server/src/routes/vc.js
src/rest-server/src/utils/manager/user/user.js
src/rest-server/test/data/nock/group-template.yaml
src/rest-server/test/data/nock/user-template.yaml
src/rest-server/test/groupManagement.js
src/rest-server/test/jobDeletion.js
src/rest-server/test/jobExecutionType.js
src/rest-server/test/jobSubmission.js
src/rest-server/test/userManagement.js
src/rest-server/test/userToken.js
src/rest-server/test/utils/nock.js
src/rest-server/test/vc.js
src/rest-server/yarn.lock

- Application will be a JSON Web Token with an additional boolean field `application`
- User / frontend service can decode the jwt and get if the token is an application token
- Since we will query `k8s secret` when authentication (check if it is revoked), the `admin` field in jwt is removed. The permission info will be retrieved dynamically from `k8s secret`
- The signed jwt list will be stored in the `pai-user-token` namespace of `k8s secret`
- Each user's token list will be a k8s secret item
- name: username's hex string
- data: uuid -> token
- The namespace will be created (if not exist) when rest server starts
- `Token is expired` error message is removed. 
- Only a `token is invalid` error message will be shown now.
- Since previous k8s secret interface is implemented for specific …

[Rest Server] Application token api

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/cell.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/intra_vc_scheduler.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/types.go

Support for reconfigurations.
1. Physical cell of a pod cannot be found: ignore the pod (won't add it to the internal view).
2. Virtual cell of a pod cannot be found, i.e., usage exceeds quota: downgrade the affinity group to opportunistic.
3. Physical and virtual cells cannot be bound, i.e., cell hierarchies don't match: downgrade the affinity group to opportunistic.
Aware of K8s suggested nodes: will use nodes suggested by K8s first. Note that this is best-effort, meaning that if we have to use a node not in the suggested nodes for safety reasons, we will still return that node. Such a case will result in a panic during scheduling, which will terminate this scheduling cycle immediately and start the next one.
This PR also has several minor bug fixes.

HiveD Reconfiguration

---

docs/pai-management/doc/how-to-install-depdencey.md

Fix some missing dependencies during installation (introduced by v0.14.0)
1. python2 "future" package
2. python3 "kubernetes" package
used in: 
https://github.com/microsoft/pai/blob/master/src/rest-server/deploy/user_v2_migrate.py
https://github.com/microsoft/pai/blob/master/src/rest-server/deploy/legacy_user_migrate.py

fix missing dependencies during installation

---

src/webportal/src/app/job-submission/components/data/data-component.jsx
src/webportal/src/app/job-submission/components/data/team-storage.jsx
src/webportal/src/app/job-submission/job-submission-page.jsx
src/webportal/src/app/job-submission/utils/constants.js
src/webportal/src/app/job-submission/utils/utils.js

Use extras to save team-storage selection
When clone job, the team storage will be selected base on previous job.
If from old job format or create new job, default team storage will be mounted

Use extras to save team-storage selection

---

src/kube-runtime/build/kube-runtime.dockerfile
src/kube-runtime/src/init.d/initializer.py
src/kube-runtime/src/init.d/parser.py

FC will compress the framework when it's size is large.
Since we need the FC spec in runtime, decompress here.
Also update the python from 2.7 to 3.7

[runtime] decompress the framework when the size is large

---

src/rest-server/src/models/v2/virtual-cluster/k8s.js

Filter pods without nodename and completed pods in virtual cluster resources.

[Rest Server] Filter pods without nodename and completed pods

---

src/webportal/src/app/components/status-badge.jsx
src/webportal/src/app/components/theme.js
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role.jsx

#3819 
- seperate stopped status from unknown status
- tweak stopped badge's color
- extract TaskRoleCount component from task role's header

[Web Portal] display stopped task count in task role's header

---

src/rest-server/src/models/v2/job/k8s.js

Update restart policy to avoid stuck pending pods #3760.

[Rest Server] Update restart policy to avoid stuck pending pods

---

src/webportal/config/webpack.common.js
src/webportal/package.json
src/webportal/server/config/express.js
src/webportal/src/app/home/index.ejs
src/webportal/src/app/layout/layout.component.ejs

There are 2 main issues about static content (js, style css, font, svg, .., etc) in current webportal:
- They are caching-disabled. The `max-age` in the response header for them is 0. Thus, the browser will always download these contents, which increases both the front-end loading time and the server's traffic.
- Many js files are splitted into very small chunks (<1kb), which means they should also be transferred by new HTTP connection.
This PR sets a `max-age` for those contents,  use `contenthash` in webpack to ensure correct caching, 
and only js files larger than 30kb would be chunked.
Loading `submit.html` before and after optimization (tested for 5 times in each case):
- Before optimization + First loading: 4.19s ~ 8.61s
- Before optimization + Second loading: 4.21s~6.49s
- After …

[Webportal] static content caching optimization

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/example/config/design/hivedscheduler.yaml
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go

If a restarted scheduler finds that the quota of a certain type of cell is insufficient, it will try to preempt (downgrade) pods with lower priority from the VC.

HiveD intra-vc preemption for restart

---

src/rest-server/src/models/v2/job/k8s.js

Revert "[Rest Server] Update restart policy to avoid stuck pending pods"

---

src/rest-server/src/middlewares/v2/hived.js

Update hived resource validation.

[Rest Server] Update hived resource validation

---

src/job-exporter/deploy/job-exporter.yaml.template
src/job-exporter/src/nvidia.py
src/job-exporter/test/data/nvidia_smi_out_of_order.xml
src/job-exporter/test/test_nvidia.py

Tested in vnext bed. After this fix, the task role metrics show correctly
Refer: https://github.com/NVIDIA/nvidia-docker/issues/376
GPU minor number not match NVIDIA_VISIBLE_DEVICES  sometimes

[Job-exporter] Fix gpu matrix not match task-role issue

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/config.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go

Record cell type name (instead of the level) in pod annotation. This enables us to shorten / lengthen cell chain.
This PR also adds some log enrichment.

HiveD: record cell type in pod annotation

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/config.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/types.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/common/utils.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go

This PR is to enable partial release of resources used by an affinity group. If a group allows partial release, its resource will be released in a per-pod manner.
This PR also fixes bugs in mapping placements of a group to the pods in the group (previously pods of the same group might be mapped to conflicted placement).

[HiveD] support partial release of affinity group

---

contrib/pai_vscode/src/pai/paiJobManager.ts

Fix the vs code extension simulation bug: /bin/sh: 1: Bad substitution

[VS Code] use bash in simulation

---

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx

Hide warning icon when retry is 0

---

src/prometheus/deploy/prometheus-deployment.yaml.template

Prometheus cause high io usage because some folders owner is root and permission is 755. But Prometheus default user is nobody:nogroup.
Prometheus service can not change the previous folder, and stuck at compacting logs. So high disk io occur.
Fix this issue by change the folder owner to nobody:nogroup

[Prometheus ] Fix prometheus high io issue

---

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go
subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go

If a pod's placement has been invalid (e.g., due to reconfiguration), we will retrieve its placement from other pods' annotation and then insist the binding decision.

[HiveD] fix pod hanging after reconfiguration

---

src/webportal/config/webportal.py
src/webportal/deploy/webportal.yaml.template

**Change**
1: Skip ```hadoop-resource-manager.master-ip``` check it when the ```cluster-type``` isn't yarn.
2: Remove the env named ```YARN_WEB_PORTAL_URI``` from the pod of webportal if the ```cluster-type``` isn't yarn.
**TODO**
The file need to be changed after this change.
https://github.com/microsoft/pai/blob/15ed057560553cd86a6041bc159b1a4065ca7611/src/webportal/src/app/env.js.template#L4
https://github.com/microsoft/pai/blob/ca0e213e05cfc5024b4886be249186173204709f/src/webportal/src/app/vc/vc.component.js#L33
https://github.com/microsoft/pai/blob/ea429d6b82cac78d7d2b4807981f23c94db12aeb/src/webportal/src/app/vc/vc.component.ejs#L68
https://github.com/microsoft/pai/blob/ea429d6b82cac78d7d2b4807981f23c94db12aeb/src/webportal/src/app/vc/vc.component.ejs#L137
I think this page or the …

[Cluster Objec Model]Don't check hadoop rm uri when in pure k8s cluster.

---

src/kube-runtime/src/plugins/teamwise_storage/README.md
src/webportal/src/app/job-submission/components/data/data-component.jsx
src/webportal/src/app/job-submission/components/data/team-storage.jsx
src/webportal/src/app/job-submission/job-submission-page.jsx
src/webportal/src/app/job-submission/models/protocol-schema.js
src/webportal/src/app/job-submission/utils/constants.js
src/webportal/src/app/job-submission/utils/utils.js

When using storage plugin, we will not inject commands into the user command. Just change the extra field in the protocol.
Sample:
```yaml
extras:
com.microsoft.pai.runtimeplugin:
- plugin: teamwiase_storage
parameters:
storageConfigNames:
- PAI_SAHRE  # storage config name provided by admin
```
- Fix plugin can not be removed bug

[Webportal] Remove storage plugin command inject

---

docs/pai-management/doc/how-to-generate-cluster-config.md

There's no docker-tag in pai/examples/cluster-configuration/services-configuration.yaml but only docker-registry.tag. Correct the document to make it clear that docker-registry.tag is the one to be modified.

Update docker-tag to docker-registry.tag

---

src/device-plugin/config/device-plugin.yaml
src/device-plugin/deploy/device-plugin.yaml
src/device-plugin/deploy/start.sh.template
src/fluentd/deploy/fluentd.yaml.template
src/watchdog/test/data/no_condtion_pod.json

Upgrade deprecated k8s apiversion "extensions/v1beta1" to "apps/v1".
Reference: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Upgrade deprecated k8s apiversion

---

.github/workflows/continuous-integration.yml
src/kube-runtime/build/kube-runtime.dockerfile
src/kube-runtime/src/init
src/kube-runtime/src/init.d/user_command_render.py
src/kube-runtime/src/init.d/user_command_renderer.py
src/kube-runtime/test/render_test_secrets.yaml
src/kube-runtime/test/test_render_user_command.py
src/rest-server/src/config/paiConfig.js
src/rest-server/src/middlewares/v2/protocol.js
src/rest-server/src/models/kubernetes.js
src/rest-server/src/models/kubernetes/k8s-secret.js
src/rest-server/src/models/kubernetes/kubernetes.js
src/rest-server/src/models/token.js
src/rest-server/src/models/v2/job-attempt.js
src/rest-server/src/models/v2/job/index.js
src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/models/v2/virtual-cluster/k8s.js
src/rest-server/src/routes/kubernetes.js
src/rest-server/src/utils/frameworkConverter.js
src/rest-server/src/utils/manager/group/crudK8sSecret.js
src/rest-server/src/utils/manager/storage/crudK8sSecret.js
src/rest-server/src/utils/manager/user/crudK8sSecret.js
src/rest-server/src/utils/userSecret.js
src/rest-server/test/k8sModel.js
src/rest-server/test/v2/protocol.js

Pass secret from frontend to runtime.
**Changes:**
- Create k8s secret obj and mount it for init container
- User command will not concatenate with `&&`, change to concatenate with `\n`. Runtime will write user command to a file.
**Tested:**
- job w/ & w/o secret
- job w/ & w/o private docker auth

[Runtime, Rest-server] Pass secret from frontend to runtime

---

src/internal-storage/deploy/create.yaml.template
src/internal-storage/deploy/delete.yaml.template
src/internal-storage/deploy/service.yaml
src/postgresql/deploy/postgresql.yaml.template
src/postgresql/deploy/service.yaml

Currently internal storage and postgresql uses master-ip as host selector. It will not work if hostname != host_ip.

[BugFix] Update deploy-rules for internal storage and postgresql

---

src/kube-runtime/build/kube-runtime.k8s.dockerfile
src/kube-runtime/package_cache.md
src/kube-runtime/src/package_cache/package_cache_info
src/kube-runtime/src/package_cache/ubuntu_build.sh
src/kube-runtime/src/plugins/plugin_utils.py
src/kube-runtime/src/plugins/ssh/init.py
src/kube-runtime/src/plugins/ssh/sshd.sh
src/kube-runtime/src/plugins/teamwise_storage/storage_command_generator.py
src/kube-runtime/src/plugins/teamwise_storage/storage_helper.py
src/kube-runtime/src/runtime.d/install_group.sh
src/kube-runtime/test/test_runtime.py

To resolve: https://github.com/microsoft/pai/issues/4211
Docs: https://github.com/microsoft/pai/blob/zhiyuhe/package_cache/src/kube-runtime/package_cache.md

Add offline apt package cache in kube runtime 

---

src/rest-server/src/models/kubernetes/kubernetes.js
src/rest-server/src/models/v2/job/k8s.js

[Rest Server] Use list pods with label selector in getting job detail

---

src/kube-runtime/src/plugins/ssh/README.md
src/kube-runtime/src/plugins/ssh/init.py
src/kube-runtime/src/plugins/ssh/sshbarrier.sh
src/webportal/src/app/job-submission/models/protocol-schema.js

Make ssh barrier timeout configurable to avoid unexpected user job failure. The default timeout is 30 mins 
BTW: remove `sshbarriertaskroles`, since it's too complex
Fixes #4239

[runtime] Make ssh barrier timeout configurable

---

docs/setup-persistent-volumes-on-pai.md

To use Kubernetes volumes in PAI, **amdin** need to assign storage to PAI groups first. ->
To use Kubernetes volumes in PAI, admin need to assign storage to PAI groups first.

fix typo in docs/setup-persistent-volumes-on-pai.md 

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/models/v2/job/k8s.js

Add launched time for job.
Closes #4295.
Resolves #3249

[Rest Server] Add launched time for job

---

src/webportal/src/app/job-submission/utils/constants.js

Current default docker image list is outdated: the latest stable release of TensorFlow and PyTorch is 2.1.0 and 1.4.0 now. And the version is not aligned: something like 2.0dev appears for TensorFlow.
This PR update the default image list to:
The images come from https://github.com/microsoft/pai/pull/4231 and have been tested.

Update default docker image list

---

src/dev-box/build/dev-box.common.dockerfile
src/pylon/build/pylon.common.dockerfile

- Fix Pylon building process. Change the url of openssl.
- Fix GitPython version to 2.x.x, due to that python2 is no longer supported in GitPython

[pylon] Update openssl-1.1.0f's url and fix GitPython version in dev-box

---

src/pylon/deploy/pylon-config/location.conf.template
src/rest-server/config/rest-server.yaml
src/rest-server/config/rest_server.py
src/rest-server/deploy/rest-server.yaml.template
src/rest-server/package.json
src/rest-server/src/config/express.js
src/rest-server/src/config/rate-limit.js
src/rest-server/src/routes/v2/job.js
src/rest-server/yarn.lock

Add rate limit for RESTful API, defaults to:
* 600 requests per ip every 1 min
* 60 list job requests per user every 1 min
* 60 submit job requests per user every 1 hour

[Hotfix] Add rate limit for RESTful API (#4418)

---

src/rest-server/docs/swagger.yaml

Our current API version (now `0.16.0` is set by release version). However, it is confusing since we prefix APIs by `v2`. I want to change the API version to `2.0.0`, which will be decoupled with the release version. 
Then the policy of version updating could be 
- hot fixes (e.g. fixing typo, correcting formatting) will update `patch` version (e.g. `2.0.0` to `2.0.1`)
- non-breaking API changes (e.g. adding new api, supporting new params in an existing api) will update `minor` version (e.g. `2.0.0` to `2.1.0`)
- big breaking changes will change the `major` version (e.g. `2.0.0` to `3.0.0`)

update api version to 2.0.0

---

src/webportal/src/app/job/job-view/fabric/job-detail/util.js

I just saw this typo when using PAI.

Fix typo in history API error message

---

src/pylon/deploy/pylon-config/nginx.conf.template
src/pylon/deploy/pylon-config/run.sh.template
src/pylon/deploy/pylon.yaml.template
src/pylon/deploy/start.sh.template

When ssl is configured in pylon configuration, ssl server in nginx will be enabled. After this PR, pylon will support ssl in basic mode.

[pylon] support nginx ssl in basic mode.  

---

RELEASE_NOTE.md
RELEASE_NOTE_zh_CN.md

- AAD Support
- mapping between AAD groups and VCs #3275
- End-to-End AAD test cases #3362 
- Introduce kubespray to deploy clusters #3757
- Kubernetes Deployment, GPU drivers installation, Nvidia docker runtime #3757 #3842 #3873
- Add new worker node #3846
- Clean up cluster environment where OpenPAI is deployed before #3879 #3883
- Ansible playbooks to uninstall GPU drivers installed by apt #3899 
- Framework Controller 
- Deployment #3435
- Foreground stop all frameworks #3664
- [hivedscheduler](https://github.com/microsoft/hivedscheduler) provides a Kubernetes Scheduler Extender for multi-tenant GPU clusters.
- Hived scheduler deployment #3495, #3579
- Hived as the default k8s scheduler #3599
- Job Near FIFO scheduling #3726, #3731
- Expose LazyPreemptionStatus #3917
- Disable leader …

add release note

---

contrib/kubespray/script/service-boot.sh
src/dev-box/build/dev-box.common.dockerfile
src/device-plugin/deploy/start.sh.template

Update device plugin yaml download script, use svn client instead.

[Hotfix] Update device plugin yaml download script (#4563)

---

contrib/kubespray/environment-check.yml
contrib/kubespray/quick-start-kubespray.sh
contrib/kubespray/requirement.sh
contrib/kubespray/roles/kubectl/tasks/main.yml
contrib/kubespray/roles/requirement/devbox/tasks/ubuntu.yml
contrib/kubespray/roles/requirement/infra/tasks/resource.yml
contrib/kubespray/roles/requirement/infra/tasks/ubuntu-docker.yml
contrib/kubespray/roles/requirement/infra/tasks/ubuntu.yml
contrib/kubespray/roles/requirement/worker/tasks/resource.yml
contrib/kubespray/roles/requirement/worker/tasks/ubuntu-docker.yml
contrib/kubespray/roles/requirement/worker/tasks/ubuntu-nvidia.yml
contrib/kubespray/roles/requirement/worker/tasks/ubuntu.yml

This PR includes:
1. Now the check script will go through all of the check list. The script will fail at end if any error detected.
User can choose to proceed regardless of the error (Because sometimes he has overrided some configuration, such as the image repo). See the following picuture for details.
2. Remove check for githubusercontent.com because it is not required. See: #4563 
3. Fix a typo to when install kubectl (google -> aliyun)

[Kubespray] make requirement check not to fail immediately

---

contrib/kubespray/quick-start/services-configuration.yaml.template

Remove default webportal plugins in quick start.
`gerhut.github.io/store` is retired now. /cc @gerhut
Closes #4579.

Remove default webportal plugins in quick start

---

src/rest-server/docs/swagger.yaml

Fix incorrect query for `/api/v2/jobs` in api docs.

[Docs] Fix incorrect query in api docs

---

src/dev-box/build/dev-box.common.dockerfile

According to https://setuptools.readthedocs.io/en/latest/python%202%20sunset.html, Python2 is not supported by setuptools. This PR pins setuptools version to lower than 45.

Fix setuptools version in dev-box

---

src/storage-manager/deploy/storage-manager.yaml.template

Before this change. The storage manager QOS class is BestEffort. When the node occur some condition, such as memory pressure/disk pressure.  This pod will be evicted first.
Change to Burstable QOS class to avoid such evict.

change storage manager QOS class from BestEffort to Burstable

---

src/rest-server/src/controllers/v2/storage.js

Fix call `/api/v2/storages?default=false` will even only get default storages.

[Rest Server] Fix default parameter of list storages API

---

src/cluster-configuration/deploy/start.sh.template
src/dev-box/build/dev-box.common.dockerfile

If the node number reach to thousands, label node one by one cost too much time. Handling it with parallel will save a lot of time.
Ref: https://stackoverflow.com/a/24961201/8589683
Tested it with 1000 node.

Handle node label with parallel

---

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role.jsx

Add task debug info in job detail page [webportal]

---

contrib/kubespray/environment-check.yml
contrib/kubespray/roles/requirement/devbox/defaults/main.yml
contrib/kubespray/roles/requirement/devbox/tasks/ubuntu.yml
contrib/kubespray/roles/requirement/infra/defaults/main.yml
contrib/kubespray/roles/requirement/infra/tasks/ubuntu.yml
contrib/kubespray/roles/requirement/worker/defaults/main.yml
contrib/kubespray/roles/requirement/worker/tasks/ubuntu-docker.yml
contrib/kubespray/roles/requirement/worker/tasks/ubuntu.yml

- Fix default runtime check issue:  https://github.com/microsoft/pai/issues/4564
- When user replace docker.io or fcr.io, check the corresponding repo instead of the original. https://github.com/microsoft/pai/issues/4675
- Get devbox ip from hostvars[inventory_hostname]['ansible_default_ipv4']['address'] instead of eth0 https://github.com/microsoft/pai/issues/4675

A fix for kubespray environment check

---

src/log-manager/deploy/log-manager.yaml.template
src/log-manager/src/logrotate/logrotate.conf

1. Change log-manager QoS class to Burstable
2. Auto rotate the log file which size more than 300M
3. The rotated log will keep no more than 30 days

[log-manager] reconfigure log-manager

---

src/pylon/deploy/pylon-config/nginx.conf.template

Use status code 307 to redirect http to https to keep request method and body.
Closes #4685.

[Pylon] Use status code 307 to redirect http to https

---

src/pylon/deploy/pylon-config/nginx.conf.template

Use status code 307 to redirect http to https to keep request method and body.

[Hotfix] Use status code 307 to redirect http to https (#4714)

---

src/dev-box/build/dev-box.common.dockerfile

In dev-box, `dnspython` package is needed by `etcd`. According to https://www.dnspython.org/, dnspython released a 2.0.0 version which doesn't support python2. We should freeze its version to `v1.16.0`, otherwise `paictl` will fail with the following error:

Freeze dnspython version in dev-box

---

src/cluster-configuration/deploy/start.sh.template

Currently, if the node labeling fails, the cluster-configuration will still be considered as a successful deployment. It will cause some problem in the future e.g. the storage manger will hang forever waiting for a node with `pai-storage` label.

Fail the script in cluster-configuration service if node is not correctly labeled

---

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml

For regex, `s` means `single line mode` which will treat all logs as a single line.
So if pattern contains `.*` at the end of pattern, it will match all logs to the end of log file.
This will cause matching string in exitInfo contains too much logs and confuse end user.
Change to only use multi-line mode in this case

refine exit spec

---

src/log-manager/deploy/log-manager.yaml.template
src/log-manager/src/logrotate/docker-entrypoint.sh
src/log-manager/src/logrotate/logrotate.conf
src/webportal/src/app/job/job-view/fabric/job-detail/conn.js

We only rotate the log if log size is more than 100MB. Max keep 2 logs, if user still write log, the old log will be dropped.
log-rotate will run every 10 mins

Change logrotate config

---

src/cluster-configuration/deploy/priority-class.yaml
src/cluster-configuration/deploy/start.sh.template
src/cluster-configuration/deploy/stop.sh.template
src/job-exporter/deploy/job-exporter.yaml.template
src/log-manager/deploy/log-manager.yaml.template
src/node-exporter/deploy/node-exporter.yaml.template

Assign PAI daemon with high priority. Make sure PAI service will not be evicted before user pod.
According to: https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods
The kubelet ranks Pods for eviction first by resource, then by priority.
We already changed pai daemon service QoS class to Burstable and make sure it will not exceed the limit resource.

make pai daemon with high priority

---

src/log-manager/deploy/log-manager.yaml.template
src/log-manager/src/logrotate/docker-entrypoint.sh

Currently we use cron job to run log-rotate. There will be multiple log-rotate instances if the log-rotate process takes long time to finish. In this case, many host resource will be consumed. 
Add checker before run log-rotate & limit the cpu

avoid run multiple log-rotate instances

---

src/rest-server/src/config/v2/hived.js
src/rest-server/src/middlewares/v2/hived.js
src/webportal/deploy/webportal.yaml.template
src/webportal/src/app/env.js.template
src/webportal/src/app/job-submission/components/context.jsx
src/webportal/src/app/job-submission/components/hived-sku-section.jsx
src/webportal/src/app/job-submission/components/tab-form-content.jsx
src/webportal/src/app/job-submission/job-submission-page.jsx
src/webportal/src/app/job-submission/models/job-protocol.js
src/webportal/src/app/job-submission/models/job-task-role.js
src/webportal/src/app/job-submission/utils/conn.js
src/webportal/src/app/job-submission/utils/constants.js
src/webportal/src/app/job-submission/utils/utils.js

Add sku count and sku type in submission form.

[Webportal] Add sku count and sku type in submission form

---

src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx
src/webportal/src/app/job/job-view/fabric/JobList/index.jsx

PR: #4854 Add table to job-list page during loading to show the columns.
But forgot to clear the old jobs, so the `loading` label will be place outside of the page.
This PR fix this bug:
1. Empty the items in the table during loading.
2. Set loading to false after catch error, to end the loading.

[Webportal] Fix loading in job list

---

src/log-manager/deploy/log-manager.yaml.template

Shrink log-manager requests resources. 
Since it's in idle state in most of time.

[log-manager] recalculate log-manager resource usage

---

contrib/kubespray/example/config.yml
contrib/kubespray/quick-start/services-configuration.yaml.template
contrib/kubespray/script/openpai-generator.py
src/log-manager/deploy/log-manager.yaml.template

When qos-switch set to true, PAI daemon will requests addition resources.
Take PAI service resources into account when calculate hived config

[quick-start] Update hived config for quick-start

---

src/rest-server/src/utils/frameworkConverter.js

When ```podCompletionStatus.containers``` is null, an error will occur in rest-server.
closes #4769

Fix exitDiagnostic bug when containers is null

---

src/webportal/src/app/job-submission/models/job-protocol.js

Fix additional fields regression issue in HiveD config on webportal submission form.

Fix additional fields regression in HiveD config

---

src/webportal/src/app/job-submission/models/job-task-role.js

Use GPU number as SKU number when import config.
Workaround for #4881.

[Webportal] Use GPU number as SKU number when import config

---

src/fluentd/deploy/fluentd-config.yaml.template
src/fluentd/src/fluent-plugin-pgjson/lib/fluent/plugin/out_pgjson.rb

fix wrong framework retry records 

---

src/rest-server/src/controllers/v2/cluster.js
src/webportal/src/app/job-submission/job-submission-page.jsx
src/webportal/src/app/job-submission/utils/conn.js

Support dynamic sku types for different virtual clusters on webportal.

[Webportal] Support dynamic sku types for different vc

---

src/database-controller/sdk/index.js
src/database-controller/sdk/package.json
src/database-controller/src/initializer/index.js
src/rest-server/docs/swagger.yaml
src/rest-server/src/controllers/v2/job.js
src/rest-server/src/middlewares/v2/protocol.js
src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/routes/v2/job.js

- getJobList : filter by tag 
- getJobDetails : with tag info
- tag : put / delete

add job tag table; add tag field to list/get job api

---

src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template
src/job-exporter/src/collector.py

- Remove deprecated service from grafana
- Add new services to monitor, include (FC, db-controller, hived, DShuttle, log-manager)

Update PAI service metrics

---

src/database-controller/config/database-controller.yaml
src/database-controller/deploy/database-controller.yaml.template
src/database-controller/sdk/index.js
src/database-controller/src/common/init.js
src/database-controller/src/common/k8s.js
src/database-controller/src/package.json
src/database-controller/src/watcher/cluster-event/config.js
src/database-controller/src/watcher/cluster-event/index.js
src/database-controller/src/watcher/framework/index.js
src/database-controller/src/yarn.lock

database size control strategy:
- In event watcher, check the disk usage in the beginning. If the disk usage > 80%, stop the event watcher and exit with a non-zero code.
- The disk check also happens  every 60s. If the disk usage > 80%, stop the event watcher and exit with a non-zero code.
- `60s` and `80%` are configurable.
Problem found:
- If a job generates too many events, it will affect all other jobs.

[display event] add event watcher in database controller

---

src/webportal/config/webpack.common.js
src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
src/webportal/src/app/job/job-view/fabric/job-event.jsx
src/webportal/src/app/job/job-view/fabric/job-event/conn.js
src/webportal/src/app/job/job-view/fabric/job-event/job-event-list.jsx

1.  Add a link to job event page
2. Add a new job event page

Add job event page

---

src/webportal/src/app/home/home/virtual-cluster-statistics.jsx

Current version, the "granted group" in Admin's VC view didn't include the admin groups.
This PR will add all groups with the admin privilege to the "granted group" view.
Before:
After:

[Webportal] Add admin groups to vc's granted groups (Admin's user profile page)

---

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx

Webportal Font Solution:
1. FontClassNames (Use to custom text)
Different classname has [different default styles](https://github.com/microsoft/fluentui/blob/5158b5e405/packages/theme/src/fonts/createFontStyles.ts#L75). Incudes:
- [FontSize](https://github.com/microsoft/fluentui/blob/5158b5e405/packages/theme/src/fonts/FluentFonts.ts#L38)
- [FontWeight](https://github.com/microsoft/fluentui/blob/5158b5e405/packages/theme/src/fonts/FluentFonts.ts#L69)
- FontFamily: [A font map](https://github.com/microsoft/fluentui/blob/5158b5e405/packages/theme/src/fonts/createFontStyles.ts#L13) for different language with a fallback ```const FontFamilyFallbacks = `'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif`;```
2. [Text …

Restore job detail title font

---

src/alert-manager/deploy/alert-manager-deployment.yaml.template

- alert-handler is used only by alert-manager
- alert-manager is used by other services

allow alert-handler to be accessed only inside the pod

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/config/v2/execution-type.js
src/rest-server/src/config/v2/tag.js
src/rest-server/src/middlewares/v2/protocol.js
src/rest-server/src/routes/v2/job.js

Refine APIs `put/delete tag` , `put job/executionType`: 
-  return error when the request has content-type issue or body format issue

add validate body middleware in put/delete tag api & executionType api

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/config/v2/user.js
src/rest-server/src/controllers/v2/user.js
src/rest-server/src/middlewares/token.js
src/rest-server/src/routes/v2/user.js
src/rest-server/test/userManagement.js

This PR is for release v1.4. Needed for multi-cluster feature.
update users own profile API:
- support AAD mode
- suppport `extension` update
- Some code is refactored: `checkAdmin` should be a common logic in token check, while `checkSelf` should be controller specific since it relies on the request body.

update users's own profile: support AAD mode; update extension

---

src/rest-server/src/controllers/v2/group.js
src/rest-server/src/controllers/v2/job.js
src/rest-server/src/controllers/v2/user.js
src/rest-server/src/controllers/v2/virtual-cluster.js
src/rest-server/src/middlewares/token.js
src/rest-server/src/routes/kubernetes.js
src/rest-server/src/routes/v2/group.js
src/rest-server/src/routes/v2/job.js
src/rest-server/src/routes/v2/user.js
src/rest-server/src/routes/v2/virtual-cluster.js

- refactor with common middleware to avoid code duplication
- fix issues in `getGroupUserList` and `createGroup` function. The created error was not thrown immediately so the following code will be executed even when the auth check doesn't pass.

use checkAdmin middleware

---

contrib/kubespray/quick-start-kubespray.sh
contrib/kubespray/quick-start-service.sh
contrib/kubespray/script/configuration-kubespray.sh
contrib/kubespray/script/configuration-services.sh
contrib/kubespray/script/environment.sh
contrib/kubespray/script/service-boot.sh
docs/manual/cluster-admin/how-to-uninstall-openpai.md
docs/manual/cluster-admin/installation-guide.md
docs_zh_CN/manual/cluster-admin/installation-guide.md

Fix part of the deployment issues listed in #5001:
- move requirement check before configuration setting;
- move quick-start-config folder setting to quick-start-services.sh; 
- fix installation document branch checkout issue; change suggested version to v1.3.y;
- refine uninstallation doc
- fix git clone issue: clone to an existing folder may raise error, so the code pai/kubespray may be unsuccessfully cloned.

deployment process refine

---

src/webportal/src/app/job/job-view/fabric/job-transfer.jsx

Fix a bug when the window is too narrow.
Before fix:
After fix:

fix dropdown UI in job transfer

---

src/webportal/src/app/job/job-view/fabric/task-attempt/conn.js
src/webportal/src/app/job/job-view/fabric/task-attempt/task-attempt-list.jsx

The are some dup code under `task-attempt` and `job-detail`. Here just keep them synced, we need to refactor it later.

Change to new log API for task attempts

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job/k8s.js
src/rest-server/src/models/v2/job/log.js
src/rest-server/src/models/v2/task.js
src/rest-server/src/models/v2/utils/frameworkConverter.js
src/rest-server/src/routes/v2/job.js
src/rest-server/src/utils/error.d.ts

Change log API from  `/jobs/{job-name}/pods/podUid/logs` to 
`/jobs/{job-name}/taskRoles/{taskRoleName}/taskIndex/{taskIndex}/attempts/{taskAttemptId}/logs`
Previous, get log for each task attempt need to query DB: 
1. get job level info. 2. get job attempt level info 3. get task level info 4. get task attempt level info. 
After this change, only need to get task level info.

Get log for each attempt.

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/controllers/v2/group.js
src/rest-server/src/controllers/v2/user.js

Fix #5120 
- fix `updateGroupUserList` API issue
- refine unknown error message in group related APIs
- fix return code issue of `getGroupUserList` in swagger 
- fix return code issue of `getAllGroups` in swagger

fix updateGroupUserList api issue

---

src/alert-manager/build/alert-handler.common.dockerfile
src/alert-manager/deploy/alert-manager-configmap.yaml.template
src/alert-manager/deploy/alert-manager-deployment.yaml.template
src/alert-manager/src/alert-handler/controllers/mail.js

- Fix #5124 : webportal uri in alert-template not correct
- refine alert-handler:
- docker file: use ENTRYPOINT instead of CMD to avoid additional process creation 
- refine customized receivers render rules : not render non-available actions
- get username by split `job_name`, no need to query rest server

[alert-handler] use pylon https uri as webportal_uri

---

src/webportal/config/webpack.common.js

If have not` host: '0.0.0.0'`, ` yarn dev `-> the page `IP:9286` show not conneted.

make de webportal bind to all ip addresses

---

docs/manual/cluster-admin/how-to-add-and-remove-nodes.md

changes:
- remove node: no need to modify `hosts.yml`, as introduced in  [kubespray](https://github.com/kubernetes-sigs/kubespray/blob/release-2.11/docs/getting-started.md#remove-nodes)
- use `scale.yml`, `remove-node.yml` instead of `update-cluster.yml`
- `--limit` flag is no longer recommended in kubespray 2.11, we can use twice `-e` to specify the nodes to modify
Future refactor about using `layout.yaml` instead of `hosts.yaml` will be discussed separately.

Fix remove nodes doc issue

---

src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job/log.js
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
src/webportal/src/app/job/job-view/fabric/task-attempt/task-attempt-list.jsx

When calling `getTaskAttempts` API. The task attempt list returned and sorted by DESC order of attemptId. 
Previous code treat the list as ASC order and return wrong log content for retried task.
Fix this issue, as well as frontend bug.
Fix https://github.com/microsoft/pai/issues/5125

Fix bug: Get wrong log for retried task & frontend crash

---

src/webportal/src/app/job/job-view/fabric/job-detail.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/context.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-top.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-csv-exporter.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-filter.jsx

Add Search box, filter, and export csv feature to task detail list page.

[Webportal] Add filter, search box and export csv file in task detail list

---

contrib/kubespray/quick-start/services-configuration.yaml.template
contrib/kubespray/script/openpai-generator.py
contrib/kubespray/script/service-boot.sh

- generate hiveD config with `layout.yaml`
- generate one `vc` for each `machine-sku`, leave the first vc as the default vc
- get GPU resources from the resource specification in `layout.yaml`

generate hived config from layout.yaml

---

src/rest-server/src/controllers/v2/job.js
src/rest-server/src/models/v2/job/log.js
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
src/webportal/src/app/job/job-view/fabric/task-attempt/task-attempt-list.jsx

When calling getTaskAttempts API. The task attempt list returned and sorted by DESC order of attemptId.
Previous code treat the list as ASC order and return wrong log content for retried task.
Fix this issue, as well as frontend bug.

Fix bug: Get wrong log for retried task & frontend crash (#5177)

---

deployment/paiLibrary/paiService/service_management_delete.py
deployment/paiLibrary/paiService/service_management_refresh.py
deployment/paiLibrary/paiService/service_management_start.py
deployment/paiLibrary/paiService/service_management_stop.py
deployment/serviceCmd.py
docs/manual/cluster-admin/upgrade-guide.md

add skip-service-list arg

---

src/webportal/src/app/home/home.jsx
src/webportal/src/app/home/home/abnormal-job-list.jsx
src/webportal/src/app/home/home/recent-job-list.jsx

Refine pivot of home page

---

contrib/kubespray/quick-start/services-configuration.yaml.template

Current (master) vc name generation logic:
- name the first vc as default vc
- name the others with corresponding sku name
VC name has many constraints:
* it is used by [hiveD](https://github.com/microsoft/pai/blob/master/src/hivedscheduler/deploy/hivedscheduler.yaml.template#L65) to create a StateFulSet, the constraints is [DNS subdomain](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).
* it is used by to generate a group name, the constraint is : [rest-server](https://github.com/microsoft/pai/blob/master/src/rest-server/src/utils/manager/group/group.js#L23)
To follow these 2 conventions, only lowercase alphanumeric characters are allowed.
To avoid bringing these constraints to the naming of `sku`, we should not generate `vc` name with sku …

use vc{index} as vc name instead of sku name

---

contrib/kubespray/quick-start-service.sh
contrib/kubespray/script/start-service-in-dev-box.sh

Fix the second issue in #5231 
The generation of hived config relies on k8s api & kubeconfig may not be correctly set on the dev-box machine. So this should be done in the container.

fix kubeconfig issue

---

docs/manual/cluster-admin/troubleshooting.md
src/job-exporter/src/collector.py
src/job-exporter/src/nvidia.py
src/job-exporter/test/test_collector.py
src/job-exporter/test/test_nvidia.py
src/prometheus/deploy/alerting/gpu.rules

GPU may drop into low perf state in some case. Which cause user workload run much slower. Add this alert. Fix: #3387

add alert for GPU low perf state

---

src/rest-server/src/routes/token.js

Add `GET /api/v2/tokens/check` API for OpenPAI client to verify token.
Currently only Marketplace will use it.
Just for internal use, didn't add to swagger.

[Rest-Server] Add tokens check API for client

---

contrib/kubespray/config/config.yaml
contrib/kubespray/quick-start/services-configuration.yaml.template
deployment/quick-start/services-configuration.yaml.template
src/marketplace-restserver/config/marketplace-restserver.yaml
src/marketplace-restserver/deploy/marketplace-restserver.yaml.template
src/marketplace-restserver/deploy/service.yaml
src/marketplace-webportal/config/marketplace_webportal.py
src/marketplace-webportal/deploy/marketplace-webportal.yaml.template
src/marketplace-webportal/deploy/service.yaml
src/webportal/config/webportal.py
src/webportal/config/webportal.yaml
src/webportal/deploy/webportal.yaml.template

1. Admin can deploy marketplace in PAI quick start script (set enable_marketplace: true in config.yaml)
2. Simplify marketplace settings (only need to set `cluster.common.marketplace = "true"`
3. Add prerequisite to marketplace-webportal (require marketplace-restserver) and marketplace-restserver (require marketplace-db)
4. Will auto add marketplace to webportal-plugins if set `cluster.common.marketplace = "true"`
Related issue & test cases: https://github.com/microsoft/openpaimarketplace/issues/209#issue-799930634

[Marketplace] Simplify marketplace setting

---

src/database-controller/src/common/framework.js
src/database-controller/src/package.json
src/database-controller/src/poller/index.js
src/database-controller/src/poller/utils.js
src/database-controller/src/yarn.lock
src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml

to fix https://github.com/microsoft/pai/issues/4889

make DBController tolerant to wrong framework request

---

src/database-controller/config/database-controller.yaml
src/database-controller/deploy/database-controller.yaml.template
src/database-controller/src/watcher/cluster-event/config.js
src/database-controller/src/watcher/cluster-event/index.js
src/database-controller/src/watcher/framework/config.js
src/database-controller/src/watcher/framework/index.js

Fix database controller memory leak

---

contrib/kubespray/quick-start-kubespray.sh
contrib/kubespray/quick-start-service.sh
docs/manual/cluster-admin/installation-guide.md
docs_zh_CN/manual/cluster-admin/installation-guide.md

Do not display "ok" and "skipped" tasks except for verbose mode.

Reduce ansible logs when deploy

---

src/cluster-configuration/deploy/gpu-configuration/gpu-configuration.json.template

`nodename` is no longer required, but `hostname` is.

fix gpu config generation issue

---

contrib/kubespray/quick-start-kubespray.sh

`DISPLAY_SKIPPED_HOSTS` option, environment variables without `ANSIBLE_` prefix are deprecated , use the `ANSIBLE_DISPLAY_SKIPPED_HOSTS` environment variable instead.

quick fix deprecated env variables warning

---

src/internal-storage/build/internal-storage-barrier.k8s.dockerfile
src/internal-storage/src/barrier.sh
src/postgresql/deploy/postgresql.yaml.template

Add an internal storage barrier to postgresql

---

src/alert-manager/src/cluster-utilization/send_alert.py

The job list should be filtered by completed time, we will fix this after the support in rest api #5347.

[cluster-utilization] change the get jobs limit to 50000

---

contrib/kubespray/roles/requirement/computing-devices/nvidia.com_gpu/tasks/main.yml

Sometime `nvidia_gpu_count.stdout_lines` is `["<num>"]`, but sometimes it becomes `["", "<num>"]`.
Use `|join("")|trim` to unify them.

Fix wrong nvidia gpu card number 

---

contrib/kubespray/script/environment.sh
src/dev-box/build/dev-box.common.dockerfile

`https://bootstrap.pypa.io/get-pip.py` is updated and doesn't support python3.5 anymore.

Fix get-pip.py compatibility problem with Python3.5

---

src/rest-server/docs/swagger.yaml
src/rest-server/src/controllers/v2/job.js

Support sorting by completionTime

---

contrib/kubespray/quick-start/services-configuration.yaml.template
src/alert-manager/src/cluster-utilization/send_alert.py

Sorting by completionTime is supported in #5375, we can thus get the whole list of jobs within 7 days

[cluster utilization] get the full list of jobs in 7 days

---

src/alert-manager/deploy/alert-templates/kill-low-efficiency-job-alert/html.ejs

After this change, the template can also be applied for killing long-running jobs

refine kill low-efficiency-job-alert email templates

---

src/webportal/deploy/webportal.yaml.template
src/webportal/src/app/env.js.template
src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
src/webportal/src/app/job/job-view/fabric/task-attempt/conn.js
src/webportal/src/app/job/job-view/fabric/task-attempt/task-attempt-list.jsx

Since we already unified log api in rest-server. We don't need log-type env any more.
Remove this env and unified the experience

web change to support general log type

---

src/webportal/src/app/layout/components/sidebar.jsx

Bug from Marketplace
In `create item` or other subpage of marketplace, click the sidebar item will not navigation to he marketplace home page.
this PR will fix it.

[Plugins] Make sure click plugin item back to the plugin's home page 

---

docs/manual/cluster-admin/how-to-use-alert-system.md
src/alert-manager/src/cert-expiration-checker/send_alert.py

Add `"status": "firing"` to the alert.
So the alert will be shown on the webportal home page.

[Alert manager] Add firing status to the cert expiration checker alert

---

docs/manual/cluster-admin/how-to-use-alert-system.md
src/alert-manager/src/cert-expiration-checker/send_alert.py

Add `"status": "firing"` to the alert.
So the alert will be shown on the webportal home page.

[Cherry-pick][Alert manager] Add firing status to the cert expiration checker alert 

---

src/alert-manager/deploy/alert-manager-deployment.yaml.template

If docker use ono-private ip. There will be error: `alertmanager: no private IP found`.
Set `cluster.advertise-address` to avoid this issue

set cluster.advertise-address to avoid docker use non-private ip

---

src/alert-manager/config/alert-manager.yaml
src/alert-manager/config/alert_manager.py

The actions with no dependencies should be placed in `alert-manager.yaml`
This bug was involved in #5383

fix alert-manager config generation issue

---

contrib/kubespray/roles/docker-cache/install/files/add_docker_cache_config.py

Fix update docker cache error: [issue comment](https://github.com/microsoft/pai/issues/5445#issuecomment-826238676).
If /etc/docker/daemon.json doesn't exist or is an empty file, the script will fail.

Fix update docker cache error

---

src/prometheus-pushgateway/src/metrics-cleaner/main.py

Some metrics were accidently deleted because job["push_failure_time_seconds"]["time_stamp"] may different from other timestamps

Fix metrics cleaner get timestamp issue

---

src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-jobview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskroleview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-tasks-in-node-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskview-dashboard.json.template

- change `rate` to `irate`
- change interval to 60s

Use `irate` instead of `rate` in PromQL for fast-moving metrics

---

contrib/kubespray/script/service-boot.sh

fix this [issue comment](https://github.com/microsoft/pai/issues/5445#issuecomment-827309308)
This is because kubectl is not installed on the host by default.

fix blank WEBPORTAL_URL

---

src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-jobview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskroleview-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-tasks-in-node-dashboard.json.template
src/grafana/deploy/grafana-configuration/pai-taskview-dashboard.json.template

- support more metrics, including
- node_memory_bytes with `type` label
- node_disk_other_bytes_total, task_block_other_byte
- get task cpu utilization with `task_cpu_seconds_total`
- task_network_receive_bytes_total, task_network_transmit_bytes_total
- avoid wrongly computed 100% cpu utilization by using `idelta`
- use `irate` instead of `rate` for fast-moving metrics & change the computing interval
- set `editable` as true in all the dashboards

extend grafana config to fit more metrics

---

.github/workflows/continuous-integration.yml
subprojects/frameworklauncher/yarn/pom.xml

Remove log4j from `frameworklauncher`.
Framework launcher is not be used in pure k8s version and it uses log4j which has high security issue.
Remove this log4j dependency to fix security issue

remove log4j dependency from frameworklauncher

---

src/alert-manager/src/cluster-utilization/send_alert.py

fix #5654 
Because alerts[indexofusage]["annotations"] is null, webportal cannot parse the item correctly.
Signed-off-by: siaimes <34199488+siaimes@users.noreply.github.com>

Because alerts[indexofusage]["annotations"] is null, webportal cannot parse the item correctly.
