frameworklauncher/doc/USERMANUAL.md, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/AntiaffinityAllocationManager.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/ApplicationMaster.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/GpuAllocationManager.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/RequestManager.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/LauncherClientInternal.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/WebStructure.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/ClusterConfiguration.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/FrameworkDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/HealthCheckDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/NodeConfiguration.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/ParentFrameworkDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/PlatformSpecificParametersDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/ResourceDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/RetryPolicyDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskRoleDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskRolePlatformSpecificParametersDescriptor.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/webserver/LauncherModule.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/webserver/RequestManager.java, frameworklauncher/src/test/java/com/microsoft/frameworklauncher/applicationmaster/GpuAllocationManagerTest.java
1. Support ClusterConfiguration to help AM scheduling
2. Support TaskRole Override
3. Prevent null for field has default value
=> [Launcher]: Support ClusterConfiguration to help AM scheduling

service-deployment/bootstrap/cluster-configuration/host-configuration/host-configuration.yaml.template
Hi Yanjie,
How to use this host-configuration, pls refer this link: [host-configuration](https://github.com/Microsoft/pai/blob/master/service-deployment/bootstrap/hadoop-service/hadoop-node-manager.yaml.template#L90)
=> Add all tag infomation to host-configuration.

service-deployment/bootstrap/cleaning/cleaning.yaml.template, service-deployment/bootstrap/frameworklauncher/frameworklauncher.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-data-node.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-name-node.yaml.template, service-deployment/bootstrap/hadoop-service/zookeeper.yaml.template, service-deployment/clusterconfig-example.yaml, service-deployment/src/cleaning-image/start.sh
Change the default /mnt as a template parameter  dataPath in clusterconfig.
=> Make datafolder as a template parameter

kubernetes-deployment/README.md, kubernetes-deployment/bootstrap.py, kubernetes-deployment/cluster-config-example.yaml
Add an function to cleanup whole cluster in a centralized method.
=> Kubernetes issue f ix

kubernetes-deployment/bootstrap.py, kubernetes-deployment/cleanup.sh, kubernetes-deployment/cluster-config-example.yaml, kubernetes-deployment/start.sh
Create kube-proxy in the dev-box. And remove the tricky way in startup.sh.
=> Kube proxy create

rest-server/src/config/express.js, webportal/src/app/job/job-submit/job-submit.component.js, webportal/src/app/job/job-view/job-view.component.js, webportal/src/app/user/user-login/user-login.component.js
Add version in RESTful API. Update webportal ajax link accordingly.
=> Add version in RESTful API

service-deployment/bootstrap/hadoop-service/hadoop-configuration/resourcemanager-generate-script.sh, service-deployment/bootstrap/hadoop-service/hadoop-data-node.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-jobhistory.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-name-node.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-node-manager.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-resource-manager.yaml.template, service-deployment/bootstrap/hadoop-service/start.sh, service-deployment/bootstrap/hadoop-service/zookeeper.yaml.template, service-deployment/src/hadoop-run/start.sh, service-deployment/src/zookeeper/dockerfile.template, service-deployment/src/zookeeper/run.sh
When deploying hadoop service， wait until deployment finished.
=> Hadoop service dependency

service-deployment/bootstrap/rest-server/rest-server.yaml.template, service-deployment/clusterconfig-example.yaml
Save authentication database to host file system.
=> Save authentication database to host file system

rest-server/src/config/launcher.js, rest-server/src/models/job.js
Add framework launcher health check. Solve service dependencies for rest
server.
Fix #96.
=> Solve service dependencies for rest server

kubernetes-deployment/bootstrap.py, kubernetes-deployment/cluster-config-example.yaml
Make ssh port configurable in k8s deployment.
=> Make ssh port configurable in k8s deployment

rest-server/src/config/launcher.js, rest-server/src/controllers/job.js, rest-server/src/models/job.js, rest-server/src/templates/dockerContainerScript.mustache
Add task details in response of GET job API.
=> Add task details in response of GET job

webportal/src/app/job/job-view/job-detail-table.component.ejs, webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.ejs, webportal/src/app/job/job-view/job-view.component.js, webportal/src/app/job/job-view/job-view.component.scss
=> Add job detail view page

webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.js
Add jobName parameter in job view page.
=> Add parameter in job view page

webportal/src/app/cluster-view/services/service-table.component.ejs, webportal/src/app/cluster-view/services/services.component.ejs, webportal/src/app/cluster-view/services/services.component.js
Add service view template, now it is an empty table waiting for data.
=> Add service view template

webportal/.gitignore, webportal/config/preprocess.js, webportal/package.json, webportal/src/app/job/job-submit/job-submit.component.ejs, webportal/yarn.lock
Add an example in job submit page.
=> [Webportal] Add an example in job submit page

job-tutorial/README.md, rest-server/src/config/job.js, rest-server/src/models/job.js
Support GPU type in job submission.
=> [Rest Server] Support GPU type in job submission

service-deployment/docker_build.py
1: refactor build and push script.
2: enable Single image build and push.
=> Single build and push

rest-server/src/models/user.js
=> [Rest Server] Fix issue in deployment

kubernetes-deployment/template/apiserver.yaml.template
Expose Kubernetes apiserver, fixes cross origin issue.
=> [Kubernetes Deployment] Expose Kubernetes apiserver

service-deployment/deploy.py
=> Single deploy and stop

kubernetes-deployment/start.sh
Comment host ip line in Kubernetes deployment.
=> [Kubernetes Deployment] Comment host ip line in deployment

service-deployment/README.md
introduce user to test their service with our new feature of single deploy and build
=> Update content in the chapter "Test your service"

service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template, service-deployment/bootstrap/prometheus/node-label.sh.template, service-deployment/clusterconfig-example.yaml, service-deployment/service.yaml
add node label for node-exporter[for issue 178]
=> add node label for node-exporter[for issue 178]

webportal/src/app/job/job-submit/job-submit.component.js
Check uploaded json in job submission.
Fixed #161.
=> [Webportal] Check uploaded json in job submission

webportal/package.json, webportal/yarn.lock
=> upgrade marked version

prometheus/exporter/gpu_exporter.go, service-deployment/src/gpu-exporter/start.sh.template
change duration to 30 seconds and configurable
=> refine the nvidia-smi query duration [fix]

tests/end_to_end/README.md, tests/end_to_end/install.sh, tests/end_to_end/start.sh, tests/end_to_end/test_hdfs.sh, tests/end_to_end/test_launcher.sh, tests/end_to_end/test_rest_server.sh, tests/end_to_end/test_service.sh, tests/end_to_end/utils.sh
Setup end to end test:
- Check pods status
- Check hdfs root path
- Check launcher webservice
- Check rest api
=> [Tests] Setup end to end test

service-deployment/bootstrap/webportal/webportal-ds.yaml.template, webportal/config/webportal.config.js, webportal/src/app/cluster-view/services/service-table.component.ejs, webportal/src/app/cluster-view/services/service-view.component.scss, webportal/src/app/cluster-view/services/services.component.js
- Disable Label click action
- Table row shows in one line
- Add link to nodename
- Add link to container log
=> update service view

kubernetes-deployment/README.md, kubernetes-deployment/bootstrap.py
1) Update kubernetes bootstrap script to enable the option that user could only install kubectl into their dev-box.
2) Update Readme.md
=> Kubectl install Option.

service-deployment/README.md
=> Fix An Issue in Readme.md

prometheus/exporter/gpu_exporter.go
refine the default path(which will be override by the entry), not affect current config
=> refine the default path, not affect current config

webportal/src/app/job/job-view/job-detail-table.component.ejs
=> [Webportal] Fix AppExitDiagnostics issue

rest-server/src/models/job.js, service-deployment/bootstrap/webportal/webportal-ds.yaml.template, webportal/src/app/job/job-view/job-detail-table.component.ejs, webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.js
Changes:
1) Correct retry count.
2) Convert framework states to 3 job states.
=> Refine job status returned by API

service-deployment/bootstrap/cleaning/cleaning.yaml.template, service-deployment/bootstrap/drivers/drivers.yaml.template, service-deployment/bootstrap/frameworklauncher/frameworklauncher.yaml.template, service-deployment/bootstrap/grafana/grafana.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-data-node.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-jobhistory.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-name-node.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-node-manager.yaml.template, service-deployment/bootstrap/hadoop-service/hadoop-resource-manager.yaml.template, service-deployment/bootstrap/hadoop-service/zookeeper.yaml.template, service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template, service-deployment/bootstrap/rest-server/rest-server.yaml.template, service-deployment/bootstrap/webportal/webportal-ds.yaml.template, service-deployment/clusterconfig-example.yaml, service-deployment/deploy.py, service-deployment/docker_build.py
1) Easy to manage image of different version
2) For future rolling-update and rolling-back.
=> Enable tag of docker image

webportal/config/webpack.common.js, webportal/src/app/cluster-view/hardware/hardware-detail.component.ejs, webportal/src/app/cluster-view/hardware/hardware-detail.component.js, webportal/src/app/cluster-view/hardware/hardware.component.ejs, webportal/src/app/cluster-view/hardware/hardware.component.js, webportal/src/app/job/breadcrumb/breadcrumb.component.ejs
=> Web portal: Add a new page to show hardware utilization detail for each node.

webportal/package.json, webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.ejs, webportal/src/app/job/job-view/job-view.component.js
New features:
- Better look-and-feel.
- Paging.
- Searching.
- Sorting.
- And the 'delete' button is also removed.
=> Web portal: apply the style of table in hardware page to job-view page

webportal/src/app/cluster-view/hardware/hardware.component.ejs, webportal/src/app/cluster-view/hardware/hardware.component.js, webportal/src/app/job/job-view/job-view.component.js, webportal/yarn.lock
Changes:
1. Hardware page: Use 'ip address' as the key of each row.
2. Solve the issue #215.
3. Update `yarn.lock` file.
=> Web portal: various improvements.

grafana/dashboards/gpu.js, service-deployment/src/grafana/pai-nodeview-dashboard.json.template
See http://10.151.40.179:3000/dashboard/script/gpu.js?orgId=1&host=10.151.40.138:9100&rows=4
=> update gpu utilization page

rest-server/src/templates/dockerContainerScript.mustache, rest-server/src/templates/yarnContainerScript.mustache
- Fix counting containers bug.
- Add logs in Docker container.
=> [Rest Server] Fix run time bugs in container

rest-server/src/controllers/token.js, webportal/config/webpack.common.js, webportal/src/app/layout/layout.component.ejs, webportal/src/app/layout/layout.component.js, webportal/src/app/user/user-auth/user-auth.component.js, webportal/src/app/user/user-login/user-login-nav.component.ejs, webportal/src/app/user/user-login/user-login.component.js, webportal/src/app/user/user-logout/user-logout.component.js
=> [Webportal] Protect user management

rest-server/src/templates/dockerContainerScript.mustache, rest-server/src/templates/yarnContainerScript.mustache
Rename tmp files in Docker container, add APP_ID as prefix to differentiate attempts with same job name.
=> [Rest Server] Rename tmp files in Docker container

kubernetes-deployment/bootstrap.py
Refactor code for future development
=> Refactor the k8s deployment code.

job-tutorial/README.md, rest-server/src/config/job.js
Add job name validation, only allow `^[a-zA-Z0-9._\-()]+$` format.
=> [Rest Server] Add job name validation

rest-server/src/templates/yarnContainerScript.mustache
Handle Docker image pulling failure.
Fixes #257.
=> [Rest Server] Handle Docker image pulling failure

kubernetes-deployment/README.md, kubernetes-deployment/bootstrap.py, kubernetes-deployment/node-list-example.yaml
incremental add machine and remove machine. (only support worker node)
=>  incremental maintenance (Add and remove a nodelist)

tests/end_to_end/install.sh, tests/end_to_end/start.sh
Fix token parsing bug in end to end tests.
=> [Tests] Fix token parsing bug in tests

kubernetes-deployment/bootstrap.py, service-deployment/deploy.py
Convert data types loaded from yaml config.
Fixes #248.
=> [Deployment] Convert data types loaded from yaml config

rest-server/README.md, rest-server/src/controllers/user.js
Allow user to change his own password.
=> [Rest Server] Allow user to change his own password

job-tutorial/README.md, job-tutorial/cntk/cntk-example.json, job-tutorial/cntk/cntk-example.sh, job-tutorial/tensorflow/tensorboard-example.json, job-tutorial/tensorflow/tensorflow-distributed-example.json, job-tutorial/tensorflow/tensorflow-example.json, rest-server/src/models/job.js, rest-server/src/templates/yarnContainerScript.mustache
Add example usage of PAI_DEFAULT_FS_URI, update tutorial accordingly.
=> [Examples] Add example usage of PAI_DEFAULT_FS_URI

rest-server/src/config/job.js, rest-server/src/templates/yarnContainerScript.mustache
- Update job name schema corresponding to #283.
- Update GPU bitmap in yarn container corresponding to #287.
=> [Rest Server] Changes corresponding to launcher

rest-server/src/config/launcher.js
Remove duplicate code in merge.
=> [Rest Server] Remove duplicate code in merge

rest-server/src/models/job.js
Allow non-hdfs output directory.
Fixes #306.
=> [Rest Server] Allow non-hdfs output directory

service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template
=> exporter [Fix]

kubernetes-deployment/Dockerfile, kubernetes-deployment/README.md
Prepare a docker environment to run the script of deploying kubernetes.
=> Prepare environment in docker to deploy kubernetes

tests/end_to_end/test_rest_server.sh
Add jobs cleanup in end to end test.
=> [Tests] Add jobs cleanup in end to end test

rest-server/src/templates/yarnContainerScript.mustache
=> Add label for cAdvisor

job-tutorial/README.md, job-tutorial/tensorflow/tensorflow-distributed-example.json, rest-server/src/config/job.js, rest-server/src/models/job.js, rest-server/src/templates/dockerContainerScript.mustache
- Update host list env variable, convert `PAI_TASK_ROLE_$i_HOST_LIST` to
`PAI_TASK_ROLE_$name_HOST_LIST`
- Add `PAI_TASK_ROLE_LIST`
=> [Rest Server] Update host list env variable

rest-server/src/models/job.js
Update GET jobs API, corresponding to #309.
=> [Rest Server] Update GET jobs API

service-deployment/bootstrap/prometheus/node-exporter-ds.yaml.template, service-deployment/clusterconfig-example.yaml
deploy cadvisor to collect container level metrics.
This deployment support get container label and container gpu metrics.
=> add cadvisor as exporter

webportal/.gitignore, webportal/src/app/cluster-view/services/service-info.js, webportal/src/app/cluster-view/services/service-table.component.ejs
Still needs more extensive testing.
=>  [web portal] [service view] pod button turns yellow if it is not ready.

rest-server/package.json, rest-server/src/config/index.js, rest-server/src/config/launcher.js, rest-server/test/healthcheck.js, rest-server/test/job.js, rest-server/test/setup.js
Setup unit test for rest server, use [Mocha](https://github.com/mochajs/mocha) for testing and [Chai](https://github.com/chaijs/chai) for Assertion.
=> [Tests] Setup unit test for rest server

.travis.yml
Setup continuous integration, add travis ci configuration.
=> [CI/CD] Setup continuous integration

kubernetes-deployment/bootstrap.py, kubernetes-deployment/sysconf/logging.yaml, kubernetes-deployment/test/test_bootstrap.py, kubernetes-deployment/test/test_logging.yaml, kubernetes-deployment/test/test_maintainlib_common.py, kubernetes-deployment/test/test_maintainlib_repair.py
=> Add logging module for k8s-dp

webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.js
In addition, the representation of the 'Duration' field is also improved. Now it's in `?d ?h ?m ?s` format.
=> [Web Portal] [Job View] Sort by StartTime in seconds

rest-server/src/models/job.js, tests/end_to_end/test_hdfs.sh
=> [Rest Server] Fix bugs

service-deployment/src/pylon/dockerfile
So that the log can be shown in k8s pod.
=> [Pylon] Link nginx log with k8s.

rest-server/test/job.js
Update unit test for rest server due to changes in #309 and #314.
=> [Tests] Update unit test for rest server

.travis.yml, rest-server/src/config/launcher.js, rest-server/src/controllers/job.js, rest-server/src/models/job.js, rest-server/test/jobConfig.js, rest-server/test/jobSshInfo.js, rest-server/test/jobSubmission.js, rest-server/test/setup.js
Fix bug:
- Job controller could not correctly handle errors and returned wrong results.
Unit test cases:
- 1 positive case.
- 4 negative cases.
In addition, some other parts of the code are also changed to make all above changes work.
=> [REST Server] [Job Submit] Fix bug and add unit test cases

rest-server/README.md, rest-server/src/controllers/job.js, rest-server/src/routes/job.js, rest-server/test/jobSubmission.js
Refine job submission api, use POST `/api/v1/jobs`.
=> [Rest Server]  Refine job submission api

.travis.yml, README.md, rest-server/package.json
Add test coverage in rest server.
=> [CI/CD] Add test coverage

job-tutorial/README.md, rest-server/src/config/job.js, rest-server/src/models/job.js, rest-server/src/templates/dockerContainerScript.mustache, rest-server/src/templates/yarnContainerScript.mustache
Support port resources in rest server.
=> [Rest Server] Support port resources in rest server

webportal/src/app/cluster-view/hardware/hardware.component.ejs, webportal/src/app/cluster-view/services/services.component.ejs, webportal/src/app/job/job-view/job-detail-table.component.ejs, webportal/src/app/job/job-view/job-table.component.ejs, webportal/src/app/job/job-view/job-view.component.js
Features:
- New layout of job details view.
- Add the link to the job metrics (Grafana) page.
Screenshot:
=> [Web Portal] Refine job details view

rest-server/src/models/job.js
Fix bug in port resources config.
=> [Rest Server] Fix bug in port resources config

hadoop-ai/hadoop-build/build.sh
Update hadoop version to enable port in hadoop. 
fix a tinny issue in hadoop path
=> update hadoop version

hadoop-ai/hadoop-build/build.sh
=> Fixhadoopversion

prometheus/exporter/gpu_exporter.py
currently add local test pass code.
docker build will add later.
after add docker build and test will remove go version.
=> add python gpu exporter

service-deployment/bootstrap/webportal/webportal-ds.yaml.template, service-deployment/clusterconfig-example.yaml, webportal/config/webportal.config.js, webportal/src/app/vc/vc.component.ejs, webportal/src/app/vc/vc.component.js
=> [VC] Refine vc view; add yarn link to each vc entry.

prometheus/exporter/docker_stats.py
parse docker stats cmd and extract the info for later job exporter to use
=> add parse docker stats to support job exporter

prometheus/exporter/docker_inspect.py
parse docker labels then used at job metrics exporter
=> add docker inspect cmd result parse

prometheus/exporter/gpu_exporter.py, prometheus/exporter/job_exporter.py
Goal: add job exporter.
Intro: Join gpu, docker stats, docker inspect metrics to generate metrics file.
Note: Will change the label name after https://github.com/Microsoft/pai/pull/429 merge.
=> add job exporter

rest-server/src/templates/yarnContainerScript.mustache
Add label for gpu in docker container.
=> [Rest Server] Add label for gpu in docker container

utilities/release.sh
=> [Utilities] Add release script

rest-server/README.md, rest-server/src/controllers/job.js, rest-server/src/models/job.js, rest-server/test/jobExecutionType.js
=> [Rest Server] Allow admin execute all jobs

prometheus/exporter/gpu_exporter.py, prometheus/exporter/job_exporter.py
for server no gpu or nvidia-smi not work case
- Nvidia-smi error, will only generate job metrics file
- Nvidia-smi live, will generate job & gpu metrics files
=> Fix: not throw nvidia-smi exception

service-deployment/bootstrap/grafana/grafana-configuration/pai-jobview-dashboard.json.template, service-deployment/bootstrap/grafana/grafana-configuration/pai-taskroleview-dashboard.json.template, service-deployment/bootstrap/grafana/grafana-configuration/pai-taskview-dashboard.json.template
- disk & network metrics from b to rate b/s
- refine the column & title
=> Fix: refine disk usage metrics of job metrics pages

rest-server/src/controllers/job.js, rest-server/src/models/job.js
=> [Rest Server] Save original submitted json

job-tutorial/README.md, rest-server/src/config/job.js
Update task role name regex to fix env export issue.
=> [Rest Server] Update task role name regex to fix env export issue

rest-server/src/config/job.js, rest-server/src/models/job.js
Add default http and ssh port.
=> [Rest Server] Add default http and ssh port

rest-server/src/models/job.js
=> [Rest Server] Fix PAI_DEFAULT_FS_URI issue

webportal/src/app/layout/layout.component.ejs, webportal/src/app/layout/layout.component.js, webportal/src/app/user/user-register/user-register.component.js
Features:
- Layout refinement: Put 'User Management', 'Hardware', 'Services', and 'K8s Dashboard' pages into 'Administration' section.
- Access control: Only admin users can see this section.
=> [Web Portal] The 'Administration' menu section

frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/ApplicationMaster.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/model/TaskStatus.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/utils/ValueRangeUtils.java, frameworklauncher/src/test/java/com/microsoft/frameworklauncher/common/utils/ValueRangeUtilsTest.java
=> Hotfix port assignment bug

job-tutorial/README.md
=> Revert "reset killAllOnCompletedTaskNumber to 1 in ReadMe"

pai-management/bootstrap/end-to-end-test/end-to-end-test.yaml.template
=> Remove duplicate value

pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template
cherry pick to master PR https://github.com/Microsoft/pai/pull/548
=> [hot fix]fix exporter path for branch 0.4.y

pai-management/k8sPaiLibrary/template/kubelet.sh.template
Enable swap in kubelet. Fixes #450.
=> Enable swap in kubelet

example/pytorch.md, example/pytorch/Dockerfile.example.pytorch, example/pytorch/README.md, example/pytorch/pytorch.mnist.json, example/pytorch/pytorch.regression.json
Add PyTorch Example. View at [pytorch/README.md](https://github.com/Microsoft/pai/blob/xiongyf/pytorch-example/example/pytorch/README.md).
=> [Examples] Add PyTorch Example

example/mxnet/Dockerfile.example.mxnet, example/mxnet/README.md, example/mxnet/mxnet.autoencoder.json, example/mxnet/mxnet.image-classification.json
=> [Examples] Add MXNet example

example/scikit-learn/Dockerfile.example.sklearn, example/scikit-learn/README.md, example/scikit-learn/sklearn.mnist.json, example/scikit-learn/sklearn.text-vectorizers.json
=> [Examples] Add scikit-learn example

pai-management/cleanup-service.py, pai-management/service_dependency_solve.py
=> fix please spell

pai-management/cleanup-service.py, pai-management/service_dependency_solve.py
merge webportal hot fix to master
=> merge webportal hot fix to master

rest-server/src/models/job.js
Enable fancy retry policy for framework and set max retry count.
Fixes #637.
=> [Rest Server] Enable fancy retry policy for framework

rest-server/src/middlewares/job.js, rest-server/src/middlewares/parameter.js, rest-server/src/routes/job.js, rest-server/test/jobSubmission.js
Check killAllOnCompletedTaskNumber in configuration.
Fixes #622
=> [Rest Server] Check killAllOnCompletedTaskNumber in configuration

prometheus/exporter/watchdog.py
also increase watchdog log file max size
=> add k8s console log show watchdog log path

cluster-configuration/cluster-configuration.yaml
One simple error that will cause a interrupt in deployment process.
=> machinetype to machine-type

pai-management/k8sPaiLibrary/maintainlib/common.py
=> Revert "Write password in stdin when ssh due to the need of sudo. And workaro…"

pai-management/doc/cluster-bootup.md
@hwuu , 
We should use 'paictl.py cluster k8s-bootup ...' cmd.
=> update doc: action start-kubernetes renamed

pai-management/bootstrap/hadoop-service/hadoop-data-node.yaml.template, pai-management/bootstrap/hadoop-service/hadoop-name-node.yaml.template, pai-management/bootstrap/hadoop-service/hadoop-node-manager.yaml.template, pai-management/bootstrap/hadoop-service/hadoop-resource-manager.yaml.template, pai-management/bootstrap/hadoop-service/node-label.sh.template, pai-management/bootstrap/hadoop-service/refrash.sh.template, pai-management/bootstrap/hadoop-service/start.sh, pai-management/bootstrap/hadoop-service/stop.sh.template, pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py
hadoop-name-node: hadoop-name-node="true"
hadoop-data-node: hadoop-data-node="true"
hadoop-resource-manager: hadoop-resource-manager="true"
hadoop-node-manager: hadoop-node-manager="true"
=> Change the label of hadoop-service

prometheus/exporter/healthy_check.py
rm the gpu file check as lspci will check no gpu machine
=> [fix] rm the gpu log file probe log

pai-management/doc/cluster-bootup.md, pai-management/doc/how-to-write-pai-configuration.md, pai-management/doc/single-box-deployment.md
Add single box deployment instruction in README.
=> Add single box deployment instruction in README

pai-management/bootstrap/hadoop-service/hadoop-configuration/nodemanager-yarn-site.xml, pai-management/bootstrap/hadoop-service/hadoop-configuration/resourcemanager-yarn-site.xml
add the port and GPU related config in PAI-Hadoop config
=> Add hadoop config in PAI

examples/serving/README.md, examples/serving/serving.tensorflow.json, rest-server/src/config/job.js, rest-server/src/models/job.js
Add TensorFlow serving example.
=> [Examples] Add TensorFlow serving example

pai-management/doc/cluster-bootup.md, pai-management/doc/paictl.md, pai-management/paictl.py
Fix some cacography of word 'configuration' which is wrote of 'configuraiton'.
=> a few cacographies of word 'configuration'

rest-server/src/templates/dockerContainerScript.mustache, rest-server/src/templates/yarnContainerScript.mustache
Refine yarn container and docker container debug log. Enable debug log on yarn portal.
=> [Rest Server] Refine container log

cluster-configuration/services-configuration.yaml, pai-management/doc/how-to-write-pai-configuration.md, pai-management/quick-start/services-configuration.yaml.template
@hwuu @ydye ,
Please take a look.
I change the quick-start configuration to use hadoop-ai by default.
And some doc update.
=> change quick start to use hadoop-ai by default

pylon/src/nginx.conf.template
Merge #760 into release branch.
@hwuu please take a look.
=> (Merge #760 into release branch)[Pylon] Refine and fix bugs

examples/cntk/README.md, examples/cntk/cntk.g2p.json, examples/jupyter/README.md, examples/jupyter/jupyter.json, examples/keras/Dockerfile.example.keras.cntk_backend, examples/keras/Dockerfile.example.keras.tensorflow_backend, examples/keras/README.md, examples/keras/keras.cntk_backend.mnist.json, examples/keras/keras.tensorflow_backend.mnist.json, examples/mpi/README.md, examples/mpi/cntk-mpi.json, examples/mpi/tensorflow-mpi.json, examples/mxnet/README.md, examples/mxnet/mxnet.autoencoder.json, examples/mxnet/mxnet.image-classification.json, examples/pytorch/README.md, examples/pytorch/pytorch.mnist.json, examples/pytorch/pytorch.regression.json, examples/scikit-learn/README.md, examples/scikit-learn/sklearn.mnist.json, examples/scikit-learn/sklearn.text-vectorizers.json, examples/serving/README.md, examples/serving/serving.tensorflow.json, examples/tensorflow/README.md, examples/tensorflow/tensorflow.cifar10.json, examples/tensorflow/tensorflow.distributed-cifar10.json, examples/tensorflow/tensorflow.imagenet.json, examples/tensorflow/tensorflow.tensorboard.json
Update openpai examples, change registry namespace from `paiexample` to `openpai`.
=> Update openpai examples

cluster-configuration/services-configuration.yaml, pai-management/doc/how-to-write-pai-configuration.md, pai-management/quick-start/services-configuration.yaml.template
add description and default for "custom-hadoop-binary-path"
=> add description and default for "custom-hadoop-binary-path"

README.md, cluster-configuration/services-configuration.yaml, pai-management/doc/how-to-write-pai-configuration.md, pai-management/k8sPaiLibrary/maintainlib/kubectl_install.py, pai-management/quick-start/services-configuration.yaml.template, pylon/src/nginx.conf.template
Updates:
- Refine documents.
- Fix bug on kubectl installation.
- Fix bugs in Pylon.
=> Merge RC-0 branch back to master

frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/Node.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/applicationmaster/SelectionManager.java, frameworklauncher/src/test/java/com/microsoft/frameworklauncher/applicationmaster/SelectionManagerTest.java
1.	First packing job with the total GPU resource,   schedule small job to small node. 
2.	If the total resource is the same, Packing job with  the available resource, put small job together.
=> adjust packing logic

frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/utils/CommonUtils.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/common/web/WebStructure.java, frameworklauncher/src/main/java/com/microsoft/frameworklauncher/webserver/LauncherModule.java, frameworklauncher/src/main/resources/log4j.properties
1. [Launcher]: Support Fetch LauncherService Log through WebServer
2. [Launcher]: Do not log to console for LauncherAM to limit container log size
=> [Launcher]: Support Fetch LauncherService Log through WebServer and Limit Container Log Size

hadoop-ai/hadoop-build/build.sh
Hi @qinchen123 @ydye @hwuu , I cherry-pick the hadoop fix to v0.6.y.
=> [hot-fix]]Patch hadoop fix: update hadoop version

rest-server/src/controllers/template.js, rest-server/src/models/user.js, webportal/src/app/job/loading/loading.component.js, webportal/src/app/marketplace/template-view/resource-table.component.ejs, webportal/src/app/marketplace/template-view/template-modal.component.ejs, webportal/src/app/marketplace/template-view/template-modal.component.js, webportal/src/app/marketplace/template-view/template-view.component.ejs, webportal/src/app/marketplace/template-view/template-view.component.js
Separate the template modal dialog as an individual component.
Fix error of calculating table height.
Remove long log text when starting server.
Separate the template modal dialog as an individual component.
=> Refine user experience of the modal dialog which uploads the job template.

pai-management/bootstrap/prometheus/watchdog-ds.yaml.template, pai-management/src/watchdog/dockerfile, pai-management/src/watchdog/image.yaml, prometheus/exporter/watchdog.py
fix hard coding api server into watchdog image
=> [hot-fix]fix hard coding api server into watchdog image (#873)

pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template, prometheus/exporter/docker_inspect.py, prometheus/exporter/docker_stats.py, prometheus/exporter/gpu_exporter.py, prometheus/exporter/healthy_check.py, prometheus/exporter/job_exporter.py, prometheus/exporter/utils.py, prometheus/test/test_docker_inspect.py, prometheus/test/test_gpu_exporter.py
split io operation with metrics generation
=> split io and metrics generation

pylon/src/nginx.conf.template
Fixes https://github.com/Microsoft/pai/issues/816
=> Fix yarn web portal link.

pylon/src/nginx.conf.template
Cherry-pick HaoW's fix into 0.6.
=> [hotfix]Fix yarn web portal link.

rest-server/src/config/user.js, rest-server/src/controllers/user.js, rest-server/src/models/user.js, rest-server/test/userManagement.js
=> REST Server: refine user errors.

rest-server/src/config/token.js, rest-server/src/controllers/token.js, rest-server/src/models/token.js, rest-server/test/jobExecutionType.js, rest-server/test/jobSubmission.js, rest-server/test/userToken.js
=> REST Server: refine token errors

rest-server/src/controllers/user.js, rest-server/src/controllers/vc.js, rest-server/src/models/user.js, rest-server/src/models/vc.js, rest-server/test/userManagement.js, rest-server/test/vc.js
=> REST Server: refine vc errors.

rest-server/src/config/redis.js, rest-server/src/controllers/template.js, rest-server/src/models/template.js, rest-server/src/routes/template.js, webportal/src/app/marketplace/template-import/template-import.component.ejs, webportal/src/app/marketplace/template-import/template-import.component.js, webportal/src/app/marketplace/template-import/template-import.component.scss, webportal/src/app/marketplace/template-view/template-modal.component.ejs, webportal/src/app/marketplace/template-view/template-modal.component.js, webportal/src/app/marketplace/template-view/template-view.component.js
Remove the duplicated API listJobs.
Use LUA script to simplify the "top" method.
Fix BUG of cannot changing selected template.
Remove conflicts when saving templates.
Enable save template to local.
=> [Marketplace] Accelerate Top K query by using LUA script

hadoop-ai/README.md, hadoop-ai/hadoop-build/README.md, hadoop-ai/hadoop-build/build.sh, pai-management/paiLibrary/managementTool/ubuntu16.04/hadoop-ai-build.sh
1. update the hadoop version to 2.9.0
2. add the steps to change the hadoop version. this is for use to degrade the version.
=> update hadoop version to 2.9.0

rest-server/src/config/redis.js, rest-server/src/controllers/template.js, rest-server/src/models/template.js, rest-server/src/routes/template.js, webportal/src/app/marketplace/template-import/template-import.component.ejs, webportal/src/app/marketplace/template-import/template-import.component.js, webportal/src/app/marketplace/template-import/template-import.component.scss, webportal/src/app/marketplace/template-view/template-modal.component.ejs, webportal/src/app/marketplace/template-view/template-modal.component.js, webportal/src/app/marketplace/template-view/template-view.component.js
* Remove the duplicated API listJobs.
* Use LUA script to simplify the "top" method.
* Fix BUG of cannot changing selected template.
* Remove conflicts when saving templates.
* Refine code style.
* Enable save template to local.
=> [Marketplace] Accelerate Top K query by using LUA script (#913)

pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template, pai-management/bootstrap/prometheus/prometheus-deployment.yaml.template, pai-management/bootstrap/prometheus/stop.sh.template, prometheus/prometheus-alert/alert-template.rules
=> add alert rule template for prometheus

pai-management/bootstrap/prometheus/node-exporter-ds.yaml.template
=> expose uname for grafana use

job-tutorial/Dockerfiles/cuda9.0-cudnn7/Dockerfile.run.tensorflow
Update TensorFlow Dockerfile in job tutorial.
Fixes #932.
=> Update job tutorial

pai-management/k8sPaiLibrary/maintaintool/kubelet-start.sh
=> Fix issue #939

rest-server/package.json, rest-server/src/controllers/template.js, rest-server/src/models/template.js, webportal/src/app/marketplace/template-view/template-view.component.js, webportal/src/app/marketplace/template-view/template-view.component.scss
Search string pattern in name and description of templates.
When search empty string, refresh the page.
=> [Marketplace] Search string pattern in name and description of templates.

rest-server/src/config/redis.js, rest-server/src/controllers/template.js, rest-server/src/models/template.js, rest-server/src/routes/template.js, webportal/src/app/marketplace/template-import/template-import.component.js
=> Add rating to template.

rest-server/src/config/job.js, rest-server/src/routes/job.js, rest-server/test/jobExecutionType.js
Will correct status code to 400 in test case after #807 merged.
=> REST Server: check request payload type, fix #909

pai-management/doc/cluster-bootup.md
Notice: You should always deploy a stable release of PAI.
=> doc refine: notice user to deploy a stable release

rest-server/src/templates/dockerContainerScript.mustache, rest-server/src/templates/yarnContainerScript.mustache
modified:   rest-server/src/templates/dockerContainerScript.mustache
modified:   rest-server/src/templates/yarnContainerScript.mustache
=> refine log in exit handler

rest-server/src/config/template.js, rest-server/src/controllers/template.js, rest-server/src/models/template.js, webportal/src/app/user/user-profile/user-profile.component.ejs, webportal/src/app/user/user-profile/user-profile.component.js, webportal/src/app/user/user-profile/user-profile.component.scss
Add Experiment tab in user profile page.
Fix tab display error.
=> [Marketplace] Add Experiment tab in user profile page.

hadoop-ai/hadoop-build/build.sh, pai-management/paiLibrary/managementTool/ubuntu16.04/hadoop-ai-build.sh
=> Yarn GPU update

Jenkinsfile
=> Jenkinsfile Refine

Jenkinsfile, pai-management/bootstrap/hadoop-node-manager/hadoop-node-manager-configuration/nodemanager-generate-script.sh, pai-management/bootstrap/hadoop-node-manager/hadoop-node-manager.yaml.template, rest-server/src/templates/yarnContainerScript.mustache
Mount it into `/etc/hadoop-configuration-for-jobs` in host machine, `/etc/hadoop` in job container,
=> Mount hadoop node manager configuration outside.

rest-server/.eslintrc.js, rest-server/package.json, rest-server/src/config/jobV2.js, rest-server/src/middlewares/jobV2.js, rest-server/src/routes/indexV2.js, rest-server/src/routes/jobV2.js, rest-server/template_example/tensorflow-cifar10.yaml, rest-server/test/jobV2Submission.js
=> [PAIShare] Add new convertor for jobV2

pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template, prometheus/doc/exporter-for-other-services.md
make prometheus generate pai_service_name lable for scraped metrics.
=> generate pai_service_name label from app label

.travis.yml, pai-management/bootstrap/prometheus/prometheus-configmap.yaml.template, pai-management/bootstrap/prometheus/stop.sh.template, pai-management/bootstrap/prometheus/watchdog-ds.yaml.template, pai-management/src/watchdog/dockerfile, pai-management/src/watchdog/image.yaml, prometheus/doc/watchdog-metrics.md, prometheus/exporter/watchdog.py, prometheus/prometheus-alert/pai-services.rules, prometheus/test/test_watchdog.py
use prometheus_client in watchdog
=> use port to expose metrics in watchdog

docs/faq.md
=> refine faq for resource allocation

examples/serving/DOCKER.md, examples/serving/Dockerfile.example.tensorflow-serving
=> update tensorflow serving example

webportal/src/app/marketplace/job-submit/job-submit.component.ejs, webportal/src/app/marketplace/job-submit/job-submit.component.js, webportal/src/app/marketplace/job-submit/sub-components/task-format.ejs, webportal/src/app/marketplace/job-submit/sub-components/user-template.js
* update the job name and job descriptions as the yaml file’s job name
* reload the page when import a new yaml file
* fix can not edit job in empty page
=> update submit page

webportal/src/app/marketplace/job-submit/job-submit.component.ejs, webportal/src/app/marketplace/job-submit/job-submit.component.scss, webportal/src/app/marketplace/job-submit/sub-components/json-editor-schema.js, webportal/src/app/marketplace/job-submit/sub-components/task-format.ejs, webportal/src/app/marketplace/job-submit/sub-components/user-template.js
=> [PAIShare] Update command view.

Jenkinsfile, pai-management/Dockerfile, pai-management/quick-start/kubernetes-configuration.yaml.template
1. fix k8s version to 1.9.9
2. input Y for `./paictl.py service delete ..`
3. set different etcdid/zkid for cluster/singlebox
4. move pip install to dockerfile
5. add -f flag for `./paictl.py cluster k8s-clean`
=> Fix jenkins

rest-server/src/routes/template.js, rest-server/template_example/tensorflow-serving.yaml, webportal/src/app/config/webportal.config.json, webportal/src/app/marketplace/job-submit/job-submit.component.js, webportal/src/app/marketplace/job-submit/sub-components/add.ejs, webportal/src/app/marketplace/job-submit/sub-components/insert-layout.ejs, webportal/src/app/marketplace/job-submit/sub-components/prerequisite-format.scss, webportal/src/app/marketplace/job-submit/sub-components/summary-layout.ejs, webportal/src/app/marketplace/job-submit/sub-components/user-template.js, webportal/src/app/marketplace/job-submit/sub-components/yaml-json-editor-convert.js, webportal/src/app/marketplace/template-common/cards-format.scss, webportal/src/app/marketplace/template-common/cards.ejs, webportal/src/app/marketplace/template-common/template-search.component.js
add modal for data, docker and script
=> [PAIShare] add modal for data, docker and script

pai-management/doc/how-to-write-pai-service-configuration.md, prometheus/doc/alert-manager.md
cherry-picked from #1107 .
@YanjieGao please add links to this doc from https://github.com/Microsoft/pai/blob/master/pai-management/doc/how-to-write-pai-service-configuration.md
=> add alert manager doc

docs/faq.md
add other items which is suggested by ziming
=> faq for user resources limit of vc

rest-server/src/models/user.js, rest-server/test/userManagement.js, webportal/src/app/user/user-view/user-edit-modal-component.ejs
=> Disable set virtual clusters of admin

pai-management/quick-start/kubernetes-configuration.yaml.template
cherry-picked from #1126 to release 0.7 branch
=> fix k8s version to 1.9.9

cluster-configuration/cluster-configuration.yaml, pai-management/paiLibrary/clusterObjectModel/paiObjectModel.py, pai-management/quick-start/cluster-configuration.yaml.template
#1195 
cherry-picked to release 0.7 branch
=> label watchdog:true in cluster-object-model

pai-management/bootstrap/grafana/grafana-configuration/pai-clusterview-dashboard.json.template
Test on my VM: http://10.169.8.247:3000/dashboard/db/pai_clusterview?refresh=30s&orgId=1
Solve issue #227
=> modify grafana view to keep consistent with yarn

examples/keras/Dockerfile.example.keras.tensorflow_backend, examples/keras/keras.tensorflow_backend.mnist.json
origin example tf version is 1.4, incompatible with code, update it to 1.10
=> fix tf version

pai-management/k8sPaiLibrary/maintaintool/kubectl-install.sh, pai-management/paictl.py
use `add_subparser` and `add_parser` to handle subcmd in paictl.
This can print help msg for both `paictl.py -h` and `paictl.py machine -h` and `paictl.py machine add -h`.
=> refactor paictl.py

prometheus/exporter/job_exporter.py, prometheus/exporter/utils.py
update `.prom` file even if no metrics get.
Readiness probe will check these file's modify time.
=> fix gpu health check error

pai-management/Dockerfile, prometheus/doc/alert-manager.md, utilities/gen-amtool-config.py
Add muting alert facilities, rely on amtool to manage alert. Provide a script for generating amtool config.
@scarlett2018 please review the doc.
=> support mute alert

rest-server/src/templates/yarnContainerScript.mustache
This is a short-term mitigation for jenkins, still need to find the root cause
=> remove hadoop getconf

pai-management/doc/cluster-bootup.md
Doc: dev-box should run outside of PAI cluster.
Fixes #1283 .
=> dev-box should run outside of PAI cluster

pai-management/bootstrap/alert-manager/alert-manager.yaml.template, pai-management/bootstrap/node-exporter/node-exporter.yaml.template, pai-management/bootstrap/prometheus/prometheus-deployment.yaml.template, pai-management/bootstrap/watchdog/watchdog.yaml.template
make sure alert about disk/memory pressure can be sent out.
=> make prometheus/alert_manager/node_exporter/watchdog tolerate pressures

webportal/src/app/marketplace/job-submit/job-submit.component.ejs, webportal/src/app/marketplace/job-submit/job-submit.component.js, webportal/src/app/marketplace/job-submit/job-submit.component.scss
1. modify buttons style
2. change page background
3. modify docker/task/data/script style
3. change loading style
=> [PAISHARE]Submit button align and fix comments of OuYang

src/cleaining-image/build/cleaning-image.dockerfile, src/hadoop-ai/build/build-pre.sh, src/hadoop-ai/build/build.sh, src/hadoop-ai/build/docker-executor.patch, src/hadoop-ai/build/hadoop-ai, src/hadoop-node-manager/deploy/hadoop-node-manager-delete/delete.sh
fix list
1. clean job when delete nm 
2. Hadoop-ai
=> fix bugs in refactor

src/pylon/src/nginx.conf.template
=> Pylon: Fix rewrite of WebHDFS redirection (#1328)

src/webportal/src/app/job/job-view/job-detail-config-info-modal.component.ejs, src/webportal/src/app/job/job-view/job-view.component.js
=> Export config at job detail page

deployment/quick-start/services-configuration.yaml.template, src/pylon/deploy/pylon-service.yaml.template, src/pylon/deploy/pylon.yaml.template, src/pylon/deploy/start.sh.template, src/pylon/deploy/stop.sh
For AKS, we could deploy service then aks assign a public ip for this service. Then user could use this address to access pylon proxy pai service
=> [AKS] add pylon service for aks LB access pai web service

README.md
=> add nni link

src/watchdog/deploy/watchdog-configmap.yaml.template, src/watchdog/src/watchdog.py
=> use sshport instead of port in watchdog configmap

examples/auto-test/job_manage.py, examples/auto-test/readme.md, examples/auto-test/start.sh, examples/mxnet/Dockerfile.example.mxnet
mxnet example:
fix branch version
auto-test:
change urlencoded to json when get the token
=> add support for special characters & fix version of mxnet example

src/rest-server/deploy/rest-server.yaml.template
=> REST server deployment: Render github env only they are given

deployment/paiLibrary/clusterObjectModel/paiObjectModel.py, src/pylon/deploy/pylon.yaml.template, src/pylon/src/nginx.conf.template
=> Add backward compatibility of WebHDFS

src/webportal/package.json, src/webportal/src/app/job/job-view/job-view.component.js, src/webportal/yarn.lock
[Web Portal] support select and stop multiple jobs
- joi 13.0.2 needs node >= 8.9.0, so I remove the engines requirements
=> [Web Portal] support select and stop multiple jobs

src/prometheus/deploy/prometheus-deployment.yaml.template
merge hotfix #1564 into master.
=> increase prometheus memory limits (data keep 1 week on a 15 workers cluster)

src/rest-server/src/config/user.js, src/rest-server/src/models/user.js, src/rest-server/test/userManagement.js, src/webportal/src/app/user/user-register/user-register.component.js, src/webportal/src/app/user/user-view/user-edit-modal-component.ejs, src/webportal/src/app/user/user-view/user-view.component.js
1. Fix wrong alert info.
2. Separate password change and user info update logic
=> [Hotfix] fix user management

src/rest-server/src/models/job.js, src/rest-server/test/jobDetail.js, src/rest-server/test/setup.js, src/webportal/src/app/job/job-view/job-detail-table.component.ejs
Closes #225 
Highlight succeeded container as green and failed container as red.
=> Expose container exit type in web portal

docs/job_tutorial.md
Update job tutorial, add doc about `jobEnvs`.
=> update jobEnvs doc

src/rest-server/deploy/rest-server.yaml.template
=> REST server deployment: Render github env only they are given (#1547)

src/prometheus/deploy/prometheus-deployment.yaml.template
=> add imagePullSecrets to prometheus

src/end-to-end-test/start.sh
=> check token existence

src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template, src/grafana/deploy/service.yaml
=> add pai service dashboard to grafana

src/hadoop-name-node/deploy/hadoop-name-node-configuration/hdfs-site.xml
=> change hdfs safemode threshold

build/core/build_center.py, deployment/confStorage/conf_storage_util.py, deployment/confStorage/download.py, deployment/confStorage/external_version_control/external_config.py, deployment/confStorage/upload.py, deployment/k8sPaiLibrary/maintainlib/add.py, deployment/k8sPaiLibrary/maintainlib/etcdfix.py, deployment/k8sPaiLibrary/maintainlib/remove.py, deployment/k8sPaiLibrary/maintainlib/update.py, deployment/paiLibrary/paiService/service_management_delete.py, deployment/paiLibrary/paiService/service_management_refresh.py, deployment/paiLibrary/paiService/service_management_start.py, deployment/paiLibrary/paiService/service_management_stop.py, deployment/paiLibrary/paiService/service_template_clean.py
This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
=> Compare to `None` using identity `is` operator

docs/alerting/README.md, docs/alerting/exporter-metrics.md, src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template
related to #1691 , use metric exposed by that PR.
=> use configured_gpu_count instead of nvidiasmi_attached_gpus in grafana

src/grafana/deploy/grafana-configuration/pai-clusterview-dashboard.json.template
=> remove unavailable gpu panel from dashboard

deployment/k8sPaiLibrary/template/apiserver.yaml.template, deployment/k8sPaiLibrary/template/controller-manager.yaml.template, deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template, deployment/k8sPaiLibrary/template/etcd.yaml.template, deployment/k8sPaiLibrary/template/kubelet.sh.template, deployment/k8sPaiLibrary/template/scheduler.yaml.template, src/hadoop-data-node/deploy/hadoop-data-node.yaml.template, src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/nodemanager-generate-script.sh, src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template, src/zookeeper/deploy/zookeeper.yaml.template
cherry-pick the hot-fixes #1619 #1689 to master.
=> fix memory limits

deployment/quick-start/services-configuration.yaml.template, release-notes.md
Fixed the datanode oom issue #1658, release a patch version v0.8.1
=> release v0.8.1

deployment/clusterObjectModel/cluster_object_model.py, deployment/clusterObjectModel/mainParser/kubernetes.py, deployment/clusterObjectModel/mainParser/machine.py, src/cluster/config/cluster.py
- Refine class name, based on pep8
- Fix an issue. service, whose name is like xxx-yyy-zzz,  will be translated to XxxYyyZzz.
=> [Cluster Object Model] Modify class name according to pep8

src/yarn-exporter/src/requirements.txt
bump requests library version for yarn-exporter
=> bump requests version

src/webportal/package.json, src/webportal/yarn.lock
=> webportal: upgrade blueimp-file-upload to 9.22.1

src/prometheus/deploy/alerting/node.rules
=> increase node cpu alerting level

.travis.yml, deployment/clusterObjectModel/test/data/configuration-template-generate/cluster-configuration.yaml, deployment/clusterObjectModel/test/data/configuration-template-generate/k8s-role-definition.yaml, deployment/clusterObjectModel/test/data/configuration-template-generate/kubernetes-configuration.yaml, deployment/clusterObjectModel/test/data/configuration-template-generate/services-configuration.yaml, deployment/clusterObjectModel/test/test_template_generate.py, deployment/paiLibrary/paiService/service_template_clean.py, deployment/paiLibrary/paiService/service_template_generate.py, src/zookeeper/config/zookeeper.md, src/zookeeper/config/zookeeper.py, src/zookeeper/config/zookeeper.yaml, src/zookeeper/deploy/delete.yaml.template, src/zookeeper/deploy/zookeeper.yaml.template
This UT won't pass ci/cd until the complete of all service parser and deployment refactor. I will merge this UT into the branch yuye/improve-com. So that, I can check the refactor of each service is passed or not.
=> [Cluster Object Model] Enable template UT to check branch states.

src/hadoop-data-node/config/hadoop-data-node.yaml, src/hadoop-data-node/config/hadoop_data_node.py, src/hadoop-data-node/deploy/delete.yaml.template, src/hadoop-data-node/deploy/hadoop-data-node.yaml.template
data node don't need its own config items,  ignore parser
=> [Cluster Object Model] change data node template files

src/hadoop-batch-job/deploy/hadoop-configuration/yarn-site.xml, src/hadoop-resource-manager/config/hadoop-resource-manager.yaml, src/hadoop-resource-manager/config/hadoop_resource_manager.py, src/hadoop-resource-manager/deploy/delete.yaml.template, src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/capacity-scheduler.xml.template, src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/yarn-site.xml, src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template
Block by Prometheus object model (yarn_exporter_port)
=> [Cluster Object Model] resource-manager parser

deployment/quick-start/services-configuration.yaml.template, release-notes.md, src/webportal/package.json
Fix grafana rule syntax error and remove unnecessary template variables
machine-maintenance document adds more detail about how to add node to kubernetes cluster
=> [Hotfix release] Patch v0.8.2

deployment/clusterObjectModel/forward_compatibility.py
Old
```
grafana:
grafana-port: 3000
```
New
```
grafana:
port: 3000
```
=> [Cluster Object Model] Grafana configuraiton compatibility

deployment/quick-start/services-configuration.yaml.template, examples/cluster-configuration/services-configuration.yaml, src/rest-server/config/rest-server.md, src/rest-server/config/rest-server.yaml, src/rest-server/config/rest_server.py, src/rest-server/deploy/rest-server.yaml.template
The service port of HDFS, WebHDFS and Yarn is hard-coded in object model of the previous code, but still shared in configurations of different services (rest-server & pylon, because they are written in the same file, call the same methods).
Currently, the parser code of different service is separated, so the services port of dependencies will be hard-coded more than once.
=> [rest-server]parser of cluster object model

deployment/clusterObjectModel/forward_compatibility.py
Old configuraiton 
```
prometheus:
prometheus-port: 9091
```
New configuration
```
prometheus:
port: 9091
```
=> Prometheus port configuration compatibility

deployment/quick-start/services-configuration.yaml.template, examples/cluster-configuration/services-configuration.yaml, src/pylon/config/pylon.md, src/pylon/config/pylon.py, src/pylon/config/pylon.yaml, src/pylon/deploy/pylon-service.yaml.template, src/pylon/deploy/pylon.yaml.template, src/pylon/deploy/start.sh.template
2 internal used configurations will be undocumented.
- `webhdfs_legacy_port` is for legacy use
- `deploy_service` is for future use
=> [pylon]parser of cluster object model

src/webportal/src/app/job/job-submit/job-submit.component.js
Closes #1767:force login before access SubmitJob page
If you do not log in when you enter the Submit Job V2 page, you will be redirected to the login page, but this feature is not available in the Submit Job page.
Add this function to /pai/src/webportal/src/app/marketplace/job-submit/job-submit.component.js and call userAuth.checkToken after the DOM is loaded.
=> Closes #1767 force login before access SubmitJob page

src/drivers/build/install-all-drivers, src/drivers/build/install-nvidia-drivers
cherry-pick of #1814 . related to #1557
=> fix drivers bug

examples/job-editor/README.md, examples/job-editor/job-editor.dockerfile, examples/job-editor/mnist_pytorch.ipynb
1. Launcher a Jupyter server
2. Hosted a mnist pytorch example
3. Scripts for automatically submitting the example to cluster
=> Job-editor prototype

src/rest-server/deploy/rest-server.yaml.template, src/rest-server/src/templates/yarnContainerScript.mustache
=> fix driver bug

docs/pai-management/doc/cluster-bootup.md
=> tell user to change gpu type/count in quick start doc

docs/job_tutorial.md, src/webportal/config/marked.config.js
=> Web portal: fix doc link

docs/job_tutorial.md, src/webportal/config/marked.config.js
hotfix to 0.8.y
cherry-picked from master
=> Web portal: fix doc link (#1844)

examples/job-editor/setup_hdfs.sh
The script file `setup_hdfs.sh` was not included in the code, append it.
=> Add the missing scripts setup_hdfs.sh

deployment/quick-start/services-configuration.yaml.template, src/job-exporter/config/job-exporter.md, src/job-exporter/config/job-exporter.yaml, src/job-exporter/deploy/job-exporter.yaml.template, src/job-exporter/src/collector.py, src/job-exporter/src/main.py, src/job-exporter/src/network.py
=> select a network interface

src/grafana/deploy/grafana-configuration/pai-jobview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-taskroleview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-taskview-dashboard.json.template
=> do not use irate in task_net* and service_net* metric

src/webportal/config/marked.config.js
=> (hotfix) webportal: fix baseurl of document

src/pylon/src/nginx.conf.template
=> Pylon: replace WehHDFS URLs in REST server responses

Jenkinsfile
clean up untracked files, prevent git cmd from failing
=> Fix jenkins failure: /.git/index.lock': File exists.

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md
Add issue and enhancement template:
try and test use this simple repo to create an issue.
https://github.com/YanjieGao/testdoc
Note: detailed info is at doc's comment
- For create an issue:
Organization Name:
Short summary about the issue/question:
Brief what process you are following:
How to reproduce it:
OpenPAI Environment:
OpenPAI version:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Others:
Anything else we need to know:
- For create an enhancement:
What would you like to be added:
Why is this needed:
Components that may involve changes:
=> [git]issue template

src/job-exporter/deploy/job-exporter.yaml.template, src/node-exporter/deploy/node-exporter.yaml.template, src/watchdog/deploy/watchdog.yaml.template
=> write timeout parameter explicitly

Jenkinsfile
Avoiding git cmd in Jenkinsfile, cp source codes from workspace.
Previously fix didn't work.
=> refine Jenkinsfile, solve the git index.lock issue

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml
=> add timeout option in nm, for launcher need

docs/job_tutorial.md, src/rest-server/src/templates/yarnContainerScript.mustache
related issue [#1895](https://github.com/Microsoft/pai/issues/1895)
expose all ports among tasks and the format will be:
PAI_${task_role}_${taskidx} _${portlabel}_PORT=${port_number}
=> [Rest-server]Rebase expose port among tasks

docs/alerting/watchdog-metrics.md, src/watchdog/src/watchdog.py
fix #1878 . Remove the check of kubelet in watchdog, since watchdog already checking node status.
=> remove kubelet check in watchdog

deployment/clusterObjectModel/mainParser/kubernetes.py, deployment/k8sPaiLibrary/template/apiserver.yaml.template, deployment/k8sPaiLibrary/template/controller-manager.yaml.template, deployment/k8sPaiLibrary/template/dashboard-deployment.yaml.template, deployment/k8sPaiLibrary/template/etcd.yaml.template, deployment/k8sPaiLibrary/template/scheduler.yaml.template, deployment/quick-start/kubernetes-configuration.yaml.template, deployment/quick-start/services-configuration.yaml.template, examples/cluster-configuration/kubernetes-configuration.yaml, examples/cluster-configuration/services-configuration.yaml, src/cleaner/deploy/cleaner.yaml.template, src/cluster/config/cluster.md, src/cluster/config/cluster.yaml, src/drivers/deploy/drivers.yaml.template, src/grafana/deploy/grafana.yaml.template, src/hadoop-data-node/deploy/hadoop-data-node.yaml.template, src/hadoop-jobhistory/deploy/hadoop-jobhistory.yaml.template, src/hadoop-name-node/deploy/hadoop-name-node.yaml.template, src/hadoop-node-manager/deploy/hadoop-node-manager.yaml.template, src/hadoop-resource-manager/deploy/hadoop-resource-manager.yaml.template, src/job-exporter/deploy/job-exporter.yaml.template, src/node-exporter/deploy/node-exporter.yaml.template, src/prometheus/deploy/prometheus-deployment.yaml.template, src/pylon/deploy/pylon.yaml.template, src/rest-server/deploy/rest-server.yaml.template, src/watchdog/deploy/watchdog.yaml.template, src/webportal/deploy/webportal.yaml.template, src/yarn-frameworklauncher/deploy/yarn-frameworklauncher.yaml.template, src/zookeeper/deploy/zookeeper.yaml.template
- k8s level
Add a configuration named ```kubernetes.qos-switch```. And its default value will be ```"true"```.
If ```kubernetes.qos-switch``` is ```"true"```, the ```resources.requests or resource.limits``` part will be enabled.
If ```kubernetes.qos-switch``` is ```"false"```, the ```resources.requests or resource.limits``` part will be removed from the component.
See the example code following.
```
{% if cluster_cfg['kuberentes']['qos-switch] == "true" -%}
resources:
requests:
memory: "1Gi"
cpu: "1000m"
{%- endif %}
``` 
- service level
Add a configuration named ```cluster.common.qos-switch```. And its default value will be ```"true"```.
If ```cluster.common.qos-switch``` is ```"true"```, the ```resources.requests or resource.limits``` part will be enabled.
If …
=> [QoS] qos switch to disable the resource requirement.

src/job-exporter/src/collector.py
previous it's watchdog uses systemctl to check dockerd's status, we moved the check into job-exporter but job-exporter can not call systemctl. Use `docker info`, as it is the [recommended way](https://docs.docker.com/config/daemon/#check-whether-docker-is-running) to check dockerd's status
=> use docker info to check dockerd's status

src/rest-server/src/models/user.js, src/rest-server/test/jobSubmission.js
If is admin user we can let he submit job to all virtual cluster
=> [Rest-server] Fix admin can't submit job to newly added VC

src/webportal/src/app/user/user-view/user-view.component.js
Now admin vc list will display all virtual clusters in webportal
=> [Webportal] Admin vc list will display all virtual clusters

src/prometheus/deploy/prometheus-configmap.yaml.template
issue context:
https://github.com/Microsoft/pai/issues/1551
This pr is seperated part from previous PR (prometheus and watchdog access api-server auth):
https://github.com/Microsoft/pai/pull/1710
=> [aks] prometheus attach token for access api-server

src/alert-manager/config/alert-manager.md, src/alert-manager/config/alert-manager.yaml, src/alert-manager/deploy/alert-manager.yaml.template, src/grafana/deploy/grafana-configuration/prom-datasource.json.template, src/prometheus/deploy/prometheus-configmap.yaml.template, src/prometheus/deploy/prometheus-deployment.yaml.template, src/pylon/config/pylon.py, src/pylon/deploy/pylon.yaml.template, src/pylon/src/nginx.conf.template
add `/alert-manager` route to pylon, also change `/prometheus` route to make pylon can server prometheus web request.
=> support external url in alerting email

docs/job_tutorial.md
Rename env to PAI_$taskRole_$taskIndex_$type_PORT
=> [Doc] Update job_tutorial.md rename PAI_$taskRole_$taskIndex_$type_PORT

examples/cluster-configuration/services-configuration.yaml, src/cluster/config/cluster.md, src/cluster/config/cluster.py, src/cluster/config/cluster.yaml
Add configuration named ```az-rdma``` in service-configuration.cluster.
=> [Azure-RDMA] cluster configuration preparation for az-rdma

src/webportal/src/app/env.js.template
=> Webportal: Fix prometheus requests

src/webportal/src/app/env.js.template
=> (Hotfix) Webportal: Fix prometheus requests

src/webportal/src/app/cluster-view/hardware/hardware.component.ejs, src/webportal/src/app/cluster-view/hardware/hardware.component.js
=> Web portal: hardware page, use ip address to identify rows, fixes #2020

src/hadoop-batch-job/deploy/hadoop-configuration/hdfs-site.xml, src/hadoop-data-node/deploy/hadoop-data-node-configuration/hdfs-site.xml, src/hadoop-name-node/deploy/hadoop-name-node-configuration/hdfs-site.xml, src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/hdfs-site.xml
#2023 
Disable it will suppress some annoy warning.
=> Disable hdfs shortcircuit

release-notes.md, src/rest-server/src/templates/dockerContainerScript.mustache
fix duplicate brace in private key path
=> fix duplicate brace

deployment/clusterObjectModel/mainParser/kubernetes.py, deployment/layout.py, deployment/quick-start/layout.yaml.template, src/pylon/config/pylon.py, src/pylon/deploy/pylon.yaml.template, src/webportal/config/webportal.py, src/webportal/deploy/webportal.yaml.template
Have not read all deploy code yet, only added a `dashboard-url` field to kubernetes cluster object model.
=> Make kubernetes dashboard config as url

src/webportal/src/app/cluster-view/hardware/hardware.component.ejs, src/webportal/src/app/cluster-view/hardware/hardware.component.js
* Web portal: hardware page, use ip address to identify rows, fixes #2020
* Remove debugger
* Simplify parens
=> Web portal: hardware page, use ip address to identify rows, fixes #2020 (#2025)

src/prometheus/deploy/alerting/node.rules
=> fix wording in alert email

deployment/quick-start/services-configuration.yaml.template, docs/faq.md, docs/hadoop/yarn_service.md, examples/cluster-configuration/services-configuration.yaml, src/hadoop-resource-manager/config/hadoop-resource-manager.md, src/hadoop-resource-manager/deploy/hadoop-resource-manager-configuration/capacity-scheduler.xml.template, src/rest-server/src/models/vc.js, src/rest-server/src/util/error.d.ts, src/rest-server/test/vc.js
1. Fix issues when delete a vc with running job #2055 
2. Limit AM resource percentage to 50% #2049 
3. Disable bonus token #2054 
4. Remove legacy VC docs #2019
=> hotfix to 0.9

src/pylon/config/pylon.py, src/pylon/deploy/start.sh.template
=> Add missing com fields in pylon, fixes #2082

docs/pai-protocol.yaml
Update PAI protocol template and example. Comments in #2007.
=> Update PAI protocol yaml

src/webportal/src/app/plugin/plugin.component.js
Cherry-picked from #2063 
jQuery version could not provide the document.currentScript property.
=> Use native loadScript instead of jQuery.getScript

src/webportal/src/app/plugin/plugin.component.js
=> Add user name & token to plugin attributes

deployment/tools/configMigration.py
After move the script, the import was broken, fix it.
=> [HOT-FIX]fix import broken

deployment/tools/configMigration.py
After move the script, the import was broken, fix it.
=> fix import broken after move the script

src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template, src/grafana/src/dashboards/gpu.js
fix a bug in link of node view, and add gpu memory util in per gpu page
=> add gpu memory util in per gpu page

deployment/tools/configMigration.py
Fix #2165 , the config migration tool was assigning wrong dashboard port, fix it.
=> fix dashboard-uri

src/rest-server/src/models/token.js
Will cherry-pick to `master` / `pai-0.9.y`
=> REST Server: Fix admin permission, Closes #2172

deployment/k8sPaiLibrary/maintaintool/docker-ce-install.sh
=> add repo before installing nvidia-container-runtime

deployment/k8sPaiLibrary/maintaintool/docker-ce-install.sh
=> add repo before installing nvidia-container-runtime (#2186)

src/watchdog/src/watchdog.py
get ride of
```
Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
DeferredList(beforeResults).addCallback(self._continueFiring)
File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
callbackKeywords=kw)
File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
self._runCallbacks()
File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
--- &lt;exception caught here&gt; ---
File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
callable(*args, **kwargs)
File …
```
=> put twisted in main thread in watchdog

src/grafana/src/dashboards/gpu.js, src/job-exporter/src/nvidia.py, src/job-exporter/test/data/nvidia_smi_sample.xml, src/job-exporter/test/test_nvidia.py
=> generate gpu memory util as used/total

src/job-exporter/src/collector.py, src/job-exporter/src/main.py
=> fix missing gpu metrics

src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-tasks-in-node-dashboard.json.template, src/grafana/deploy/service.yaml
Add a page to show all tasks util in certain node
add a link to tasks in node page in node util page like
=> add a dashboard in grafana to list all tasks in node

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md
Fix format in issue templates:
- remove trailing spaces
- change chinese colon into english
=> Fix format in issue templates

src/rest-server/test/jobExecutionType.js
=> REST server: remove expires in JWT payload of unit test

src/job-exporter/src/collector.py, src/job-exporter/src/main.py, src/job-exporter/src/nvidia.py, src/job-exporter/src/ps.py, src/job-exporter/test/data/ps_sample.txt, src/job-exporter/test/test_collector.py, src/job-exporter/test/test_nvidia.py, src/job-exporter/test/test_ps.py, src/prometheus/deploy/alerting/gpu.rules
fixed #2192 , working in progress
=> alert on unhealthy gpu

src/hadoop-ai/build/build-pre.sh
=> [BUG] Fix hadoop ai build path

src/pylon/src/nginx.conf.template
=> Pylon: fix double start query in yarn redirect

src/end-to-end-test/deploy/start.sh
=> [Cherry-pick] disable end-to-end test

src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template, src/grafana/src/dashboards/gpu.js
=> add gpu memory util in per gpu page (#2166)

README.md, deployment/clusterObjectModel/service_config_update.py, deployment/paiLibrary/paiService/service_management_refresh.py, deployment/tools/configMigration.py, docs/pai-management/doc/add-service.md, docs/pai-management/doc/customized-configuration.md, docs/pai-management/doc/how-to-bootup-k8s.md, docs/pai-management/doc/how-to-generate-cluster-config.md, docs/pai-management/doc/how-to-start-pai-serv.md, docs/pai-management/doc/kubernetes-ha.md, docs/pai-management/doc/validate-deployment.md, docs/upgrade/upgrade_to_v0.10.md
Add detailed upgrading doc for v0.10. Support upgrade since v0.8 and later.
=> [v0.10.1] Add upgrading doc for v0.10

src/prometheus/deploy/alerting/node.rules
=> fix alerting rule bugs

deployment/tools/pluginIdMigration.py
Add convert code to add id for webportal plugins
=> Add convert code to add id for webportal plugins

RELEASE_NOTES.md
Will change merge base to pai-v0.10.y after the branch is created.
=> WIP: Draft a v0.10.1 release note

README.md, deployment/clusterObjectModel/service_config_update.py, deployment/paiLibrary/paiService/service_management_refresh.py, deployment/tools/configMigration.py, docs/pai-management/doc/add-service.md, docs/pai-management/doc/customized-configuration.md, docs/pai-management/doc/how-to-bootup-k8s.md, docs/pai-management/doc/how-to-generate-cluster-config.md, docs/pai-management/doc/how-to-start-pai-serv.md, docs/pai-management/doc/kubernetes-ha.md, docs/pai-management/doc/validate-deployment.md, docs/upgrade/upgrade_to_v0.10.md
Cherry-pick the upgrade doc and script for v0.10 to master branch.
=> Cherry-pick upgrade doc and script from v0.10

src/prometheus/deploy/alerting/node.rules
increase memory threshold to 95%
=> increase memory threshold to 95%

src/rest-server/.editorconfig, src/rest-server/package.json, src/rest-server/src/config/v2/protocol.js, src/rest-server/src/middlewares/v2/asyncHandler.js, src/rest-server/src/middlewares/v2/protocol.js, src/rest-server/test/v2/protocol.js, src/rest-server/yarn.lock
Part of #2260. Protocol yaml parsing, validation, and rendering:
- Use `ajv` for protocol schema and validation.
- Use `mustache` for protocol rendering.
=> [Rest Server] Protocol yaml parsing, validation, and rendering

src/rest-server/src/models/v2/job.js
Part of #2260. Convert protocol to framework launcher description file.
Unit tests will be added in a separate PR.
=> [Rest Server] Convert protocol to framework launcher description

src/hadoop-ai/build/YARN-8896-2.9.0.patch, src/hadoop-ai/build/build-pre.sh, src/hadoop-ai/build/build.sh, src/hadoop-ai/build/hadoop-ai
* add max allocation per heatbeat
* reneme patch for better readibility
=> [hotfix_0.11]add yarn max allocation per heatbeat (#2365)

src/drivers/deploy/clean.yaml.template
fix bug in rollback nvidia container runtime
=> fix delete script of rollback nvidia runtime

docs/pai-management/doc/distributed-deploy.md
=> documentation typo fix

contrib/submit-nfs-job/src/App/TensorflowDistributedJob.tsx
* fix typo
* add `minSucceededTaskCount` in distributed job
=> [Webpotal Plugin] Fix bugs

docs/pai-management/doc/distributed-deploy.md
Thanks to @keithcallenberg's contribution in #2285.
=> [Docs] Cherry pick #2285 documentation typo fix

contrib/submit-nfs-job/src/App/TensorflowSingleNodeJob.tsx
Change `name` to `jobName` in json.
Closes #2390.
=> [Webportal Plugin] Fix bugs

src/webportal/src/app/layout/layout.component.ejs
Change label to title in a new template for feedback.
Closes #2100.
=> [Webportal] Update new issue template

src/webportal/src/app/job/job-view/fabric/job-detail.jsx, src/webportal/src/app/job/job-view/fabric/job-list.jsx
Add active sidebar menu in job list/detail pages.
=> [Webportal] Add active sidebar menu in job list/detail pages

contrib/submit-nfs-job/src/App/TensorflowDistributedJob.tsx, contrib/submit-nfs-job/src/App/TensorflowSingleNodeJob.tsx, docs/pai-management/doc/distributed-deploy.md, src/webportal/src/app/job/job-view/fabric/job-detail.jsx, src/webportal/src/app/job/job-view/fabric/job-list.jsx, src/webportal/src/app/layout/layout.component.ejs
Cherry pick hotfix commits into v0.11 release: #2379, #2380, #2391, #2392.
=> [Hot Fix] Merge master into release 0.11

contrib/storage_plugin/README.MD
=> Update README.MD (#2397)

deployment/quick-start/services-configuration.yaml.template, deployment/tools/configMigration.py, deployment/tools/pluginIdMigration.py, docs/upgrade/upgrade_to_v0.11.md
Including:
- change template tag to v0.11.0
- update configMigration.py to support 0.10 -> 0.11
- add plugin migration docs.
=>  v0.11 upgrade process

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
- fix the bug that log auto referesh is not disabled when SSH info is shown
- add username "root" to ssh command
=> [Web Portal] fix container ssh info

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
=> [Web Portal] fix container ssh info #2401

src/webportal/src/app/job/job-view/fabric/job-detail.jsx
- job v2's config file may not have taskRoles property
=> [Web Portal] fix job v2 detail page rendering error

src/webportal/src/app/job/job-view/fabric/job-detail.jsx
=> [Web Portal] fix job v2 detail page rendering error #2417

src/webportal/src/app/job/job-view/fabric/JobList/Ordering.js, src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx
=> Job list: add retries column

deployment/k8sPaiLibrary/maintainlib/deploy.py
=> Paictl  k8s boot-up failed

README.md, docs/user/training.md
update doc for better reading.
update hello-world sample, as it fails with CUDA 10.
=> Doc refactoring and update hello-world sample

src/job-exporter/src/docker_inspect.py, src/job-exporter/test/data/inspect_result_bug_fix.json, src/job-exporter/test/test_docker_inspect.py
=> fix void env supply by yarnScript

src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
Fixes #2420 
- Refine dependency of filterJobs
- Optimize rendering of KeywordSearchBox
- Debounce filter update by 200ms
=> Job list: optimize filter

src/webportal/src/app/job/job-view/fabric/job-detail/components/status-badge.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/util.js
=> [Web Portal] Display task state in job detail page

deployment/k8sPaiLibrary/maintainlib/common.py, deployment/k8sPaiLibrary/maintainlib/deploy.py, src/drivers/deploy/drivers.yaml.template
#2433 
This is only a workaround for v0.10, official fix is in v0.11.
To apply it, you should do following steps before setup cluster.
In dev-box:
```
cd /pai
git fetch
git checkout pai-0.10.y
```
=> Unblock v0.10 setup

src/rest-server/src/templates/yarnContainerScript.mustache
=> Refine hdfs error message.

contrib/pai_vscode/package.json, contrib/pai_vscode/src/pai/paiJobManager.ts
=> [VS Code] Improve speed of simulation

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
=> [Web Portal] fix job detail page's "retry link"

src/pylon/src/nginx.conf.template, src/rest-server/src/controllers/job.js, src/rest-server/test/jobSubmission.js
1. Respond a location header of the job just created.
2. Respond the job details if launcher creates the framework on time.
=> Follow REST protocol in job create controller, closes #1629

src/webportal/src/app/job/job-view/fabric/job-detail/util.js
[Web Portal] fix job detail "jobConfig not found" bug
=> [Web Portal] fix job detail "jobConfig is null" bug

src/rest-server/src/models/job.js, src/webportal/src/app/job/job-view/fabric/JobList/Ordering.js, src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx
=> [Web Portal][Rest Server] Add TotalGpuCount and TotalTaskCount into job list

src/alert-manager/config/alert-manager.md, src/alert-manager/config/alert-manager.yaml, src/alert-manager/deploy/alert-configmap.yaml.template, src/alert-manager/deploy/alert-templates/pai.tmpl
@squirrelsc think there are too many same alert email, so maybe should enlarge the interval of same alerts, I make it as configurable and default to our old value.
At the same time, it would be useful to send resolved email to notify problem solved.
=> send resolved email and make user can config repeat interval

src/webportal/src/app/job/job-submit/job-submit.component.js, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx
bug issue: https://github.com/Microsoft/pai/issues/2375
=> fix two bugs: add validation when submitting job by json #2375, Job List-filter UI fix #2479

deployment/checkCmd.py
Add a prerequisites check for os version, as part of #1893. Fixes #1657 .
=> check if the nodes are ubuntu 16.04

contrib/storage_plugin/storagectl.py, src/dev-box/build/dev-box.dockerfile
1. Add dev-box environment for storage plugin.
2. Handle case when setup storage server with no storage user.
=> Add environment and handle corner cases

contrib/submit-nfs-job/src/App/SimpleNFSJob.tsx, contrib/submit-nfs-job/src/App/TensorflowDistributedJob.tsx, contrib/submit-nfs-job/src/App/TensorflowSingleNodeJob.tsx, contrib/submit-nfs-job/src/App/index.tsx
https://github.com/Microsoft/pai/issues/2518
=> Update docker selection guidence in the UX #2518

src/webportal/src/app/job/job-submit/job-submit.component.js, src/webportal/src/app/job/job-submit/job-submit.schema.js
1. Only show the following fields in job form by default:
- `jobName`
- `image`
- `virtualCluster`
- `taskRoles`
2. Only show the following fields in taskRole form by default:
- `name`
- `taskNumber`
- `cpuNumber`
- `memoryMB`
- `gpuNumber`
- `command`
3. Rename item in taskRoles to "taskRole"
4. Rename item in portList to "port"
5. Patch the label of Properties button to "More Properties"
=> Refine job submission form

src/webportal/src/app/job/job-view/fabric/job-detail/components/monaco-panel.jsx
#2554 
This PR is a shim of webkit's flexbox bug.
The bug has been fixed in the latest version of Chrome/Chromium/Opera.
- webkit:  https://bugs.webkit.org/show_bug.cgi?id=137730#c24
- chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=784059
=> [Web Portal] fix job detail page's stdout/stderr/ssh info css bug

src/webportal/src/app/job/job-view/fabric/job-detail/components/monaco-panel.jsx
=> [Web Portal] fix job detail page's stdout/stderr/ssh info css bug #2559

src/hadoop-data-node/deploy/hadoop-data-node-configuration/core-site.xml, src/hadoop-name-node/deploy/hadoop-name-node-configuration/core-site.xml
Fix #2551 
According to https://hadoop.apache.org/docs/r2.9.0/hadoop-project-dist/hadoop-common/HttpAuthentication.html#CORS
=> Enable hdfs cros

contrib/storage_plugin/README.MD, contrib/storage_plugin/README_zh_CN.MD
=> Fix Storage Doc 0.12

contrib/storage_plugin/README.MD, contrib/storage_plugin/README_zh_CN.MD
=> Storage doc fix

.travis.yml, contrib/submit-protocol/package.json, contrib/submit-protocol/src/App/ProtocolForm.tsx, contrib/submit-protocol/yarn.lock
Replace bootstrap with fabric styles.
Asset size: `plugin.js 1.25MB -> 652KB`.
=> [Protocol Plugin] Replace bootstrap with fabric styles

src/rest-server/src/templates/dockerContainerScript.mustache, src/rest-server/src/templates/yarnContainerScript.mustache
Remove useless log such as:
% Total    % Received % Xferd  Average Speed ...
=> Remove useless log

src/hadoop-node-manager/deploy/hadoop-node-manager-configuration/yarn-site.xml.template
An enough graceful timeout(65s) for yarn container exit
=> Gracefully stop yarn container

src/webportal/src/app/home/index.jsx
=> [Web Portal] IE11 flexbox bug workaround #2581

src/webportal/src/app/home/index.jsx
https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11
=> [Web Portal] IE11 flexbox bug workaround

src/webportal/src/app/env.js.template, src/webportal/src/app/home/index.jsx, src/webportal/src/app/user/user-logout/user-logout.component.js
webportal has the following logic to inject env.
```
{% if not cluster_cfg['authentication']['OIDC'] %}
- name: AUTHN_METHOD
value: basic
{% else %}
- name: AUTHN_METHOD
value: OIDC
{% endif %}
```
Implement backend logic of login in restserver
=> [Authn] webportal logic to login

src/rest-server/deploy/job-exit-spec-config/job-exit-spec.yaml.template, src/rest-server/deploy/rest-server.yaml.template, src/rest-server/deploy/start.sh.template, src/rest-server/deploy/stop.sh
```
- code: -7151
phrase: CONTAINER_RM_RESYNC_LOST
issuer: PAI_LAUNCHER
causer: PAI_YARN
type: PLATFORM_FAILURE
stage: UNKNOWN
behavior: TRANSIENT_NORMAL
reaction: ALWAYS_RETRY
reason: "Container lost after Launcher AM resynced with YARN RM"
repro:
- "Stop the container's YARN NM"
- "Restart YARN RM"
solution:
- "Wait result from next retry"
- "Contact Cluster Admin"
- code: -7152
phrase: CONTAINER_RM_RESYNC_EXCEEDED
issuer: PAI_LAUNCHER
causer: PAI_YARN
type: PLATFORM_FAILURE
stage: UNKNOWN
behavior: NON_TRANSIENT
reaction: NEVER_RETRY
reason: "Container exceeded after Launcher AM resynced with YARN RM"
repro:
- "Stop the container's YARN NM"
- "Restart YARN RM"
- "Wait until AM releases container"
- "Start the container's YARN NM"
solution:
- "Wait result from next retry"
- "Contact …
```
=> Generate config yaml file based on error exit spec.

README.md, README_zh_CN.md, docs/upgrade/upgrade_to_v0.12.md
=> update upgrade doc for v0.12

src/cleaner/deploy/cleaner.yaml.template, src/cleaner/scripts/clean_docker.py
Add error spec as file when kill container.
=> Add error spec as file when kill container.

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/util.js
Disable clone for old yaml jobs.
Do not support protocol job at present.
=> [Webportal] Disable clone for old yaml jobs

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
@Scarlett does this merge to master branch?
=> [Hotfix]Hide task role status

contrib/submit-protocol/src/App/MarketplaceForm.tsx, contrib/submit-protocol/src/App/ProtocolForm.tsx
Add marketplace dropdown in submission form.
=> [Protocol Plugin] Add marketplace dropdown in submission form

docs/rest-server/runtime-exit-spec.md, src/cleaner/scripts/clean_docker.py, src/rest-server/src/templates/dockerContainerScript.mustache, src/rest-server/src/templates/yarnContainerScript.mustache
1. make sure user error output will redirect to stderr
2. Remove some useless error message
3. Correct error info
Testing Done:
Tested in singlebox
=> Fix runtime errorspec issues

src/rest-server/src/controllers/user.js, src/rest-server/src/routes/user.js, src/rest-server/test/userManagement.js, src/webportal/package.json, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
Job List Status filter should list all the status  https://github.com/Microsoft/pai/issues/2535
=> fix job list status filter bug

contrib/submit-protocol/src/App/ProtocolForm.tsx, contrib/submit-protocol/src/App/index.tsx, contrib/submit-protocol/src/index.ts, src/rest-server/src/config/v2/protocol.js, src/webportal/config/webportal.py, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js, src/webportal/src/app/job/job-view/fabric/job-detail/util.js
Closes #2589.
* Add plugin id in submit protocol plugin
* Add protocol job clone in webportal, add plugin id to env
* Add extra schema in rest server api v2
=> [Protocol Plugin] Support job clone

src/prometheus/deploy/prometheus-deployment.yaml.template
=> put prometheus data dir in host to avoid lost data during restart

docs/rest-server/API.md, src/rest-server/.eslintrc.js, src/rest-server/package.json, src/rest-server/src/models/job.js, src/rest-server/src/util/env.js, src/rest-server/test/data/exit-spec.yaml, src/rest-server/test/jobDetail.js, src/rest-server/test/setup.js, src/rest-server/yarn.lock
=> [Rest Server] exit spec phase2

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
=> [Web Portal] The url in ssh info needs to be quoted 

src/rest-server/src/models/job.js
=> [Rest Server] Infer TaskStatus after App completed  #2635

src/webportal/package.json, src/webportal/yarn.lock
...to resolve the security vulnerabilities.
=> Upgrade jquery to 3.4.0

src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
=> [Web Portal] fix "View full log" for stdout doesn't work without pylon

contrib/marketplace/package.json, contrib/marketplace/src/App/MarketplaceLayout.tsx, contrib/marketplace/src/App/index.tsx, contrib/marketplace/yarn.lock, contrib/submit-protocol/package.json, contrib/submit-protocol/src/App/MarketplaceForm.tsx, contrib/submit-protocol/src/App/ProtocolForm.tsx, contrib/submit-protocol/yarn.lock
Support marketplace in Azure DevOps repo and GitHub private repo.
=> [Webportal Plugin] Support marketplace in Azure DevOps / private repo

src/rest-server/build/rest-server.dockerfile, src/webportal/build/webportal.dockerfile
`No lockfile found` when building rest server and webportal images, update Dockerfiles.
=> [Build] Update rest server and webportal Dockerfile

src/webportal/config/webpack.common.js, src/webportal/config/webportal.yaml, src/webportal/src/app/layout/layout.component.ejs
Remove entry for preview submission and old marketplace.
Close #2356.
=> [Web Portal] Remove entry for outdated link

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/job-status.jsx, src/webportal/src/app/layout/layout.component.js
=> [Web Portal] fix home page's responsive layout; hide dashboard and virtual cluster sidebar item from user view

docs/user/training.md
I think it's a typo, so I want to fix it.
=> Fix typo in training page

docs/rest-server/API.md
Update rest server api docs for api v2:
- `POST jobs`
- `GET jobs/:frameworkName/config`
=> [Docs] Update rest server api docs for api v2

contrib/marketplace/src/App/MarketplaceLayout.tsx, contrib/submit-protocol/src/App/MarketplaceForm.tsx, contrib/submit-protocol/src/App/ProtocolForm.tsx, contrib/submit-protocol/src/App/index.tsx, contrib/submit-protocol/src/index.ts
Resolve comments in #2780.
* Update default marketplace option in submission form
* Set default view to grid view in marketplace
* Remove subtitle in marketplace
* Remove star icon
* Add apply and discard buttons for uri configuration
* Support copy url from GitHub / DevOps to marketplace directly.
=> [Plugin] Update protocol submission form and marketplace

src/rest-server/src/controllers/v2/job.js
Check duplicate job in submission v2.
=> [Rest Serever] Check duplicate job in submission v2

src/webportal/src/app/user/fabric/batchRegister/Table.jsx, src/webportal/src/app/user/fabric/batchRegister/TopBar.jsx, src/webportal/src/app/user/fabric/userView/Table.jsx, src/webportal/src/app/user/fabric/userView/TopBar.jsx
=> [Web Portal] Modify button styles for user view

src/rest-server/src/controllers/v2/job.js, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
* Fix job clone bug
* Check duplicate job in submission v2
=> [Hotfix] Cherry pick #2836 and #2837

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
=> [Web Portal] fix retry count's margin-top #2845

src/webportal/src/app/home/home/conn.js, src/webportal/src/app/home/index/conn.js, src/webportal/src/app/job/job-submit/job-submit.component.js, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js, src/webportal/src/app/user/change-password/change-password.component.js, src/webportal/src/app/user/fabric/conn.js, src/webportal/src/app/vc/vc.component.js
=> [Web Portal] Fix token authentication bug #2843

src/webportal/src/app/home/home/conn.js, src/webportal/src/app/home/index/conn.js, src/webportal/src/app/job/job-submit/job-submit.component.js, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js, src/webportal/src/app/user/change-password/change-password.component.js, src/webportal/src/app/user/fabric/conn.js, src/webportal/src/app/vc/vc.component.js
#2779 
- fix cookie's expiration date
- Portal will clear the token cache and redirect user to login page (logout) when it receives an unauthorized error
=> [Web Portal] Fix token authentication bug

src/webportal/src/app/user/fabric/userView/BatchPasswordEditor.jsx, src/webportal/src/app/user/fabric/userView/BatchVirtualClustersEditor.jsx, src/webportal/src/app/user/fabric/userView/UserEditor.jsx
#2847 
fix text broken in create/edit user
=> [Web Portal] fix text broken in create/edit user

src/webportal/src/app/user/fabric/userView/BatchPasswordEditor.jsx, src/webportal/src/app/user/fabric/userView/BatchVirtualClustersEditor.jsx, src/webportal/src/app/user/fabric/userView/UserEditor.jsx
=> [Web Portal] fix text broken in create/edit user #2849

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
=> [Web Portal] disable appTrackingUrl button if returned url is nil #2856

src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/user/fabric/batchRegister/Table.jsx, src/webportal/src/app/user/fabric/userView/Table.jsx
=> [Web Portal] tweak disabled action button's background color #2858

src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
- add hint messages if filtered job list is empty
- top bar should not be hidden if clear button is pressed
=> [Web Portal] add hint messages if filtered job list is empty

src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
=> [Web Portal] add hint messages if filtered job list is empty #2862

src/webportal/src/app/user/fabric/batchRegister/index.jsx, src/webportal/src/app/user/fabric/userView/TopBar.jsx, src/webportal/src/app/user/fabric/userView/index.jsx
#2493 
Adjust styles for user managerment, detail info in #2493
=> [Web Portal] Adjust styles for user managerment

src/webportal/src/app/user/fabric/batchRegister/index.jsx, src/webportal/src/app/user/fabric/userView/TopBar.jsx, src/webportal/src/app/user/fabric/userView/index.jsx
=> [Web Portal] Adjust styles for user managerment #2860

src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
=> [Web Portal] fix job list's `vcName` query #2879

src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
=> [Web Portal] fix job list's `vcName` query

src/rest-server/src/models/job.js, src/rest-server/src/models/v2/job.js, src/rest-server/src/templates/yarnContainerScript.mustache
Fix error in Docker runtime detection, add quotation marks.
=> [Rest Server] Fix error in Docker runtime detection

docs/rest-server/API.md, docs/user/storage.md, docs/user/training.md, docs/user/troubleshooting_job.md
Rewording and some format fixes.
=> refine documents

src/rest-server/src/models/vc.js, src/rest-server/test/vc.js
=> [Rest Server] update user's vc permission when create/remove vc

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
1. Number: column header "Number" -> "No."
2. Gpus: show gpu count by default. Popup detailed gpu info on hover.
3. Info: tweak button's padding
=> [Web Portal] Refine job detail page's task list

src/rest-server/src/config/secret.js, src/rest-server/src/config/token.js, src/rest-server/src/config/user.js, src/webportal/src/app/user/fabric/utils.js
Will remove the "draft" after done an e2e test.
=> Add dot and dash to allowed characters in username

src/job-exporter/src/collector.py, src/job-exporter/src/docker_inspect.py, src/job-exporter/test/data/dlts_docker_inspect.json, src/job-exporter/test/test_collector.py, src/job-exporter/test/test_docker_inspect.py
scrape user_email from docker inspect if available. For feature of sending email to users if job idle for a long time.
=> collect DLWS_USER_EMAIL labels if available

src/alert-manager/deploy/alert-configmap.yaml.template
Fixed #2761
[Ref](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-users/p6tMwFomWWE/IrGI4O2NAAAJ)
=> group alerts by alertstate so no firing/resolved in same email

contrib/pai_vscode/CHANGELOG.md, contrib/pai_vscode/package.json
Update version and change log.
=> [VS Code] Update version and change log

src/job-exporter/src/collector.py, src/job-exporter/src/docker_inspect.py, src/job-exporter/test/data/dlts_docker_inspect.json, src/job-exporter/test/test_collector.py, src/job-exporter/test/test_docker_inspect.py
vc info will be used in alert email so user can know where to find their jobs.
=> collect role name/idx and vc info from inspect

src/rest-server/src/models/v2/job/k8s.js
Convert framework response to formats used in job list and detail, keep interface with webportal.
=> [Rest Server] Convert framework response in job list and detail

contrib/marketplace/src/App/MarketplaceLayout.tsx, contrib/submit-job-v2/src/App/MarketplaceForm.tsx
Refine error message for marketplace.
=> [Plugin] Refine error message for marketplace

src/kube-runtime/build/kube-runtime.dockerfile, src/kube-runtime/src/entry, src/kube-runtime/src/init/sshd.sh, src/kube-runtime/src/parse.py, src/kube-runtime/src/prep/ssh.sh, src/kube-runtime/src/run
Port [kube runtime](https://github.com/microsoft/pai/tree/dixu/kube-runtime/src/kube-runtime).
=> Port kube runtime

src/rest-server/src/models/v2/job/yarn.js
Update http errors in get job v2.
=> [Rest Server] Update http errors in get job v2

docs/pai-job-protocol.yaml
Fix port errors in job protocol example.
=> [Docs] Fix errors in job protocol example

contrib/submit-job-v2/src/App/ProtocolForm.tsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
- Add tensorboard support in submit-job-v2 plugins.
- Add a button to show tensorboard page in job-view of webportal.
For reviewers:
I'm not familiar with the front-end. So the code may be immature. Please feel free to correct me.
=> Add tensorboard support

src/rest-server/src/models/v2/job/k8s.js
Add annotations for `userName`, `virtualCluster`, `config` in framework.
=> [Rest Server] Add annotations in framework config

src/rest-server/src/controllers/v2/job.js, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/routes/v2/job.js, src/webportal/src/app/home/home/conn.js, src/webportal/src/app/job/job-submit/job-submit.component.js, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js, src/webportal/src/app/marketplace/job-submit/job-submit.component.js
Integrate webportal with k8s rest server.
=> Integrate webportal with k8s rest server

src/webportal/src/app/components/monaco-hack.scss, src/webportal/src/app/job-submission/components/command-section.jsx, src/webportal/src/app/job-submission/components/controls/key-value-list.jsx, src/webportal/src/app/job-submission/components/docker-section.jsx, src/webportal/src/app/job-submission/components/monaco-text-field.jsx, src/webportal/src/app/job-submission/components/sidebar/env-var.jsx
1. enable monaco text field's auto layout
2. hide monaco aria container
3. fix the bug that contents in pai environment variables list can not be copied.
=> [Web Portal] job submission page css tweak

src/webportal/src/app/job-submission/components/container-size-section.jsx, src/webportal/src/app/job-submission/components/controls/key-value-list.jsx, src/webportal/src/app/job-submission/components/data/custom-mount-list.jsx, src/webportal/src/app/job-submission/job-submission.jsx
- scrollbar position 
- column's min width
=> [Web Portal] Tweak job submission page layout

src/rest-server/src/models/v2/job/k8s.js
Adapt framework state and task state in k8s framework controller.
=> [Rest Server] Adapt framework state and task state in k8s

src/webportal/src/app/job-submission/components/submission-section.jsx, src/webportal/src/app/job-submission/job-submission.jsx, src/webportal/src/app/job-submission/models/data/job-data.js, src/webportal/src/app/job-submission/models/data/mount-directories.js, src/webportal/src/app/job-submission/models/job-protocol.js, src/webportal/src/app/job-submission/models/job-task-role.js, src/webportal/src/app/job-submission/utils/constants.jsx, src/webportal/src/app/job-submission/utils/utils.js
Add workaround for comments in commands
fix clone job job
=> fix clone job bug

contrib/python-sdk/README.md, contrib/python-sdk/openpaisdk/__init__.py, contrib/python-sdk/openpaisdk/cli_factory.py, contrib/python-sdk/openpaisdk/cluster.py, contrib/python-sdk/openpaisdk/command_line.py, contrib/python-sdk/setup.py
update the installing source branch to `master`, and update versioning to `v0.4.00`
=> Sdk 0.4.01 - update documents and versioning

src/webportal/config/webpack.common.js, src/webportal/src/app/components/monaco-editor.jsx, src/webportal/src/app/job-submission/components/command-section.jsx, src/webportal/src/app/job-submission/components/monaco-text-field.jsx, src/webportal/src/app/job-submission/components/tab-form.jsx, src/webportal/src/app/job-submission/job-submission.jsx, src/webportal/src/app/job-submission/models/job-task-role.js, src/webportal/src/app/job-submission/utils/constants.js
- change command sections's default command to placeholder
- add shell syntax highlighting
- change task role section's scroll area
- tweak command section's default height
=> [Web Portal] change command section's default comments to placeholder

src/webportal/src/app/job-submission/models/data/job-data.js
1. correct jobdir
2. add preinstallation
=> fix data command error

src/rest-server/.gitignore, src/rest-server/build/build-pre.sh, src/rest-server/build/rest-server.dockerfile, src/webportal/.gitignore, src/webportal/build/build-pre.sh, src/webportal/build/webportal.dockerfile
Move npm version to dockerfile in rest server and webportal.
=> [Hotfix] Move npm version to dockerfile #3109

src/rest-server/src/controllers/job.js, src/rest-server/src/controllers/v2/virtual-cluster.js, src/rest-server/src/controllers/vc.js, src/rest-server/src/models/v1/virtual-cluster/index.js, src/rest-server/src/models/v1/virtual-cluster/yarn.js, src/rest-server/src/models/v2/virtual-cluster/index.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/rest-server/src/models/v2/virtual-cluster/yarn.js, src/rest-server/src/routes/v2/virtual-cluster.js
Add virtual cluster api for k8s rest server.
=> Add virtual cluster api for k8s rest server

src/webportal/src/app/job-submission/components/data/add-data-source.jsx, src/webportal/src/app/job-submission/components/data/add-git.jsx, src/webportal/src/app/job-submission/components/data/add-hdfs.jsx, src/webportal/src/app/job-submission/components/data/add-http.jsx, src/webportal/src/app/job-submission/components/data/add-local.jsx, src/webportal/src/app/job-submission/components/data/team-mount-list.jsx, src/webportal/src/app/job-submission/utils/constants.js
add hdfs check before into data list refine horizontal alignment
=> refine hdfs check for robustness

src/webportal/src/app/layout/layout.component.ejs
Remove duplicate version prefix on webportal.
=> [Webportal] Remove duplicate version prefix

docs/tools/dedicated_vc.md, src/tools/.gitignore, src/tools/node_maintain.py, src/tools/operator_wrapper/__init__.py, src/tools/operator_wrapper/alert_operator.py, src/tools/operator_wrapper/restserver_operator.py, src/tools/operator_wrapper/yarn_operator.py, src/tools/tests/test_node_maintain.py
=> [Hotfix] Fix AAD group in dedicated vc create/delete

deployment/quick-start/services-configuration.yaml.template, src/rest-server/config/rest-server.md, src/rest-server/config/rest-server.yaml, src/rest-server/config/rest_server.py, src/rest-server/deploy/rest-server.yaml.template, src/rest-server/src/config/launcher.js, src/rest-server/src/models/v2/job/k8s.js
Add launcher-type to service config
Use kube-runtime build in project.
=> Add launcher-type to service config. Use kube-runtime build in project.

src/webportal/src/app/user/fabric/userView/TopBar.jsx, src/webportal/src/app/user/fabric/userView/index.jsx
Change button text from 'Import CSV' to 'Create Bulk Users' in user management
=> [Web Portal] Change 'Import CSV' to 'Create Bulk Users' in user management

src/rest-server/src/controllers/v2/job.js, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/routes/v2/job.js
Support stop framework api in k8s rest server.
=> Support stop framework api in k8s rest server

src/webportal/src/app/user/fabric/userView/index.jsx
Add confirm dialog before batch edit admin's password as Yang Ou's suggestion
=> [Web Portal] Add confirm dialog before batch edit admin's password

src/webportal/src/app/job-submission/utils/webhdfs.js
using pylon when uploading file to avoid cors block by browser
=> hot fix for hdfs CORS problem

src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
=> [Web Portal] fix stdout/stderr's full log link bug when pylon is not used

src/rest-server/src/models/v2/job/k8s.js
Add stopped state using exit code.
=> [Rest Server] Add stopped state

docs/zh_CN/pai-management/doc/how-to-install-depdencey.md
some older packages cannot work
=> update python packages

src/rest-server/src/models/v2/job/k8s.js, src/webportal/src/app/components/status-badge.jsx, src/webportal/src/app/components/util/job.js, src/webportal/src/app/home/home/job-status.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/util.js
Add completing state for job and tasks.
=> [Rest Server] Add completing state for job and tasks

docs/pai-job-protocol.yaml, src/rest-server/src/config/v2/protocol.js
Update varibale naming in protocol schema.
=> [Rest Server] Update variable naming in protocol schema

src/webportal/.gitignore, src/webportal/config/webpack.common.js, src/webportal/package.json, src/webportal/yarn.lock
Test case: enter the home page and then enter the job list page, this will cause the job list page to reuse some modules from the home page.
* These test cases are run in different environments, please only refer the transfer size but not the time.
Before:
After:
For further optimization, adding backend pagination to the job list works well.
=> [Web Portal] Bundle shared modules into independence chunks.

src/rest-server/deploy/rest-server.yaml.template, src/rest-server/src/config/launcher.js, src/rest-server/src/config/v2/hived.js, src/rest-server/src/config/v2/protocol.js, src/rest-server/src/config/vc.js, src/rest-server/src/controllers/v2/virtual-cluster.js, src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/middlewares/v2/protocol.js, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/virtual-cluster/index.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/rest-server/src/models/v2/virtual-cluster/yarn.js, src/rest-server/src/routes/v2/virtual-cluster.js, src/rest-server/src/utils/error.d.ts
1. Add deployment flag to enable/disable hived
2. Validate memory/cpu in hived mode
3. Add resource unit api to query cluster sku
=> [Pure k8s] add scheduler validation in restserver

docs/rest-server/API.md, src/rest-server/package.json, src/rest-server/src/controllers/job.js, src/rest-server/src/controllers/v2/job.js, src/rest-server/src/models/v2/job/yarn.js, src/rest-server/src/utils/converter.js, src/rest-server/test/jobConfig.js
Fix authentication file issue in protocol converter.
=> [Rest Server] Fix auth file issue in protocol converter

src/rest-server/src/templates/dockerContainerScript.mustache
=> fix hadoop env missing

contrib/python-sdk/README.md, contrib/python-sdk/openpaisdk/cluster.py, contrib/python-sdk/openpaisdk/command_line.py, contrib/python-sdk/openpaisdk/job.py, contrib/python-sdk/openpaisdk/utils.py, contrib/python-sdk/setup.py
1. add methods to check available resources
2. update codes to dump requests in debugging mode
=> add methods to check available resources

contrib/samba-aad-server/README.md, contrib/samba-aad-server/build.sh, contrib/samba-aad-server/build/Dockerfile, contrib/samba-aad-server/build/default, contrib/samba-aad-server/build/infosrv/domaininfo.py, contrib/samba-aad-server/build/infosrv/uwsgi.ini, contrib/samba-aad-server/build/krb5.conf, contrib/samba-aad-server/build/nsswitch.conf, contrib/samba-aad-server/build/run.sh, contrib/samba-aad-server/build/sambadatacreate, contrib/samba-aad-server/build/sambauserhomecreate, contrib/samba-aad-server/build/smb.conf, contrib/samba-aad-server/start.sh
A sample of samba server with AAD integration.
usage:
```
./build.sh
./start.sh <DOMAIN> <DOMAINUSER> <DOMAINPWD> <PAISMBUSER> <PAISMBPWD>
```
=> Example of samba server with AAD

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
Please refer the pic, add button to retrieve  merged log
=> add button to retrieve merged log

subprojects/hivedscheduler/README.md
@fanyangCS @mzmssg @zhypku , please feel free to enrich and refine this README.
=> [HivedScheduler]: Add Basic README

src/webportal/src/app/job/job-view/fabric/JobList/FilterButton.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx
=> [Web Portal] refine job list page's filters

contrib/pai_vscode/src/pai/container/jobListTreeView.ts
Current job list refresh logic will always show error message while the cluster is down.
After the fix, error message will only show one time.
=> [VS Code] Fix refresh job list

.github/workflows/continuous-integration.yml, .github/workflows/nodejs.yml, .travis.yml
Add a nodejs workflow to test GitHub Actions.
=> Add a nodejs workflow for GitHub Actions

.github/workflows/continuous-integration.yml, .github/workflows/lint.yml
Migrate CI from Travis to GitHub Actions.
=> Migrate CI from Travis to GitHub Actions

src/dev-box/build/dev-box.dockerfile, src/rest-server/deploy/rest-server.yaml.template
Fix rest server template error in k8s PAI.
=> Fix rest server template error in k8s PAI

src/rest-server/src/models/v1/job/yarn.js
Fix stop job access control error in v1 api.
=> [Rest Server] Fix stop job access control error

src/rest-server/src/utils/converter.js, src/rest-server/test/converter.js
Fix `defaults` field in config converter.
=> [Rest Server] Fix `defaults` field in config converter

src/rest-server/src/models/v2/job/k8s.js, src/webportal/src/app/components/status-badge.jsx, src/webportal/src/app/components/util/job.js, src/webportal/src/app/home/home/job-status.jsx, src/webportal/src/app/job/job-view/fabric/JobList/utils.js
Add retry pending state and expose `retryDelayTime`.
Closes #3376.
=> [Rest Server] Add retry pending state for k8s job and tasks

src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/job/yarn.js
Set shared memory size for k8s pod jobs #3358.
=> [Rest Server] Set shared memory size for k8s pod jobs

src/rest-server/src/controllers/v2/user.js
Return 403 error for illegal user
=> Refine aad user login error

src/webportal/src/app/job/job-view/fabric/JobList/StopJobConfirm.jsx, src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
=> [webportal]add stop job confirm

src/rest-server/src/models/v2/job/k8s.js
=> Check available vc in k8s job submission

contrib/storage_plugin/README.MD, contrib/storage_plugin/storagectl.md, src/webportal/src/app/job-submission/components/data/team-detail.jsx, src/webportal/src/app/job-submission/components/data/team-storage.jsx, src/webportal/src/app/job-submission/models/data/mount-directories.js, src/webportal/src/app/job-submission/models/data/team-data-list.js, src/webportal/src/app/job-submission/utils/constants.js
Show all usable team storage in Data section.
Click detail to view team storage details.
Write usage hint for team storage support file systems.
=> Refine team share storage in Job submission page.

src/dev-box/.gitignore, src/pylon/.gitignore, src/rest-server/src/models/v2/job/k8s.js, src/webportal/src/app/job-submission/components/task-roles.jsx, src/webportal/src/app/job-submission/job-submission.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/src/app/layout/layout.component.js
* ignore modified files during deployment in git
* fix typo `retryPolicy` -> `retryPolicyStatus`
* fix incompatible default task role name
* rename "Go to Yarn Tracking Page"
* convert task role names in log path
* change `alert` to `prompt` in view token
=> Fix bugs in pure k8s

src/webportal/src/app/user/fabric/batchRegister/Table.jsx, src/webportal/src/app/user/fabric/batchRegister/TableTextField.jsx, src/webportal/src/app/user/fabric/components/CustomPassword.jsx, src/webportal/src/app/user/fabric/userView/BatchPasswordEditor.jsx, src/webportal/src/app/user/fabric/userView/UserEditor.jsx
Generate a random initial password for new user
#3133
=> [WebPortal] Generate a random initial password for new user

src/webportal/src/app/home/home/abnormal-job-list.jsx
=> fix bug: when stopping abnormal job, the status not change

src/webportal/src/app/job-submission/models/job-task-role.js
=> [Web Portal] fix clone job type error bug #3453

src/rest-server/src/models/v2/group.js
=> Check groups every time restserver start

src/webportal/src/app/job-submission/components/form-style.js, src/webportal/src/app/job-submission/components/tab-form.jsx, src/webportal/src/app/job-submission/components/topbar/export-config.jsx, src/webportal/src/app/job-submission/components/topbar/import-config.jsx, src/webportal/src/app/job-submission/components/topbar/topbar.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx
- submission page's unnecessary vertical scrollbar
- form card's bottom shadow
- import/export button's hover effect
=> [Web Portal] tweak job submission page's layout

src/rest-server/src/models/v2/group.js
=> [Hotfix] Check groups every time restserver start

src/job-exporter/src/collector.py, src/job-exporter/src/nvidia.py, src/job-exporter/test/data/nvidia_smi_retired_pages.xml, src/job-exporter/test/test_nvidia.py
expose `nvidia-smi -q -d  PAGE_RETIREMENT` number as `nvidiasmi_retired_page_count`
=> expose nvidiasmi_retired_page_count

src/webportal/src/app/home/home/abnormal-job-list.jsx, src/webportal/src/app/home/home/utilization-chart.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Fix home page layout. Same as #3471
=> fix layout (#3471)

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/abnormal-job-list.jsx, src/webportal/src/app/home/home/job-status.jsx, src/webportal/src/app/home/home/recent-job-list.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
=> [Web Portal] tweak home page's layout #3488

src/pylon/deploy/pylon-config/location.conf.template, src/webportal/src/app/layout/alerts.jsx
=> not show alert when alert-manager not deployed

src/rest-server/src/models/v1/job/yarn.js
Fix ACL issue in stopping jobs.
=> [Hotfix] Fix ACL issue in stopping jobs #3516

src/rest-server/src/models/v1/job/yarn.js
Fix ACL issue in stopping jobs.
=> [Rest Server] Fix ACL issue in stopping jobs

src/webportal/src/app/job-submission/components/tools/tensorboard.jsx
=> [TensorBoard]Fix TensorBoard bug

src/rest-server/src/models/v2/job/yarn.js
Fix hdfs container directory permission issue, potential race condition.
=> [Rest Server] Fix hdfs container directory permission issue

src/webportal/src/app/job/job-view/fabric/JobList/FilterButton.jsx, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx
- use SearchBox control instead of TextField
- use italic font style for searchbox's placeholder
- stick `@Me` to the top of user list
=> [Web Portal] tweak job list's user filter

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/abnormal-job-list.jsx, src/webportal/src/app/home/home/job-status.jsx, src/webportal/src/app/home/home/recent-job-list.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
- recent/abnormal job list's height
- responsive layout
=> [Web Portal] tweak home page's layout

src/webportal/src/app/layout/layout.component.ejs, src/webportal/src/app/layout/layout.component.js
=> [Web Portal] hide admin's sidebar item by default

src/webportal/src/app/home/home/recent-job-list.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
- fix typo
- rencent -> recent
- job list's error message bar
- overlay -> main layer
- auto dismissed after 1 sec -> need to be closed manually
=> [Web Portal] fix typo; change job list's error message bar's dismiss behavior

src/webportal/src/app/home/home/recent-job-list.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx
=> [Web Portal] fix typo; change job list's error message bar's dismiss behavior #3506

src/webportal/src/app/job-submission/components/tab-form-content.jsx, src/webportal/src/app/job-submission/models/job-task-role.js
=>  [Web Portal] support editing task role's hidden fields in yaml editor #3513 

src/rest-server/src/models/v2/job/yarn.js
Fix hdfs container directory permission issue.
=> [Hotfix] Fix hdfs container directory permission issue

src/webportal/src/app/home/home/abnormal-job-list.jsx
disable stop button when job is stopping
=> disable stop button when job is stopping

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/src/app/layout/alerts.jsx
=> ignore alerts not found error and add notice for all logs

src/rest-server/src/controllers/v2/user.js, src/rest-server/src/models/v2/group.js, src/rest-server/src/models/v2/user.js
1. check groups when creating user, updating user grouplist, adding group to user grouplist.
2. remove nonexistent groups from user grouplist every time restserver start.
=> [hotfix] check group existence when updating user grouplist

src/rest-server/src/controllers/v2/user.js, src/rest-server/src/models/v2/group.js, src/rest-server/src/models/v2/user.js
=> [hotfix] check group existence when updating user grouplist (#3498)

docs/user/job_submission.md, src/webportal/config/preprocess.js
https://github.com/microsoft/pai/issues/3464
=> Fix help docs on the webportal

contrib/notebook-extension/README.md, contrib/notebook-extension/openpai_submitter/main.py, contrib/notebook-extension/openpai_submitter/scripts/interface.js, contrib/notebook-extension/openpai_submitter/scripts/panel.js, contrib/notebook-extension/openpai_submitter/scripts/panel_recent.js, contrib/notebook-extension/openpai_submitter/scripts/utils.js
**1. More friendly hint for user:**
**2. Add content for how to edit your cluster settings:**
**3. Lazy loading of resources to accelerate the submitter:**
=> fix jupyter notebook extension

deployment/paiLibrary/paiService/service_template_generate.py
Fix error `StatefulSet` kind in template generation.
=> [Deployment] Fix error StatefulSet kind in template generation

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/abnormal-job-list.jsx, src/webportal/src/app/home/home/resource-bar.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
=> Change admin home page layout

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/abnormal-job-list.jsx, src/webportal/src/app/home/home/resource-bar.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
fix home page layout, cherry pick commit. Same as #3552
=> Change admin home page layout (#3552)

docs/user/remote_develeoment.md
=> [Doc] Add code preparation

src/rest-server/src/routes/user.js
Fix legacy job router issue in k8s.
=> [Rest Server] Fix legacy job router issue in k8s

deployment/k8sPaiLibrary/maintainlib/common.py
Remove password from stdin in paictl.
Close #729.
=> [Deployment] Remove password from stdin in paictl

src/webportal/.gitignore, src/webportal/package.json, src/webportal/src/app/components/monaco-panel.jsx, src/webportal/src/app/job-submission/components/submission-section.jsx, src/webportal/src/app/job-submission/components/topbar/import-config.jsx, src/webportal/src/app/job-submission/components/topbar/topbar.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx, src/webportal/src/app/job-submission/job-submission.jsx, src/webportal/src/app/job-submission/models/job-protocol.js, src/webportal/yarn.lock
=> add react router in wizard and add save button when edit yaml #3553

src/webportal/package.json, src/webportal/src/app/components/monaco-panel.jsx, src/webportal/src/app/job-submission/components/submission-section.jsx, src/webportal/src/app/job-submission/components/topbar/import-config.jsx, src/webportal/src/app/job-submission/components/topbar/topbar.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx, src/webportal/src/app/job-submission/job-submission.jsx, src/webportal/src/app/job-submission/models/job-protocol.js, src/webportal/yarn.lock
1. add react router in wizard
2. import config from single page will redirect to general page
3. add save button in yaml editor
4. add validation when import illegal yaml file
5. move init function to top
=> add react router in wizard and add save button when edit yaml

src/webportal/src/app/job/job-view/fabric/job-detail/conn.js
Use v1 api in fetchRawJobConfig.
=> [Webportal] Use v1 api in fetchRawJobConfig

src/rest-server/src/models/v2/job/runtime-env.js
Change PAI_JOB_NAME to framework name.
Fixes #3546.
=> [Rest Server] Change PAI_JOB_NAME to framework name

src/hivedscheduler/deploy/start.sh, src/rest-server/deploy/rest-server.yaml.template, src/rest-server/deploy/service.yaml
Fix rest server deployment issues in k8s.
=> Fix rest server deployment issues in k8s

src/webportal/deploy/webportal.yaml.template, src/webportal/src/app/env.js.template, src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx, src/webportal/src/app/layout/layout.component.js
#3206 
- Virtual Cluster
- Job Detail -> application tracking page link
- Job Detail -> job attempts page link
=> [Pure K8S][Web Portal] Hide pages and links that are not supported in pure k8s version

marketplace-v2/keras-tensorflow-mnist.yaml, marketplace-v2/pytorch-mnist.yaml, marketplace-v2/tensorflow-cifar10.yaml
Update marketplace job to be compatible with k8s.
=> [Examples] Update marketplace job to be compatible with k8s

marketplace-v2/horovod-pytorch-synthetic-benchmark.yaml
Add a horovod mpi example in marketplace.
=> [Examples] Add a horovod mpi example in marketplace

src/rest-server/src/middlewares/v2/hived.js
Fix bug in hived resources calculation.
=> [Rest Server] Fix bug in hived resources calculation

src/webportal/src/app/job-submission/components/tools/job-ssh.jsx, src/webportal/src/app/job-submission/components/tools/tool-component.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx, src/webportal/src/app/job-submission/models/plugin/ssh-plugin.js, src/webportal/src/app/job-submission/utils/constants.js
User can input public key for jobs.
Enable job-wise SSH by default.
=> [pure k8s] Add SSH config to webportal for pure-k8s based PAI

src/webportal/src/app/job-submission/job-submission-page.jsx, src/webportal/src/app/job-submission/utils/utils.js, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
- Hide ssh info panel if pure-k8s enabled
- Add alert message if cloned/imported job config has masked secret field
=> [Web Portal] Hide ssh info panel if pure-k8s enabled; Add alert message if cloned/imported job config has masked secret field

src/kube-runtime/build/kube-runtime.dockerfile
=> Change pyaml to PyYAML

src/rest-server/src/routes/index.js, src/rest-server/src/routes/rewrite.js
Add user api rewrite for legacy jobs in k8s.
=> [Rest Servre] Add user api rewrite for legacy jobs in k8s

deployment/checkCmd.py, deployment/confStorage/conf_storage_util.py, deployment/confStorage/external_version_control/external_config.py, deployment/k8sPaiLibrary/maintainlib/common.py, deployment/k8sPaiLibrary/maintainlib/update.py, deployment/layoutCmd.py, deployment/paiLibrary/common/file_handler.py, deployment/paiLibrary/paiService/service_template_generate.py, deployment/tools/configMigration.py, deployment/tools/pluginIdMigration.py
* Use `sudo -S` to read password from stdin
* Update deprecated `yaml.load()`
=> [Deployment] Fix paictl issues during deployment

src/rest-server/deploy/rest-server.yaml.template
Skip hived config mount in default scheduler.
=> [Rest Server] Skip hived config mount in default scheduler

src/kube-runtime/build/kube-runtime.dockerfile, src/kube-runtime/src/init
Aggregate init container logs to init.log
=> Refine k8s init container logs

src/rest-server/src/config/vc.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/rest-server/src/utils/k8sUtils.js
Fix total GPU number when there're invalid GPUs.
=> [Rest Server] Fix total GPU number when there're invalid GPUs

src/rest-server/src/config/launcher.js, src/rest-server/src/models/v2/job/k8s.js
Add graceful deletion timeout in submission config.
=> [Rest Server] Add graceful deletion timeout in submission config

src/frameworkcontroller/deploy/frameworkcontroller.yaml.template, src/kube-runtime/build/kube-runtime.dockerfile
v0.4.0-alpha.0:
https://github.com/microsoft/frameworkcontroller/tree/77ec4abbdc194f8964d68cfd5b9780a7a87b06e6
Including ExitSpec and Force Deletion
=> [FC]: Update FC image to v0.4.0-alpha.0

src/webportal/src/app/cluster-view/services/service-info.js, src/webportal/src/app/cluster-view/services/services.component.js
Refer to https://github.com/webpack/webpack/issues/4039#issuecomment-273804003
Solve following error
=> fix service page not disply issue

src/webportal/src/app/job-submission/components/submission-section.jsx
Disable 'Back' button when cloning
=> Disable 'Back' button when cloning

src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/user/fabric/batchRegister/Table.jsx, src/webportal/src/app/user/fabric/userView/Table.jsx, src/webportal/src/app/user/fabric/userView/TopBar.jsx
[related issue](https://github.com/prettier/prettier/issues/6487#issuecomment-533099418)
=> Fix prettier formatting error with jsdoc head

src/webportal/src/app/components/monaco-editor.jsx, src/webportal/src/app/home/home.jsx, src/webportal/src/app/job-submission/components/command-section.jsx, src/webportal/src/app/job-submission/components/monaco-text-field.jsx, src/webportal/src/app/job-submission/components/sidebar/sidebar-card.jsx, src/webportal/src/app/job-submission/components/tab-form.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx
Fix the glitches on edge beta / old version chromium
Affected pages
- Home Page
- Job Submission Page
- Task Config Form
- Sidebar Cards
=> [Web Portal] edge beta (old version chromium) compatibility

src/webportal/src/app/layout/alerts.jsx, src/webportal/src/app/layout/layout.component.js
Fix react layout issue in non-admin home page, which will block
rendering alert panel and plugins.
=> [Webportal] Fix react layout issue in non-admin home page

src/rest-server/src/models/v2/virtual-cluster/k8s.js
Fix used gpu number error in default scheduler.
=> [Rest Server] Fix used gpu number error in default scheduler

src/webportal/src/app/layout/layout.component.js
Hide grafana dashboard in k8s webportal.
Close #3685.
=> [Webportal] Hide grafana dashboard in k8s webportal

src/rest-server/src/models/v2/job/k8s.js
Fix total gpu number in job summary.
=> [Rest Server] Fix total gpu number in job summary

src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Refer to issue https://github.com/microsoft/pai/issues/3686
fixes #3686
=> fix VC view link bug

src/frameworkcontroller/deploy/frameworkcontroller.yaml.template, src/kube-runtime/build/kube-runtime.dockerfile
[FC v0.4.0 Release Notes](https://github.com/microsoft/frameworkcontroller/releases/tag/v0.4.0)
=> [FC]: Update FC image to official v0.4.0

src/rest-server/src/models/v2/virtual-cluster/k8s.js
Exclude unready node resources in virtual cluster.
=> [Rest Server] Exclude unready node resources in virtual cluster

deployment/k8sPaiLibrary/template/apiserver.yaml.template
See https://github.com/microsoft/pai/issues/3703#issuecomment-540879683
=> Tune ApiServer for larger workload

src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/job/runtime-env.js, src/webportal/src/app/job-submission/components/task-role/completion-policy.jsx, src/webportal/src/app/job-submission/models/completion.js, src/webportal/src/app/job-submission/models/protocol-schema.js
* Support `null` in framework completion policy.
* Update UI for completion policy.
=> Support null in framework completion policy

deployment/k8sPaiLibrary/maintaintool/update_resource.py, deployment/k8sPaiLibrary/monitorTool/update_resource.py, src/frameworkcontroller/deploy/delete.sh, src/frameworkcontroller/deploy/frameworkcontroller.yaml.template, src/frameworkcontroller/deploy/rbac.yaml, src/frameworkcontroller/deploy/service.yaml, src/frameworkcontroller/deploy/stop.sh, src/frameworkcontroller/deploy/stop.sh.template, src/hivedscheduler/deploy/hivedscheduler-config.yaml.template, src/hivedscheduler/deploy/hivedscheduler.yaml.template, src/hivedscheduler/deploy/service.yaml, src/hivedscheduler/deploy/stop.sh.template, src/kube-runtime/deploy/delete.sh, src/kube-runtime/deploy/rbac.yaml, src/kube-runtime/deploy/service.yaml, src/kube-runtime/deploy/stop.sh, src/rest-server/src/models/v2/job/k8s.js
Support framework controller and hived scheduler deployment in RBAC.
=> Support k8s services deployment in RBAC

src/rest-server/deploy/rbac.yaml, src/rest-server/deploy/stop.sh, src/rest-server/src/config/launcher.js, src/rest-server/src/config/vc.js, src/rest-server/src/models/v2/job/index.js, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js
Fix apiserver requests in RBAC.
=> [Rest Server] Fix apiserver requests in RBAC

src/kube-runtime/src/plugins/ssh/sshd.sh
Fix sshd issues in k8s runtime.
=> Fix sshd issues in k8s runtime

src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/models/v2/job/k8s.js
Add pod priority to support FIFO job scheduling.
Closes #3704.
=> [Rest Server] Add pod priority to support FIFO job scheduling

src/rest-server/src/models/v2/job/k8s.js
Simplify error message for long job name.
Closes #3746.
=> [Rest Server] Simplify error message for long job name

examples/cluster-configuration/services-configuration.yaml, src/cluster/config/cluster.md, src/cluster/config/cluster.py, src/cluster/config/cluster.yaml, src/job-exporter/deploy/job-exporter.yaml.template, src/job-exporter/src/main.py
Refer to issue: https://github.com/Azure/AKS/issues/1271
Copy nvidia-smi from /usr/local/nvidia/bin to /usr/local/bin will solve the problem.
=> Enable  nvidia-smi command in AKS

deployment/clusterObjectModel/test/data/configuration-template-generate/services-configuration.yaml, examples/cluster-configuration/services-configuration.yaml, src/device-plugin/config/device-plugin.yaml, src/device-plugin/config/device_plugin.py, src/device-plugin/deploy/delete.sh, src/device-plugin/deploy/delete.sh.template, src/device-plugin/deploy/start.sh, src/device-plugin/deploy/start.sh.template, src/device-plugin/deploy/stop.sh, src/hivedscheduler/deploy/start.sh.template, src/hivedscheduler/deploy/stop.sh.template
Move GPU device plugin to service.
=> Move GPU device plugin to service

src/rest-server/src/controllers/v2/job.js, src/rest-server/src/models/v2/job/k8s.js
Add label selector for framework username.
Closes #3738.
=> [Rest Server] Add label selector for framework username

contrib/python-sdk/openpaisdk/utils.py
in requests.request add `verify=False` to disable SSL cert checking in https
=> support https in requests

src/webportal/src/app/job-submission/models/data/mount-directories.js
Install curl for ubuntu 18.04 compatibility.
Remove unnecessary package install.
Remove blobEndPoint for azure blob since it is not mandatory
=> Install curl for azureblob for ubuntu 18.04

src/webportal/src/app/job-submission/models/job-protocol.js
Fix bug: #3434 When import config to submit job. Some additional fields in prerequisites will missing.
fixes #3434
=> Fix bug: allow addition info in prerequisites

src/rest-server/src/models/v2/job/k8s.js
Add task retry count for elastic jobs.
Closes #3781.
=> [Rest Server] Add task retry count for elastic jobs

src/rest-server/src/utils/error.d.ts, src/rest-server/src/utils/manager/storage/crudK8sSecret.js, src/webportal/src/app/job-submission/utils/conn.js
Make 'empty' as system reserved key for storage server and storage config
=> Make 'empty' as system reserved key for storage server and storage config

src/pylon/build/pylon.dockerfile, src/pylon/deploy/pylon-config/nginx.conf.template
Add access rules example in pylon config.
=> [Pylon] Add access rules example in pylon config

docs/rest-server/API.md, src/rest-server/src/controllers/v2/storage.js, src/rest-server/src/routes/v2/storage.js, src/webportal/src/app/job-submission/utils/conn.js
Change query storage configs/servers rest-apis to GET
=> Change query storage configs/servers rest-apis to GET

src/webportal/src/app/job-submission/components/tools/job-ssh.jsx, src/webportal/src/app/job-submission/components/tools/tool-component.jsx, src/webportal/src/app/job-submission/job-submission-page.jsx, src/webportal/src/app/job-submission/models/plugin/ssh-plugin.js
Remove secret ref from ssh plugin
=> Remove secret ref from ssh plugin

src/rest-server/src/utils/manager/storage/storage.js
=> Fix HDFS Schema

deployment/k8sPaiLibrary/maintainconf/add.yaml, deployment/k8sPaiLibrary/template/kubelet.service.template
Fix kubelet.service in add machines.
=> [Deployment] Fix kubelet.service in add machines

contrib/storage_plugin/storagectl.md, contrib/storage_plugin/storagectl.py
Fix error when group extension.acls.storageConfigs is not init.
Fix docs
=> Storage CLI bug fix

src/rest-server/src/models/v2/job/k8s.js
Mask secret in framework annotations.
=> [Rest Server] Mask secret in framework annotations

src/rest-server/src/config/v2/hived.js, src/rest-server/src/middlewares/v2/hived.js
Update hived config validation.
=> [Rest Server] Update hived config validation

examples/cluster-configuration/services-configuration.yaml, src/cluster/config/cluster.yaml, src/fluentd/deploy/fluentd-config.yaml.template, src/frameworkcontroller/deploy/frameworkcontroller.yaml.template, src/kube-runtime/build/kube-runtime.dockerfile
1. Fix FC may log invalid json to history
2. Fix history snapshot may lost during FC Pod upgrade
=> Improve job history pipeline fault tolerance

src/device-plugin/README.md, src/device-plugin/deploy/delete.sh.template, src/device-plugin/deploy/device-plugin.yaml, src/device-plugin/deploy/start.sh.template, src/rest-server/src/models/v2/job/k8s.js
Add device plugin for host devices under `/dev`.
=> Add device plugin for host devices

src/rest-server/src/models/v2/job/yarn.js
Make -1 compatible in yarn launcher completion policy.
=> [Rest Server] Make -1 compatible in launcher completion policy

src/rest-server/src/models/v2/job/k8s.js, src/webportal/src/app/components/util/job.js, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role.jsx
=> Add stopping status to task

src/rest-server/src/models/v2/job/k8s.js
Mock framework status before the status is updated.
=> [Rest Server] Mock framework status before the status is updated

src/webportal/config/webpack.common.js, src/webportal/package.json, src/webportal/src/app/components/monaco-editor.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/yarn.lock
=> [Web Portal] lazy loading of monaco editor component

contrib/kubespray/clean-env.md, contrib/kubespray/readme.md
- document
- Anible-playbooks
- cluster env apt fix
- remove nvidia drivers installed by OpenPAI
- remove the docker installation of OpenPAI.
=> [kubespray] Add document to help user clean their environment 

contrib/kubespray/clean-env.md, contrib/kubespray/readme.md
* [kubespray] Add document to help user clean their environment with ansible
=> [kubespray] update doc to clean up cluster

src/cluster/config/cluster.yaml, src/fluentd/deploy/fluentd.yaml.template
=> [Docker] add cluster-level configuration of docker-data-root

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go
count reserved cells in total quota
=> HiveD: fix bug in initial assignment validation

src/rest-server/src/middlewares/v2/hived.js
* Fix taskRoles undefined bug
* Update max gpu check
* Set default priority to test
=> [Rest Server] Update hived validation

src/rest-server/src/middlewares/v2/hived.js
* Fix taskRoles undefined bug
* Update max gpu check
* Set default priority to test
=> [Hotfix] Update hived validation (#3911)

src/webportal/src/app/job-submission/components/submission-section.jsx, src/webportal/src/app/job-submission/components/topbar/export-config.jsx, src/webportal/src/app/job-submission/utils/utils.js
In original code: 
```javascript  
if (!jobData.containData) {
return;
}
```
If job data.containData is false,  the tensorboard command will not be prefixed.
closes #3796
=> Fix tensorboard precommand bug

src/hivedscheduler/deploy/hivedscheduler-config.yaml.template, src/hivedscheduler/deploy/hivedscheduler-service.yaml, src/hivedscheduler/deploy/stop.sh.template, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/example/run/deploy.yaml, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/intra_vc_scheduler.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/types.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/constants.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/api/types.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/types.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/utils.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/webserver/webserver.go
Resolves https://github.com/microsoft/pai/issues/3850
=> [Hived]: Expose LazyPreemptionStatus

src/rest-server/src/models/v2/job/k8s.js
Specify image pull policy for app container.
=> [Rest Server] Specify image pull policy for app container

src/rest-server/src/middlewares/v2/hived.js
Check resource quota for gang scheduling only.
=> [Rest Server] Check resource quota for gang scheduling only

contrib/pai_vscode/schemas/pai_cluster.schema.json, contrib/pai_vscode/src/pai/clusterManager.ts
VS Code extension got unexpected token E in JSON error #3912
=> [VS Code] Fix add cluster bug when connection timeout

src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx
https://medium.com/javascript-in-plain-english/how-to-use-async-function-in-react-hook-useeffect-typescript-js-6204a788a435
=> [Web Portal] fix react hook warning

src/rest-server/src/models/v2/job/k8s.js
Specify image pull policy for app container.
=> [Hotfix] Specify image pull policy for app container (#3933)

src/rest-server/src/middlewares/v2/hived.js
Check resource quota for gang scheduling and skip check for oppo.
=> [Hotfix] Check resource quota for gang scheduling

src/rest-server/src/config/launcher.js, src/rest-server/src/models/v2/job/k8s.js
Add image pull secrets for private registry.
Limitation: Do not support multiple users for same registry like `.docker/config.json`. Multiple registries in one job is fine.
=> [Rest Server] Add image pull secrets for private registry

src/rest-server/src/config/launcher.js, src/rest-server/src/models/v2/job/k8s.js
Add image pull secrets for private registry.
=> [Hotfix] Add image pull secrets for private registry (#3943)

src/rest-server/src/middlewares/v2/hived.js
Add critical priority in hived.
=> [Hotfix] Add critical priority in hived (#3949)

src/rest-server/src/middlewares/v2/hived.js
Add critical priority in hived.
=> [Rest Server] Add critical priority in hived

subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/hived_algorithm_test.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/intra_vc_scheduler.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/algorithm/topology_aware_scheduler.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/internal/types.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/scheduler/scheduler.go, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/pkg/webserver/webserver.go
=> [Hived]: Expose and Refine Pod Waiting Reason

marketplace-v2/horovod-pytorch-synthetic-benchmark.yaml
Shorten name to fit backend restrict.
=> [Examples] Shorten name to fit backend restrict

src/rest-server/src/config/vc.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Add available resources for low priotity cluster.
=> [Rest Server] Add available resources for low priotity cluster

src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/middlewares/v2/protocol.js
Fix duplicate affinity group name issue.
=> [Rest Server] Fix duplicate affinity group name issue

src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/middlewares/v2/protocol.js
Fix duplicate affinity group name issue.
=> [Hotfix] Fix duplicate affinity group name issue (#3971)

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
Add more error patterns
Enable to recognize more type of errors
=> Add more error patterns

docs/pai-job-protocol.yaml, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/job/runtime-env.js, src/rest-server/src/models/v2/job/yarn.js
Update default completion policy, set `minSucceededInstances` to task instances by default.
=> [Rest Server] Update default completion policy

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml, src/kube-runtime/src/init, src/kube-runtime/src/init.d/image_checker.py, src/kube-runtime/test/docker_image_auth.yaml, src/kube-runtime/test/docker_image_local_registry.yaml, src/kube-runtime/test/docker_image_no_exist.yaml, src/kube-runtime/test/docker_image_no_tag.yaml, src/kube-runtime/test/docker_image_no_user_tag.yaml, src/kube-runtime/test/test_image_checker.py
=> [runtime] add docker image checker (#3974)

contrib/pai_vscode/schemas/pai_yaml_job_config.schema.json
VS Code got "Property com.microsoft.pai.runtimeplugin is not allowed." error #3979
=> [VS Code] Fix property is not allowed error

src/hivedscheduler/config/hivedscheduler.py, src/hivedscheduler/config/hivedscheduler.yaml, src/hivedscheduler/deploy/hivedscheduler-config.yaml.template, src/hivedscheduler/deploy/hivedscheduler-service.yaml.template, src/hivedscheduler/deploy/service.yaml, src/rest-server/deploy/rest-server.yaml.template, src/rest-server/src/config/launcher.js, src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/models/v2/job/k8s.js
Expose preemption status in scheduler.
=> [Rest Server] Expose preemption status in scheduler

src/prometheus/deploy/prometheus-deployment.yaml.template
=> [Prometheus ] fix prometheus high io issue (#4019)

src/kube-runtime/src/init.d/image_checker.py, src/kube-runtime/test/docker_image_no_tag.yaml, src/kube-runtime/test/test_image_checker.py
=> [runtime] fix image check (#4015)

src/internal-storage/src/create.sh
fix a bug, which will cause internal storage service restarts periodically
=> [BugFix] fix internal storage

Jenkinsfile, tests/jenkins/stage_build.sh, tests/jenkins/stage_clean.sh, tests/jenkins/stage_deploy.sh, tests/jenkins/stage_prepare.sh, tests/jenkins/stage_test.sh, tests/jenkins/test_generate_config.sh, tests/jenkins/test_rest_server.sh
Add Jenkins stages for pure k8s version.
=> [CI/CD] Add Jenkins stages for pure k8s version

src/storage-manager/build/storage-manager.dockerfile, src/storage-manager/deploy/scripts/entrypoint.sh
Tested in intx. This config works fine for samba and nfs
=> [Storage-Manager] move apt-get to docker image

docs/hivedscheduler/devops.md, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/README.md, subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/doc/user-manual.md
Resolves https://github.com/microsoft/pai/issues/4092
=> [Hived]: Add config quick start docs

src/rest-server/src/models/v2/job-attempt.js, src/rest-server/src/utils/elasticSearch.js
=> Add log in job attempt api

src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
1. hide view history link if retry is 0
2. show warning icon if api not healthy
3. hide tensorboard link if tensorboard url is null
=> Hide warning icon if retry is 0

docs/pai-job-protocol.yaml, src/rest-server/src/config/v2/protocol.js, src/rest-server/src/models/v2/job/k8s.js
Move jobname from framework labels to annotations.
Fixes #4101.
=> [Rest Server] Remove job name length limitation

src/rest-server/package.json, src/rest-server/src/config/kubernetes.js, src/rest-server/src/models/kubernetes.js, src/rest-server/src/server.js, src/rest-server/test/setup.js
- Fix the kube config bugs.
- Workaround for the async initialization of kube config
=> [Rest Server] fix k8s api request options

src/rest-server/src/models/v2/job/k8s.js
Remove framework owner reference for priority class, ref #4117.
=> [Hotfix] Remove owner reference for priority class

examples/cluster-configuration/services-configuration.yaml, marketplace-v2/rocm-pytorch-mnist.yaml, marketplace-v2/rocm-tensorflow2.yaml, src/device-plugin/deploy/delete.sh.template, src/device-plugin/deploy/start.sh.template, src/rest-server/src/models/v2/job/k8s.js
Add support for AMD GPU:
* add AMD GPU device plugin
* support AMD GPU job submission in hived scheduler
* add AMD ROCM deep learning examples
Fixes #4090.
=> Add support for AMD GPU

src/webportal/src/app/job-submission/job-submission-page.jsx
Don't auto fill storage plugin if there is no default
storage config.
=> storage plugin bug fix

src/frameworkcontroller/deploy/service.yaml, src/kube-runtime/deploy/service.yaml, tests/jenkins/stage_deploy.sh, tests/jenkins/stage_prepare.sh
Update kube-runtime dependencies.
Closes #4078.
=> Update kube-runtime dependencies

docs/user_group_management.md
My document on user group management in basic authentication for the new design,please review.
=> Add new user group management  in basic mode document

src/webportal/src/app/cluster-view/services/service-info.js
=> [Web Portal] fix service page's URL error #4178

src/webportal/src/app/cluster-view/services/service-info.js
- Convert the `restServerUri` in `env.js` if it is relative
=> [Web Portal] fix service page's URL error

docs/k8s-dashboard/access-k8s-dashboard.md
Add doc for accessing K8S dashboard
=> add k8s dashboard doc

docs/k8s-dashboard/access-k8s-dashboard.md
Cherry-pick to master branch
* add k8s dashboard doc
* fix review comments
Closes #4137
=> add k8s dashboard doc (#4187)

src/watchdog/GOPATH/src/github.com/microsoft/watchdog/pkg/watchdog/garbage_collector.go, src/watchdog/GOPATH/src/github.com/microsoft/watchdog/pkg/watchdog/k8s_client.go, src/watchdog/GOPATH/src/github.com/microsoft/watchdog/testdata/priority_class_list.json
For health check PAI return response body if error occur.
=> [Watchdog] Fix watch dog not report error if health check failed

src/webportal/src/app/layout/components/sidebar.jsx
=> Add version in webportal

contrib/pai_vscode/src/pai/container/jobListTreeView.ts
The job list auto refresh will be trigger only when the `PAI JOB LIST` view is visible.
=> [VS Code] Fix job list auto refresh in background

contrib/pai_vscode/i18n/common.json, contrib/pai_vscode/package.json, contrib/pai_vscode/package.nls.json, contrib/pai_vscode/package.nls.zh-cn.json, contrib/pai_vscode/snippets/job_config.yaml, contrib/pai_vscode/snippets/job_runtime_plugin.yaml, contrib/pai_vscode/snippets/job_taskRole.yaml, contrib/pai_vscode/snippets/runtimePlugins/sshPlugin.yaml, contrib/pai_vscode/snippets/runtimePlugins/storagePlugin.yaml, contrib/pai_vscode/snippets/runtimePlugins/tensorboardPlugin.yaml, contrib/pai_vscode/src/common/constants.ts, contrib/pai_vscode/src/extension.ts, contrib/pai_vscode/src/pai/paiJobManager.ts, contrib/pai_vscode/src/pai/storage/storageHelper.ts, contrib/pai_vscode/src/pai/yaml/yamlCommands.ts, contrib/pai_vscode/src/pai/yaml/yamlJobConfigCompletionProvider.ts, contrib/pai_vscode/src/root.ts, contrib/pai_vscode/yarn.lock
=> [VS Code] Add RuntimePlugin snippets and right click menu

RELEASE_NOTE.md
Copy 0.16.0 release note from `pai-0.16.y` branch
This is a draft release not, feel free to give comments.
=> [doc] release note

src/rest-server/src/utils/frameworkConverter.js, src/webportal/src/app/job/job-view/fabric/job-retry/container-list.jsx
=> Fix log url in job retry page

tests/jenkins/stage_prepare.sh, tests/jenkins/test_rest_server.sh
Fix Jenkins test job failed issue caused by upstream pytorch and torchvision.
=> [CI/CD] Fix Jenkins issue caused by downloading MNIST 403

src/kube-runtime/src/init.d/initializer.py
fixes #4200 ,
Make sure the init-plugin script will not quit if `failurePolicy` set to `ignore`
=> [runtime] fix failurePolicy inconsistent

src/rest-server/src/models/v2/job/k8s.js
=> [Rest Server] Remove list pods from getting job detail

src/rest-server/src/models/v2/job/k8s.js
Support cpu job on gpu node in default scheduler.
=> [Rest Server] Support cpu job on gpu node in default scheduler

src/k8s-dashboard/deploy/k8s-dashboard.yaml.template
change k8s dashboard token ttl to 7d
=> [dashboard] change dashboard token ttl to 7d

src/rest-server/deploy/rbac.yaml
Update RBAC rules for storage.
=> [Rest Server] Update RBAC rules for storage

src/webportal/src/app/user/fabric/user-profile/storage-list.jsx
=> [webportal] show account name for Azure-file and Azure-blob in webportal

src/webportal/src/app/user/fabric/user-profile/storage-list.jsx
=> [webportal] Change storage representation

src/rest-server/src/models/v2/job/k8s.js
=> [Rest Server] fix fetch job status failed

src/rest-server/config/rest-server.yaml
Enable priority class by default.
=> [Rest Server] Enable priority class by default

.github/workflows/lint.yml, .travis.yml, src/utilities/doc_checker.py
The python 2.7 reach end of life.
=> [CI] Update python to 3.8 for lint document

src/rest-server/src/config/vc.js, src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/middlewares/v2/protocol.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/rest-server/src/utils/k8sUtils.js, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
Update virtual cluster resource metics using hived scheduler api.
Closes #4332.
=> [Rest Server] Update virtual cluster metrics using scheduler api

src/log-manager/src/nginx/nginx.conf, src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
=> [log-manager] Fix return too much log issue

src/rest-server/docs/swagger.yaml
Update job and virtual cluster api docs.
=> [Docs] Update job and virtual cluster api docs

src/webportal/src/app/user/fabric/userView/UserEditor.jsx
=> Disable `default` vc option in edit user dialog

src/rest-server/src/config/v2/group.js, src/rest-server/src/controllers/v2/group.js, src/rest-server/src/routes/v2/group.js, src/rest-server/src/routes/v2/index.js
- Add leacy and deprecated comment for API to update singal value.
- Bind group api with /api/v2/groups
- Add api put /api/v2/groups to update a group's value.
=> [Restserver] Refine group api

src/webportal/src/app/job-submission/components/sidebar/sidebar-card.jsx
=> Move chevron arrow to left

src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
=> Change title from Utilization to Allocation

src/webportal/src/app/home/home/gpu-chart.jsx
=> Refine gpu chart

src/rest-server/deploy/priority-class.yaml, src/rest-server/deploy/start.sh.template, src/rest-server/src/models/v2/job/k8s.js
Add minimal priority `-1,100,000,000` when priority class disabled.
For priority calculated by rest server, the min value is `-(127<<23)-(1<<23) = -1,073,741,824`;
For priority value in k8s, the min value is `-2,147,483,648` for signed 32-bit integer.
=> [Rest Server] Add minimal priority when priority class disabled

src/rest-server/src/controllers/v2/cluster.js, src/rest-server/src/controllers/v2/virtual-cluster.js, src/rest-server/src/models/v2/virtual-cluster/k8s.js, src/rest-server/src/models/v2/virtual-cluster/yarn.js, src/rest-server/src/routes/v2/cluster.js, src/rest-server/src/routes/v2/job.js, src/rest-server/src/routes/v2/virtual-cluster.js, src/rest-server/test/vc.js, src/webportal/src/app/home/home/conn.js, src/webportal/src/app/job-submission/utils/conn.js, src/webportal/src/app/job/job-submit-v1/job-submit.component.js, src/webportal/src/app/job/job-view/fabric/JobList/TopBar.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/conn.js, src/webportal/src/app/user/fabric/conn.js, src/webportal/src/app/vc/vc.component.js, tests/jenkins/test_rest_server.sh
* add bearer auth for job and vc api
* migrate sku types api in vc
=> [Rest Server] Update job and virtual cluster api

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/abnormal-job-list.jsx
=> Fix abnormal job list bug in home page

src/rest-server/src/config/v2/protocol.js, src/rest-server/src/models/v2/job/k8s.js
Fix log path length, set job name length limit to 255.
Closes #4391.
=> [Rest Server] Fix log path length

.travis.yml, src/rest-server/docs/swagger.yaml
- add validation of swagger to travis
- fix validation error
=> validate rest server swagger

src/pylon/deploy/pylon-config/location.conf.template, src/rest-server/config/rest-server.yaml, src/rest-server/config/rest_server.py, src/rest-server/deploy/rest-server.yaml.template, src/rest-server/package.json, src/rest-server/src/config/express.js, src/rest-server/src/config/rate-limit.js, src/rest-server/src/routes/v2/job.js, src/rest-server/yarn.lock
Add rate limit for RESTful API, defaults to:
* 600 all api requests per ip every 1 min
* 60 list job requests per user every 1 min
* 60 submit job requests per user every 1 hour
=> [Rest Server] Add rate limit for RESTful API

src/rest-server/docs/swagger.yaml, src/rest-server/src/models/v2/job/k8s.js
Update nullable fields in job api.
Closes #4424.
=> [Docs] Update nullable fields in job api

deployment/k8sPaiLibrary/template/kubelet.sh.template, docs/setup-persistent-volumes-on-pai.md, src/rest-server/src/models/v2/storage.js
Fix Azure File issues in storage.
=> [Rest Server] Fix Azure File issues in storage

deployment/k8sPaiLibrary/template/kubelet.sh.template, docs/setup-persistent-volumes-on-pai.md, src/rest-server/src/models/v2/storage.js
Fix Azure File issues in storage.
=> [Hotfix] Fix Azure File issues in storage (#4438)

src/rest-server/docs/swagger.yaml, src/rest-server/src/models/v2/job/k8s.js
Update nullable fields in job api.
=> [Hotfix] Update nullable fields in job api (#4437)

src/rest-server/docs/swagger.yaml
=> [Docs] Update schema in vc api

src/webportal/src/app/job/job-view/fabric/job-detail/util.js
=> Fix history typo

src/rest-server/docs/swagger.yaml
=> [Hotfix] Update schema in vc api (#4464)

src/rest-server/docs/swagger.yaml
=> Refine job attempt schema

src/rest-server/docs/swagger.yaml
=> Fix job attempt schema

src/rest-server/docs/swagger.yaml
=> [Docs] Update schema in storage api

src/webportal/src/app/user/fabric/userView/index.jsx
Fix https://github.com/microsoft/pai/issues/4482
=> Select `default` vc when add new users

src/rest-server/docs/swagger.yaml
=> [Hotfix] Update schema in storage api (#4491)

docs/upgrade/upgrade_to_v1.0.0.md
- change 0.18.0 to 1.0.0
- change instruction about removing gpu driver
=> Fix upgrade doc to "migrate from yarn"

src/pylon/deploy/pylon-config/nginx.conf.template
Force https if ssl cert is configured.
Closes #4470.
=> [Pylon] Force https if ssl cert is configured

src/rest-server/docs/swagger.yaml, src/rest-server/src/models/v2/job/k8s.js, src/rest-server/src/models/v2/storage.js
Support read only storage.
Closes #4503.
=> [Rest Server] Support read only storage

RELEASE_NOTE.md, RELEASE_NOTE_zh_CN.md
cherry pick from https://github.com/microsoft/pai/pull/4452
This PR will be merged into master after v1.0.0 is formally released.
=> Cherry pick to master - add release note

contrib/kubespray/example/config.yml, contrib/kubespray/quick-start/openpai.yml.template
=> Cherry pick - Configurable image_repo and extra_vars

src/storage-manager/deploy/conf/smb.conf.template
=> [storage] add write permission for dir under home folder

contrib/kubespray/script/service-boot.sh, src/dev-box/build/dev-box.common.dockerfile, src/device-plugin/deploy/start.sh.template
Update device plugin yaml download script, use svn client instead.
=> [Device Plugin] Update device plugin yaml download script

contrib/kubespray/quick-start/services-configuration.yaml.template
Remove default webportal plugins in quick start.
=> [Hotfix] Remove default webportal plugins in quick start (#4580)

README.md
https://github.com/microsoft/pai/tree/mintao/homepage-img
=> Change home page img link

src/rest-server/docs/swagger.yaml
=> [Rest Server] Update rest-server swagger

docs/manual/cluster-admin/how-to-set-up-storage.md
Update blobfuse flexvolume installer in manual.
Closes #4637.
=> [Docs] Update blobfuse flexvolume installer in manual

contrib/rocm-container-runtime/README.md, contrib/rocm-container-runtime/install.sh, contrib/rocm-container-runtime/rocm-container-runtime, contrib/rocm-container-runtime/rocm-container-runtime.conf
=> Add ROCm container runtime

src/rest-server/docs/swagger.yaml, src/rest-server/src/models/v2/storage.js
Add default field in storage list api.
=> [Rest Server] Add default field in storage list api

src/webportal/src/app/job-submission/components/data/team-detail.jsx
=> Refine team storage description [for marketplace]

contrib/api-stress-test/clean.yml, contrib/api-stress-test/readme.md, contrib/api-stress-test/roles/locust/config/templates/start.sh, contrib/api-stress-test/roles/locust/master/templates/master.yml, contrib/api-stress-test/roles/locust/master/templates/start-master.sh, contrib/api-stress-test/roles/locust/remove/defaults/main.yml, contrib/api-stress-test/roles/locust/remove/templates/remove-locust.sh, contrib/api-stress-test/roles/locust/worker/templates/start-worker.sh, contrib/api-stress-test/roles/locust/worker/templates/worker.yml, contrib/api-stress-test/roles/openpai/remove/tasks/main.yml, contrib/api-stress-test/roles/virtual-kubelet/build/templates/build.sh, contrib/api-stress-test/roles/virtual-kubelet/remove-local/defaults/main.yml, contrib/api-stress-test/roles/virtual-kubelet/remove-local/tasks/main.yml, contrib/api-stress-test/roles/virtual-kubelet/remove-local/templates/vk-remove-local.sh, contrib/api-stress-test/stress-part1.yml, contrib/api-stress-test/stress-part2.yml
1: Add kubeconfig option in kubectl command
2: Fix typo
3: Add --rm option in vk build script.
4: vk start will take much time. Seperate the stress.yml into 2 parts and aks user to deploy openpai after vk ready.
=> Ansible Task bug fix in clean.yml

src/webportal/src/app/job-submission/components/data/team-detail.jsx, src/webportal/src/app/job-submission/components/data/team-storage.jsx, src/webportal/src/app/user/fabric/user-profile/storage-list.jsx
=> [webportal] Fix permission UI of read-only storage

src/webportal/src/app/job-submission/components/data/team-detail.jsx, src/webportal/src/app/job-submission/components/data/team-storage.jsx, src/webportal/src/app/user/fabric/user-profile/storage-list.jsx
=> [webportal] Fix permission UI of read-only storage 

src/webportal/README.md, src/webportal/src/app/job-submission/components/topbar/topbar.jsx
=> Fix ```learn more``` link in submit page

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
For future FC feature: https://github.com/microsoft/frameworkcontroller/pull/56
=> Add Job ScaleDown error spec

src/webportal/package.json, src/webportal/src/app/job/job-view/fabric/job-detail/util.js, src/webportal/yarn.lock
https://support.google.com/chrome/thread/29828561?hl=en
=> Fix chrome timestamp bug of "24:xx"

src/webportal/package.json, src/webportal/src/app/cluster-view/services/service-info.js, src/webportal/yarn.lock
=> [Webportal] Update k8s proxy API

src/grafana/deploy/grafana.yaml.template
=> change grafana theme to light

src/frameworkcontroller/deploy/frameworkcontroller.yaml.template
Update to https://github.com/microsoft/frameworkcontroller/releases/tag/v0.7.0
=> Update FC Image

contrib/kubespray/preinstall.sh
an error of file extension 
change "set-host-daemon-port-range.yaml" to "set-host-daemon-port-range.yml"
=> an error of preinstall.sh

contrib/aks-engine/reset-env.sh, contrib/aks-engine/templates/k8s.json.j2, contrib/aks-engine/templates/start-openpai.sh.j2
Fix bugs in aks engine scripts.
=> Fix bugs in aks engine scripts

src/webportal/package.json, src/webportal/src/app/home/home/conn.js, src/webportal/src/app/job/job-view/fabric/JobList/Table.jsx, src/webportal/src/app/job/job-view/fabric/JobList/index.jsx, src/webportal/yarn.lock
1. show the columns in loading, user can change the col ordering when sorting error.
2. fix filter not working after click refresh button issue.
=> [Webportal] Fix column ordering and filter

src/rest-server/src/middlewares/v2/hived.js
Fix HiveD resource validation error message.
=> Fix HiveD resource validation error message

src/database-controller/config/database-controller.yaml, src/database-controller/deploy/database-controller.yaml.template, src/database-controller/src/common/framework.js, src/database-controller/src/package.json, src/database-controller/src/poller/config.js, src/database-controller/src/poller/index.js, src/database-controller/src/watcher/framework/config.js, src/database-controller/src/watcher/framework/index.js, src/database-controller/src/write-merger/config.js, src/database-controller/src/yarn.lock
- raise memory limit
- concurrency control
=> Fix scale problem for database controller

src/database-controller/src/write-merger/app.js, src/rest-server/src/config/express.js
error for listing/submitting job:
error for viewing job detail:
=> Give a friendly error message when db is down

src/webportal/src/app/job-submission/components/hived-sku-section.jsx
Add default sku type in submission form.
=> Add default sku type in submission form

src/rest-server/src/utils/frameworkConverter.js
fix #4846
Add `withoutGetPod` parameter to function `convertTaskDetail`, and set it true in `convertToJobAttempt` (will set the containerGpus field to null).
By default, the `convertTaskDetail` will still call get pod API to generate the container GPUs info.
=> [Rest-server] Remove get pod step from get job attempts

src/fluentd/src/fluent-plugin-pgjson/lib/fluent/plugin/out_pgjson.rb
=> Fix fluentd postgresql plugin

src/webportal/src/app/job-submission/models/job-protocol.js
Fix additional fields regression issue in HiveD config on webportal submission form.
=> [Hotfix] Fix additional fields regression in HiveD config (#4878)

src/webportal/src/app/job-submission/models/job-task-role.js
Use GPU number as SKU number when import config.
=> [Hotfix] Use GPU number as SKU number when import config (#4883)

contrib/kubespray/example/openpai.yml, contrib/kubespray/quick-start/openpai.yml.template, deployment/k8sPaiLibrary/template/kubelet.sh.template
Refer: https://github.com/kubernetes/kubernetes/issues/52902
=> Fix transient Pod MatchNodeSelector failed as kubelet label missing

src/internal-storage/deploy/service.yaml
=> make internal storage depend on cluster configuration

docs/manual_zh_CN/cluster-user/如何使用数据.md
How to Manage Data  translation
=> Translate Doc

src/database-controller/deploy/service.yaml
to fix #4968
Database controller should run after framework controller.
Otherwise it will fail to get framework information.
=> fix database controller dependency

contrib/kubespray/roles/requirement/worker/tasks/ubuntu-docker.yml
This PR fixed issue #4957
There's some mistake in the ansible-playbook for requirement checking
=> Fix checking requirement

contrib/aks-engine/templates/k8s.json.j2, src/rest-server/src/middlewares/v2/hived.js, src/rest-server/src/models/v2/job/k8s.js
Update pod priority calculation:
* add one bit in FIFO bits
* decrease priority value every 16s
Known issue: FIFO will be broken every ~8.5 years when mod result meets 0.
=> [Rest Server] Update pod priority calculation

src/webportal/src/app/job-submission/models/job-protocol.js
Fix sku types config issue on webportal.
Closes #5002.
=> [Webportal] Fix sku types config issue

src/webportal/src/app/job/job-view/fabric/job-detail.jsx, src/webportal/src/app/job/job-view/fabric/job-detail/components/summary.jsx
=> Move exit diagnostics to attempt level

examples/Distributed-example/cifar10-single-mul-DDP-nccl-gloo-Apex-mixed.py, examples/Distributed-example/cifar10-single-mul-DDP-nccl-gloo.py
=> Fix example

src/rest-server/docs/swagger.yaml, src/rest-server/src/controllers/v2/job.js, src/rest-server/src/routes/v2/job.js
Make a user can add/delete tags to his/her own jobs.
=> Fix tag auth

contrib/kubespray/quick-start/services-configuration.yaml.template, deployment/quick-start/services-configuration.yaml.template, docs/manual/cluster-admin/how-to-use-alert-system.md, docs_zh_CN/manual/cluster-admin/how-to-use-alert-system.md, examples/cluster-configuration/services-configuration.yaml, src/alert-manager/deploy/alert-manager-configmap.yaml.template, src/alert-manager/src/alert-handler/emails/general-templates/subject.ejs, src/prometheus/deploy/alerting/customized.rules.template, src/prometheus/deploy/alerting/gpu.rules, src/prometheus/deploy/alerting/jobs.rules, src/prometheus/deploy/alerting/k8s.rules, src/prometheus/deploy/alerting/node.rules, src/prometheus/deploy/alerting/pai-services.rules, src/webportal/src/app/layout/components/alerts.jsx
Alert Severity: 
-  Add severity label for predefined & customized alerts : fatal / error / warn / info 
-  Show severity in mail/webportal
-  Introduce in related doc
=> Alert Severity

contrib/kubespray/example/openpai.yml, contrib/kubespray/quick-start/openpai.yml.template
=> Set coreDNS requests to zero

src/pylon/deploy/pylon-config/location.conf.template
Remove yarn log-redirection config.
update config for log-manager
=> change pylon config for log-manager redirection

docs/manual/cluster-admin/how-to-set-up-virtual-clusters.md, src/rest-server/src/models/v2/job/k8s.js
Support CPU jobs on GPU nodes in HiveD scheduler.
Closes #5058.
=> Support CPU jobs on GPU nodes in HiveD scheduler

contrib/kubespray/script/kubernetes-boot.sh, contrib/kubespray/script/service-boot.sh, src/dev-box/build/dev-box.common.dockerfile
Fix part of the deployment issues in #5001 
services-boot.sh:
-  use the same version of kubernetes in dev-box and services-boot.sh
- remove redundant package / source code dependencies
- clean up `dev-box-quick-start` docker in the beginning if exists 
kubernetes.sh
- remove kubectl installation
=> Deployment process refine

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
=> Update Browse Log Folder

docs_zh_CN/manual/cluster-admin/how-to-set-up-virtual-clusters.md, docs_zh_CN/manual/cluster-admin/how-to-uninstall-openpai.md, docs_zh_CN/manual/cluster-admin/how-to-use-alert-system.md, docs_zh_CN/manual/cluster-admin/installation-faqs-and-troubleshooting.md, docs_zh_CN/manual/cluster-admin/installation-guide.md, docs_zh_CN/manual/cluster-admin/troubleshooting.md
See comparison between current master and pai-1.3.y branch:
https://github.com/microsoft/pai/compare/6e80802..1752ad95
=> Align zh_CN doc

src/rest-server/config/rest-server.yaml
Update rate limit values for RESTful API with database.
=> [Rest Server] Update rate limit values for RESTful API

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
- Fix the problem that the dialog box could not pop up in the waiting state
- Display a message when there is no log
=> fix log folder detail

src/alert-manager/src/alert-handler/controllers/mail.js
=> fix query param issue

src/grafana/deploy/grafana-configuration/pai-serviceview-dashboard.json.template, src/job-exporter/src/collector.py
=> Monitor log-cleaner service 

src/webportal/src/app/layout/components/alerts.jsx
=> fix get alerts inhibition issue in webportal

src/webportal/src/app/user/fabric/user-profile/bounded-cluster-dialog.jsx
=> Give user a hint on https error

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx
=> fix show all log crash

src/device-plugin/deploy/device-plugin.yaml
=> Set a larger `github.com/fuse` resource volume

contrib/kubespray/script/configuration-kubespray.sh, contrib/kubespray/script/openpai-generator.py
fix path issues involved in #5158
=> [installation] fix path issues

src/k8s-job-exit-spec/config/k8s-job-exit-spec.yaml
Remove oserror:.*input/output error, since it may caused by local filesystem/remote filesystem. Retry may fix this issue.
=> update error spec

src/webportal/src/app/user/fabric/user-profile/bounded-cluster-dialog.jsx
=> fix uri check for job transfer

contrib/kubespray/environment-check.yml, contrib/kubespray/roles/requirement/computing-devices/enflame.com_dtu/tasks/main.yml, src/device-plugin/deploy/delete.sh.template, src/device-plugin/deploy/start.sh.template
add Enflame DTU device plugin in device plugin service as requested by #5140
=> add dtu device plugin

contrib/kubespray/script/service-boot.sh, src/dev-box/build/start-script.sh
- fix typo: dev-box-gusui -> dev-box-quick-start
- use git reset -> git checkout : checkout will not update local code when PAI_BRANCH_NAME = master
=> fix checkout issue when using master branch

deployment/confStorage/synchronization.py, deployment/confStorage/upload.py, deployment/configCmd.py, deployment/utility/pai_version.py
- Fix #5208 
- Refine pylint of the code touched in this PR
=> Refine pai-version / cluster-id checking log

src/webportal/src/app/home/home.jsx, src/webportal/src/app/home/home/virtual-cluster-statistics.jsx
=> Fix home page css style

docs/manual/cluster-admin/troubleshooting.md
Provide a possible solution for `NodeGpuCountChanged` alert.
Related Issue: #5217
=> add troubleshooting doc for NodeGpuCountChanged alert

src/webportal/src/app/job/job-view/fabric/job-detail/components/task-role-container-list.jsx, src/webportal/src/app/job/job-view/fabric/task-attempt/task-attempt-list.jsx
Fix #5207 
Change log list name change: `all` to `stdout+stderr`
Always refresh token when try to download log. Avoid token expired.
=> Enhance log UI

contrib/kubespray/config/config.yaml, contrib/kubespray/script/environment.sh, contrib/kubespray/script/service-boot.sh, contrib/kubespray/script/start-service-in-dev-box.sh, docs/manual/cluster-admin/installation-guide.md
- use only local pai code
- fix pip3 issue
=> use only local pai folder for installation

contrib/kubespray/script/configuration-kubespray.sh, contrib/kubespray/script/kubernetes-boot.sh
Fix first issue in #5231
Use only local pai folder
=> [installation] Remove `~pai-deploy/pai` reference

src/webportal/src/app/components/util/job.js
=> [Webportal] Fix export csv file error 'dur.toFormat is not a function'

examples/Distributed-example/cifar10-single-mul-DDP-nccl-gloo-Apex-mixed.py
close https://github.com/microsoft/openpaimarketplace/issues/126
=> Fix cifar10-single-mul-ddp-nccl-gloo-apex-mixed.py

src/marketplace-restserver/build/marketplace-restserver.k8s.dockerfile, src/marketplace-webportal/build/marketplace-webportal.k8s.dockerfile
1. Always use latest image when deploying master branch pai
2. Use specific version of marketplace image in each release version
=> Use latest marketplace image in master branch

docs/manual/cluster-admin/how-to-add-and-remove-nodes.md, docs/manual/cluster-admin/installation-guide.md
=> fix add/remove node doc issue

contrib/submit-job-v2/package.json, contrib/submit-job-v2/yarn.lock, src/webportal/package.json, src/webportal/yarn.lock
=> Update openpai-js-sdk version for security alert

docs/manual/cluster-admin/basic-management-operations.md, docs/manual/cluster-admin/how-to-add-and-remove-nodes.md, docs/manual/cluster-admin/how-to-customize-cluster-by-plugins.md, docs/manual/cluster-admin/how-to-manage-users-and-groups.md, docs/manual/cluster-admin/how-to-set-up-storage.md, docs/manual/cluster-admin/how-to-set-up-virtual-clusters.md, docs/manual/cluster-admin/how-to-uninstall-openpai.md, docs/manual/cluster-admin/how-to-use-alert-system.md, docs/manual/cluster-admin/installation-faqs-and-troubleshooting.md, docs/manual/cluster-admin/installation-guide.md, docs/manual/cluster-admin/recommended-practice.md, docs/manual/cluster-admin/troubleshooting.md, docs/manual/cluster-admin/upgrade-guide.md, docs/manual/cluster-user/how-to-manage-data.md, docs/manual/cluster-user/quick-start.md, docs/manual/cluster-user/use-marketplace.md, docs/manual/cluster-user/use-vscode-extension.md, docs_zh_CN/manual/cluster-admin/how-to-use-alert-system.md, docs_zh_CN/manual/cluster-admin/installation-faqs-and-troubleshooting.md, docs_zh_CN/manual/cluster-admin/troubleshooting.md
Improve the language in the admin manual
=> Docs modification (admin)

src/database-controller/sdk/index.js, src/database-controller/sdk/package.json, src/database-controller/src/common/framework.js, src/rest-server/src/controllers/v2/job.js, src/rest-server/src/models/v2/job/k8s.js
add a field `launchTime` in Framework table
=> fix get jobs api launchedTime field issue

src/rest-server/docs/swagger.yaml, src/rest-server/src/middlewares/token.js, src/rest-server/src/models/token.js, src/rest-server/src/routes/token.js
=> sign token with job info

docs/manual/cluster-admin/how-to-manage-users-and-groups.md
- fix broken img link
- refine doc structure
=> refine authentication doc

src/webportal/src/app/job-submission/components/submission-section.jsx
Fixes https://github.com/microsoft/openpaimarketplace/issues/234
=> Add type `template` and isPrivate `true` when saving from submission page

docs/manual/cluster-admin/how-to-manage-users-and-groups.md, docs_zh_CN/manual/cluster-admin/how-to-manage-users-and-groups.md
=> sync auth zh doc

README.md, docs/index.md, docs_zh_CN/index.md
Old:
[![Build Status](https://github.com/microsoft/pai/workflows/CI/badge.svg)](https://github.com/microsoft/pai/actions)
New:
[![Build Status](https://openpai.visualstudio.com/OpenPAI/_apis/build/status/OpenPAI-nightly-build?branchName=master)](https://openpai.visualstudio.com/OpenPAI/_build/latest?definitionId=25&branchName=master)
=> [CI] Use nightly-build status in README.md

src/webportal/src/app/job-submission-demo/components/save-template-dialog.jsx, src/webportal/src/app/job-submission-demo/components/sidebar/index.jsx, src/webportal/src/app/job-submission-demo/components/submission-section.jsx, src/webportal/src/app/job-submission-demo/components/template-selection.jsx, src/webportal/src/app/job-submission-demo/job-edit-page.jsx, src/webportal/src/app/job-submission-demo/job-submission-page.jsx, src/webportal/src/app/job-submission-demo/utils/conn.js, src/webportal/src/app/job-submission-demo/utils/utils.js
1. Add save-template in new submission page
2. Add default description and share option in save template dialog 
3. Add more template option seletions
=> Add save-template in new submission page

src/database-controller/sdk/index.js, src/database-controller/src/common/framework.js, src/database-controller/src/poller/index.js
[Work Items](https://github.com/microsoft/pai/issues/5337#issuecomment-839551679)
- DB Framework table definition
- save framework config to DB when submit jobs
- dbc lint
=> [job status change notif] parse job config to DB

src/alert-manager/deploy/alert-manager-configmap.yaml.template, src/alert-manager/deploy/alert-templates/job-status-change/html.ejs, src/alert-manager/deploy/alert-templates/job-status-change/subject.ejs
Part 3 in [Work Items](https://github.com/microsoft/pai/issues/5337#issuecomment-839551679)
=> [job status change notif] handle the alerts in alert-manager

src/frameworkcontroller/deploy/delete.sh
=> make deletion of framework crd idempotent

src/webportal/src/app/job-submission/models/protocol-schema.js
support customize  runtime plugin execution phrase. The value can be `preTaskStarts` or `postTaskSucceeds`
=> support customize  runtime plugin execution phrase

src/rest-server/deploy/rest-server.yaml.template, src/rest-server/docs/swagger.yaml, src/rest-server/package.json, src/rest-server/src/config/launcher.js, src/rest-server/src/controllers/v2/alert.js, src/rest-server/src/models/v2/alert.js, src/rest-server/src/routes/v2/alert.js, src/rest-server/src/routes/v2/index.js, src/rest-server/test/setup.js, src/rest-server/yarn.lock
=> add alert related API

src/webportal/deploy/webportal.yaml.template, src/webportal/src/app/env.js.template, src/webportal/src/app/layout/components/alerts.jsx
The API was introduced in #5498
=> [webportal] Get alerts from REST Server instead of alert manager

contrib/autoscaler/scaler.py
SimpleScaler: open all nodes if there are pending jobs
=> turn on all nodes if has_pending_pods

src/prometheus-pushgateway/build/prometheus-pushgateway.common.dockerfile, src/prometheus-pushgateway/config/prometheus-pushgateway.yaml, src/prometheus-pushgateway/config/prometheus_pushgateway.py, src/prometheus-pushgateway/deploy/delete.sh, src/prometheus-pushgateway/deploy/prometheus-pushgateway.yaml.template, src/prometheus-pushgateway/deploy/refresh.sh, src/prometheus-pushgateway/deploy/service.yaml, src/prometheus-pushgateway/deploy/start.sh, src/prometheus-pushgateway/deploy/stop.sh, src/prometheus/deploy/prometheus-configmap.yaml.template
- add prometheus pushgateway service
- set `hornor_label` as true in Prometheus to keep `instance` label valuable
=> add prometheus pushgateway service; adjust prometheus config

src/grafana/deploy/grafana-configuration/pai-jobview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-nodeview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-taskroleview-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-tasks-in-node-dashboard.json.template, src/grafana/deploy/grafana-configuration/pai-taskview-dashboard.json.template, src/prometheus-pushgateway/config/prometheus-pushgateway.yaml
- change default job-to-live time to 30s
- fix task related network metrics issues
=> fix grafana config & pushgateway parameter issue

contrib/kubespray/script/environment.sh
Signed-off-by: siaimes <34199488+siaimes@users.noreply.github.com>
=> This can save some time when installing the environment.

src/prometheus-pushgateway/deploy/prometheus-pushgateway.yaml.template
Set resources requests for 1000 workers & resources limits for 2500 workers
=> pushgateway: request memory / cpu for 1000 clients

src/frameworkcontroller/deploy/frameworkcontroller.yaml.template
Ref: https://github.com/microsoft/frameworkcontroller/releases/tag/v1.0.0
=> Update FC image to v1.0.0

contrib/kubespray/config/config.yaml, contrib/kubespray/quick-start/openpai.yml.template, docs/manual/cluster-admin/installation-guide.md, docs_zh_CN/manual/cluster-admin/installation-guide.md
fix #5150, serialize image pulls issue.
Signed-off-by: siaimes <34199488+siaimes@users.noreply.github.com>
=> fix #5150, serialize image pulls issue.
